"""Quotes — generated by eos new-app, fixed by coding agent.

Original prompt: "A simple quote of the day app that picks a random
inspirational quote and shows it. Store quotes in app data."
"""

import json
import random

from emptyos.sdk import BaseApp, cli_command, web_route

DEFAULT_QUOTES = [
    "The best way to get started is to quit talking and begin doing. - Walt Disney",
    "Don't let yesterday take up too much of today. - Will Rogers",
    "It's not whether you get knocked down, it's whether you get up. - Vince Lombardi",
    "Dream bigger. Do bigger.",
    "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
    "Great things never come from comfort zones.",
    "Push yourself, because no one else is going to do it for you.",
    "The OS itself is empty. You fill it. - EmptyOS",
]


class QuotesApp(BaseApp):

    async def setup(self):
        await super().setup()
        quotes_file = self.data_dir / "quotes.json"
        if not quotes_file.exists():
            quotes_file.write_text(json.dumps(DEFAULT_QUOTES, indent=2))

    def _load_quotes(self) -> list[str]:
        path = self.data_dir / "quotes.json"
        if path.exists():
            return json.loads(path.read_text())
        return DEFAULT_QUOTES

    def get_quote(self) -> str:
        quotes = self._load_quotes()
        state = self.load_state({"last": -1})
        idx = random.choice([i for i in range(len(quotes)) if i != state["last"]] or [0])
        state["last"] = idx
        self.save_state(state)
        return quotes[idx]

    # ── Hub panel contribution ──
    async def panel_quote(self) -> dict | None:
        """Quote of the day for the hub footer."""
        raw = self.get_quote()
        if not raw:
            return None
        # Split "text — author" heuristically
        text, author = raw, ""
        for sep in (" - ", " — ", " – "):
            if sep in raw:
                parts = raw.rsplit(sep, 1)
                text, author = parts[0].strip(), parts[1].strip()
                break
        return {"text": text, "author": author}

    # ── Voice Assistant contribution ──
    async def assistant_context(self) -> str | None:
        raw = self.get_quote()
        if not raw:
            return None
        for sep in (" - ", " — ", " – "):
            if sep in raw:
                parts = raw.rsplit(sep, 1)
                text, author = parts[0].strip(), parts[1].strip()
                return f"Daily inspiration: {text} ({author})"
        return f"Daily inspiration: {raw}"

    @cli_command("quotes", help="Show a random inspirational quote")
    async def cmd_quotes(self):
        print(f"\n  {self.get_quote()}\n")

    @web_route("GET", "/api/quote")
    async def api_quote(self, request):
        quote = self.get_quote()
        await self.emit("quotes:shown", {"quote": quote[:80]})
        return {"quote": quote}

    @web_route("GET", "/api/list")
    async def api_list(self, request):
        return self._load_quotes()

    @web_route("POST", "/api/add")
    async def api_add(self, request):
        data = await request.json()
        quote = data.get("quote", "").strip()
        if not quote:
            return {"error": "quote is required"}
        quotes = self._load_quotes()
        quotes.append(quote)
        path = self.data_dir / "quotes.json"
        path.write_text(json.dumps(quotes, indent=2))
        return {"ok": True, "total": len(quotes)}

    @web_route("POST", "/api/delete")
    async def api_delete(self, request):
        data = await request.json()
        index = data.get("index")
        if index is None:
            return {"error": "index is required"}
        quotes = self._load_quotes()
        if 0 <= index < len(quotes):
            removed = quotes.pop(index)
            path = self.data_dir / "quotes.json"
            path.write_text(json.dumps(quotes, indent=2))
            return {"ok": True, "removed": removed}
        return {"error": "index out of range"}

    @web_route("POST", "/api/generate")
    async def api_generate(self, request):
        """AI-generate a quote on a topic."""
        data = await request.json()
        topic = data.get("topic", "life and growth")
        result = await self.think_safe(
            f"Generate one original, inspiring quote about '{topic}'. "
            f"Return ONLY the quote text with attribution '- AI'. No explanation.",
            domain="text", temperature=0.9,
            fallback="",
        )
        if not result:
            return {"error": "AI is offline — try again when a provider is available."}
        quote = result.strip().strip('"')
        # Auto-add to collection
        quotes = self._load_quotes()
        quotes.append(quote)
        (self.data_dir / "quotes.json").write_text(json.dumps(quotes, indent=2))
        await self.emit("quotes:generated", {"quote": quote[:80], "topic": topic})
        return {"quote": quote, "total": len(quotes), "provenance": self.last_provenance()}

    @web_route("POST", "/api/vault-sync")
    async def api_vault_sync(self, request):
        """Save quote collection to vault as a markdown note."""
        quotes = self._load_quotes()
        favs_path = self.data_dir / "favorites.json"
        favs = json.loads(favs_path.read_text()) if favs_path.exists() else []

        lines = [
            "# Quote Collection",
            "",
            f"*{len(quotes)} quotes, {len(favs)} favorites*",
            "",
        ]

        if favs:
            lines.append("## Favorites")
            lines.append("")
            for q in favs:
                lines.append(f"> {q}")
                lines.append("")

        lines.append("## All Quotes")
        lines.append("")
        for q in quotes:
            lines.append(f"> {q}")
            lines.append("")

        self.vault_write("quotes-collection.md", "\n".join(lines))
        return {"synced": len(quotes), "favorites": len(favs)}

    @web_route("GET", "/api/favorites")
    async def api_favorites(self, request):
        path = self.data_dir / "favorites.json"
        if path.exists():
            return json.loads(path.read_text())
        return []

    @web_route("POST", "/api/favorite")
    async def api_favorite(self, request):
        data = await request.json()
        quote = data.get("quote", "").strip()
        if not quote:
            return {"error": "quote is required"}
        path = self.data_dir / "favorites.json"
        favs = json.loads(path.read_text()) if path.exists() else []
        if quote not in favs:
            favs.append(quote)
            path.write_text(json.dumps(favs, indent=2))
        return {"ok": True, "total": len(favs)}
