"""Build EmptyOS.app — a native macOS bundle that boots the real daemon.

Dev-grade build (Tier "open" per .claude/rules/product-packaging.md): the .app
is a thin shell that runs THIS repo via a dedicated venv. It references the
working clone — it does NOT copy the tree in — so EmptyOS keeps evolving in
place (conversation mode) and a `git pull` updates the app with no rebuild.

This deliberately avoids PyInstaller: the daemon discovers apps/plugins/engines
by scanning the filesystem at runtime (emptyos/sdk/app_layout.py), which a
static freeze can't capture without per-app hidden-import gymnastics. A venv +
shell-stub bundle is both simpler and more honest about what's running.

Run ON A MAC (PyInstaller/codesign aren't needed; this is pure stdlib + venv):

    python3 products/desktop-macos/build_app.py            # venv + EmptyOS.app
    python3 products/desktop-macos/build_app.py --no-venv  # rebuild bundle only

Output: products/desktop-macos/dist/EmptyOS.app
        ~/Library/Application Support/EmptyOS/venv   (the runtime env)

Then: open products/desktop-macos/dist/EmptyOS.app   (first time: right-click →
Open to clear Gatekeeper — the app is unsigned in this tier).
"""

from __future__ import annotations

import plistlib
import shutil
import stat
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[1]
DIST = HERE / "dist"
APP = DIST / "EmptyOS.app"
VENV = Path.home() / "Library" / "Application Support" / "EmptyOS" / "venv"

BUNDLE_ID = "net.binbian.emptyos"
VERSION = "0.1.0"


def make_venv() -> Path:
    """Create the runtime venv and install the repo + pywebview into it."""
    py = VENV / "bin" / "python3"
    if not py.exists():
        VENV.parent.mkdir(parents=True, exist_ok=True)
        print(f"creating venv → {VENV}")
        subprocess.run([sys.executable, "-m", "venv", str(VENV)], check=True)
    subprocess.run([str(py), "-m", "pip", "install", "--upgrade", "pip"], check=True)
    print("installing EmptyOS (editable) + pywebview — this can take a minute…")
    subprocess.run([str(py), "-m", "pip", "install", "-e", str(REPO)], check=True)
    subprocess.run([str(py), "-m", "pip", "install", "-r",
                    str(HERE / "requirements.txt")], check=True)
    return py


def venv_python() -> Path:
    py = VENV / "bin" / "python3"
    if not py.exists():
        sys.exit(f"venv missing at {VENV}; run without --no-venv first.")
    return py


def write_bundle(py: Path) -> None:
    shutil.rmtree(APP, ignore_errors=True)
    macos = APP / "Contents" / "MacOS"
    res = APP / "Contents" / "Resources"
    macos.mkdir(parents=True)
    res.mkdir(parents=True)

    # Info.plist
    info = {
        "CFBundleName": "EmptyOS",
        "CFBundleDisplayName": "EmptyOS",
        "CFBundleExecutable": "EmptyOS",
        "CFBundleIdentifier": BUNDLE_ID,
        "CFBundleVersion": VERSION,
        "CFBundleShortVersionString": VERSION,
        "CFBundlePackageType": "APPL",
        "LSMinimumSystemVersion": "11.0",
        "NSHighResolutionCapable": True,
        # No Dock-less background: this IS the app window.
        "LSUIElement": False,
    }
    icon = HERE / "AppIcon.icns"
    if icon.exists():
        shutil.copy2(icon, res / "AppIcon.icns")
        info["CFBundleIconFile"] = "AppIcon"
    with open(APP / "Contents" / "Info.plist", "wb") as f:
        plistlib.dump(info, f)

    # Executable shell stub — bakes the repo + venv python, execs the launcher.
    stub = macos / "EmptyOS"
    stub.write_text(
        "#!/bin/bash\n"
        "# Generated by build_app.py — references the working EmptyOS clone.\n"
        f'export EOS_REPO="{REPO}"\n'
        "export PYTHONIOENCODING=utf-8\n"
        f'exec "{py}" "{HERE / "launcher.py"}" "$@"\n',
        encoding="utf-8",
    )
    stub.chmod(stub.stat().st_mode | stat.S_IEXEC | stat.S_IXGRP | stat.S_IXOTH)


def main() -> None:
    if "--no-venv" not in sys.argv:
        py = make_venv()
    else:
        py = venv_python()
    write_bundle(py)
    print(f"\nbuilt → {APP}")
    print("Open it: right-click → Open the first time (unsigned, Gatekeeper).")
    print("Headless smoke test:")
    print(f'  "{py}" "{HERE / "launcher.py"}" --no-window')


if __name__ == "__main__":
    main()
