"""eos boot — generate and manage system startup sequence."""

from __future__ import annotations

import os
import platform
from pathlib import Path

import typer
from rich.console import Console
from rich.table import Table

console = Console()

# Windows Startup folder
_STARTUP_DIR = Path(
    os.environ.get("APPDATA", ""),
    "Microsoft", "Windows", "Start Menu", "Programs", "Startup",
)
_STARTUP_VBS = _STARTUP_DIR / "start-emptyos.vbs"

# How long to wait (ms) for services before starting EmptyOS
_SERVICE_INIT_DELAY_MS = 8000


def _collect_services(data: dict) -> list[dict]:
    """Collect all autostart services from config."""
    services = []

    # Plugins with autostart = true
    plugins = data.get("plugins", {})
    for pid, pcfg in plugins.items():
        if not isinstance(pcfg, dict):
            continue
        if not pcfg.get("autostart"):
            continue
        services.append({
            "name": pid,
            "source": "plugin",
            "launcher": pcfg.get("launcher", ""),
            "executable": pcfg.get("executable", ""),
            "host": pcfg.get("host", ""),
        })

    # Startup programs (non-plugin)
    startup = data.get("startup", {})
    for name, exe_path in startup.items():
        if isinstance(exe_path, str) and exe_path:
            services.append({
                "name": name,
                "source": "startup",
                "launcher": "",
                "executable": exe_path,
                "host": "",
            })

    return services


def generate_boot_vbs(data: dict, eos_dir: str) -> str:
    """Generate boot.vbs content from config."""
    lines = [
        "' EmptyOS Boot Sequence",
        "' Auto-generated by: eos boot --generate",
        "' Re-run that command after changing emptyos.toml to update.",
        "'",
        "' All processes launch headless (no CMD windows).",
        "",
        'Set WshShell = CreateObject("WScript.Shell")',
        'Set fso = CreateObject("Scripting.FileSystemObject")',
        "",
    ]

    services = _collect_services(data)
    svc_count = 0

    for svc in services:
        launcher = svc["launcher"].replace("/", "\\")
        executable = svc["executable"].replace("/", "\\")
        name = svc["name"]

        if launcher:
            launcher_path = Path(launcher)
            launcher_dir = str(launcher_path.parent).replace("/", "\\")
            # Check directory exists before launching
            lines.append(f"' --- {name} ---")
            lines.append(f'If fso.FolderExists("{launcher_dir}") Then')
            lines.append(f'    WshShell.CurrentDirectory = "{launcher_dir}"')
            lines.append(
                f'    WshShell.Run "cmd /c ""{launcher}"" > nul 2>&1", 0, False'
            )
            lines.append("End If")
            lines.append("")
            svc_count += 1
        elif executable:
            exe_path = executable.replace("/", "\\")
            lines.append(f"' --- {name} ---")
            lines.append(f'WshShell.Run """{exe_path}""", 0, False')
            lines.append("")
            svc_count += 1

    if svc_count > 0:
        lines.append(f"' Wait for {svc_count} service(s) to initialize")
        lines.append(f"WScript.Sleep {_SERVICE_INIT_DELAY_MS}")
        lines.append("")

    # EmptyOS itself
    eos_dir_win = eos_dir.replace("/", "\\")
    lines.append("' --- EmptyOS ---")
    lines.append(f'WshShell.CurrentDirectory = "{eos_dir_win}"')
    lines.append(
        'WshShell.Run "cmd /c python -m emptyos start >> emptyos.log 2>&1", 0, False'
    )
    lines.append("")

    return "\n".join(lines)


def _generate_startup_vbs(eos_dir: str) -> str:
    """Generate the thin Startup folder VBS that delegates to boot.vbs."""
    boot_path = Path(eos_dir, "boot.vbs").resolve()
    return (
        "' EmptyOS Boot — delegates to boot.vbs in project dir\n"
        'Set WshShell = CreateObject("WScript.Shell")\n'
        f'WshShell.Run "wscript ""{boot_path}""", 0, False\n'
    )


def boot_command(
    generate: bool = typer.Option(False, "--generate", help="Generate boot.vbs from config"),
    install: bool = typer.Option(False, "--install", help="Generate + install to Windows Startup"),
    uninstall: bool = typer.Option(False, "--uninstall", help="Remove from Windows Startup"),
    show: bool = typer.Option(False, "--show", help="Show current boot sequence"),
):
    """Manage system startup sequence for EmptyOS and its services."""
    if platform.system() != "Windows":
        console.print("[yellow]Boot management is currently Windows-only.[/yellow]")
        raise typer.Exit(1)

    if uninstall:
        _uninstall_boot()
        return

    # All other operations need config
    from emptyos.kernel.config import Config
    try:
        config = Config()
    except FileNotFoundError as e:
        console.print(f"[red]{e}[/red]")
        raise typer.Exit(1)
    data, eos_dir = config._data, str(config.path.parent)

    if show or not (generate or install):
        _show_boot(data, eos_dir)
        return

    # Generate (or install which implies generate)
    boot_vbs = generate_boot_vbs(data, eos_dir)
    boot_path = config.path.parent / "boot.vbs"
    boot_path.write_text(boot_vbs, encoding="utf-8")
    console.print(f"[green]Generated {boot_path}[/green]")

    if install:
        install_boot(eos_dir)


def _show_boot(data: dict, eos_dir: str):
    """Display the current boot sequence."""
    services = _collect_services(data)

    table = Table(title="EmptyOS Boot Sequence")
    table.add_column("Order", style="dim", width=6)
    table.add_column("Service", style="bold")
    table.add_column("Source")
    table.add_column("Launch Method")
    table.add_column("Host")

    for i, svc in enumerate(services, 1):
        method = "launcher" if svc["launcher"] else "executable" if svc["executable"] else "—"
        path = svc["launcher"] or svc["executable"] or "—"
        table.add_row(
            str(i),
            svc["name"],
            svc["source"],
            f"{method}: {path}" if path != "—" else "—",
            svc["host"] or "—",
        )

    # EmptyOS itself is always last — read actual bind from config
    try:
        from emptyos.kernel.config import Config
        _cfg = Config()
        _emptyos_addr = f"{_cfg.host}:{_cfg.port}"
    except Exception:
        _emptyos_addr = "127.0.0.1:9000"
    table.add_row(
        str(len(services) + 1),
        "[bold green]emptyos[/bold green]",
        "core",
        f"python -m emptyos start",
        _emptyos_addr,
    )

    console.print(table)

    # Check install status
    if _STARTUP_VBS.exists():
        console.print(f"\n[green]Installed[/green] in Startup folder: {_STARTUP_VBS}")
    else:
        console.print(f"\n[yellow]Not installed[/yellow] — run [bold]eos boot --install[/bold] to start on login")

    boot_path = Path(eos_dir) / "boot.vbs"
    if boot_path.exists():
        console.print(f"Boot script: {boot_path}")
    else:
        console.print("[yellow]boot.vbs not generated yet[/yellow] — run [bold]eos boot --generate[/bold]")


def install_boot(eos_dir: str):
    """Install boot.vbs into Windows Startup folder."""
    if not _STARTUP_DIR.exists():
        console.print(f"[red]Startup folder not found: {_STARTUP_DIR}[/red]")
        raise typer.Exit(1)

    vbs_content = _generate_startup_vbs(eos_dir)
    _STARTUP_VBS.write_text(vbs_content, encoding="utf-8")
    console.print(f"[green]Installed to {_STARTUP_VBS}[/green]")
    console.print("EmptyOS will start automatically on next login.")


def _uninstall_boot():
    """Remove from Windows Startup folder."""
    if _STARTUP_VBS.exists():
        _STARTUP_VBS.unlink()
        console.print(f"[green]Removed {_STARTUP_VBS}[/green]")
        console.print("EmptyOS will no longer start on login.")
    else:
        console.print("[yellow]Not installed — nothing to remove.[/yellow]")
