"""Unit tests for scripts/check_vault_structure.py — the vault structure guard.

Daemon-free (``test_unit_`` prefix → conftest lets it run offline). Builds a
synthetic vault in tmp_path and asserts every drift class is classified,
purged, and — critically — that review-class items and legitimately-named
files ("Chapter 2.md") are NEVER touched.
"""

import importlib.util
import json
import os
import sys
import time
import tomllib
from pathlib import Path

import pytest

_REPO = Path(__file__).resolve().parent.parent
_spec = importlib.util.spec_from_file_location(
    "check_vault_structure", _REPO / "scripts" / "check_vault_structure.py"
)
vs = importlib.util.module_from_spec(_spec)
sys.modules["check_vault_structure"] = vs
_spec.loader.exec_module(vs)

_OLD = time.time() - 3 * 86400  # comfortably past the 24h age gate


def _w(p: Path, text: str, old: bool = True) -> Path:
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(text, encoding="utf-8")
    if old:
        os.utime(p, (_OLD, _OLD))
    return p


@pytest.fixture
def vault(tmp_path):
    v = tmp_path / "vault"

    # — declared PARA skeleton —
    (v / "00_Inbox").mkdir(parents=True)          # kept-empty (contract keep glob)
    _w(v / "CLAUDE.md", "conventions\n")

    # — empty dir chain (fixpoint: emptyB empty → emptyA holds only emptyB) —
    (v / "20_Areas/emptyA/emptyB").mkdir(parents=True)

    # — numbered dups —
    _w(v / "30_Resources/note.md", "same body\n")
    _w(v / "30_Resources/note 2.md", "same body\n")          # identical → safe
    _w(v / "30_Resources/other.md", "original\n")
    _w(v / "30_Resources/other 2.md", "edited copy\n")       # divergent → review
    _w(v / "30_Resources/Chapter 2.md", "a real chapter\n")  # no base → untouched

    # — sync conflict (identical) —
    _w(v / "50_Journal/2026-06-30.md", "day\n")
    _w(v / "50_Journal/2026-06-30.sync-conflict-20260630-185225-6TUUOTZ.md", "day\n")

    # — tmp / zero-byte / Untitled —
    _w(v / "10_Projects/x/test-write.tmp", "t\n")
    _w(v / "00_Inbox/Critical", "")                              # zero-byte, old → safe
    _w(v / "00_Inbox/fresh-stub.md", "", old=False)              # zero-byte, FRESH → skipped
    _w(v / "40_Archive/Untitled.md", "real content here\n")     # non-empty → review

    # — undeclared top-level entries —
    (v / "Music/Albums").mkdir(parents=True)
    _w(v / "Music/Albums/a.md", "album\n")
    _w(v / "index.js", "console.log(1)\n")

    return v


def _scan(v):
    contract, path, generated = vs.load_contract(v)
    return vs.scan(v, contract), contract, path, generated


def test_contract_autogenerated(vault):
    _, contract, path, generated = _scan(vault)
    assert generated
    assert path == vault / vs.CONTRACT_REL
    # round-trips through a real TOML parser
    parsed = tomllib.load(open(path, "rb"))
    assert "00_Inbox" in parsed["toplevel"]["folders"]
    assert parsed["junk"]["min_age_hours"] == 24
    # second load reads the file, doesn't regenerate
    _, _, generated2 = vs.load_contract(vault)
    assert not generated2


def test_classification(vault):
    f, *_ = _scan(vault)

    safe_names = {cat: {p.name for p in paths} for cat, paths in f.safe.items()}
    assert "note 2.md" in safe_names["numbered_dups"]
    assert any("sync-conflict" in n for n in safe_names["sync_conflict"])
    assert "test-write.tmp" in safe_names["tmp_files"]
    assert "Critical" in safe_names["zero_byte"]
    assert "fresh-stub.md" not in safe_names["zero_byte"]      # age gate

    empty_rel = {str(p.relative_to(vault)).replace("\\", "/") for p in f.safe["empty_dirs"]}
    assert "20_Areas/emptyA" in empty_rel and "20_Areas/emptyA/emptyB" in empty_rel
    assert "00_Inbox" not in empty_rel                          # keep glob

    review_paths = {r["path"] for rows in f.review.values() for r in rows}
    assert "30_Resources/other 2.md" in review_paths            # divergent dup
    assert "40_Archive/Untitled.md" in review_paths             # non-empty Untitled
    assert "Music/" in review_paths and "index.js" in review_paths  # undeclared top-level
    assert "CLAUDE.md" not in review_paths                      # declared root file

    # legitimately-named "Chapter 2.md" (no base file) is in NO bucket
    all_flagged = review_paths | {p.name for paths in f.safe.values() for p in paths}
    assert "Chapter 2.md" not in all_flagged
    assert "30_Resources/Chapter 2.md" not in all_flagged


def test_purge_safe_only(vault):
    f, contract, *_ = _scan(vault)
    summary = vs.purge(vault, f, contract)

    assert summary["files_deleted"] >= 4   # note 2, sync-conflict, .tmp, Critical
    assert summary["dirs_deleted"] >= 2    # emptyA + emptyB (fixpoint)
    assert summary["review_skipped"] == f.review_count

    # safe classes gone
    assert not (vault / "30_Resources/note 2.md").exists()
    assert not (vault / "20_Areas/emptyA").exists()
    assert not (vault / "00_Inbox/Critical").exists()
    # base + review + legit + kept survive
    assert (vault / "30_Resources/note.md").exists()
    assert (vault / "30_Resources/other 2.md").exists()
    assert (vault / "30_Resources/Chapter 2.md").exists()
    assert (vault / "40_Archive/Untitled.md").exists()
    assert (vault / "Music/Albums/a.md").exists()
    assert (vault / "00_Inbox").exists()                        # kept-empty
    assert (vault / "20_Areas").exists()                        # depth-1 never pruned
    assert (vault / "00_Inbox/fresh-stub.md").exists()          # age gate

    # 10_Projects/x emptied by the .tmp delete → swept in the same purge
    assert not (vault / "10_Projects/x").exists()

    # second scan: no safe left except nothing; review remains
    f2 = vs.scan(vault, contract)
    assert f2.safe_count == 0
    assert f2.review_count == f.review_count


def test_main_exit_code_and_json(vault, capsys):
    rc = vs.main(["--vault", str(vault), "--json"])
    out = capsys.readouterr().out.strip()
    env = json.loads(out)                       # exactly one JSON object on stdout
    assert set(env) == {"ok", "code", "message", "data"}
    assert env["ok"] is False and env["code"] == "review"
    assert rc == env["data"]["review_count"] == 4   # divergent dup, Untitled, Music/, index.js
    assert env["data"]["contract_generated"] is True


def test_main_purge_no_snapshot(vault, capsys):
    rc = vs.main(["--vault", str(vault), "--purge", "--no-snapshot", "--json"])
    env = json.loads(capsys.readouterr().out.strip())
    assert "purged" in env["data"]
    assert env["data"]["purged"]["files_deleted"] >= 4
    assert rc == 4                                # review count unchanged by purge
    assert not (vault / "30_Resources/note 2.md").exists()
    assert (vault / "30_Resources/other 2.md").exists()


def test_retention_ttl(tmp_path):
    """[retention] dirs: expired files → safe; fresh files untouched; files in
    a retention dir are exempt from every other junk rule (a backup named
    'note 2.md' is a deliberate copy, not a dup)."""
    v = tmp_path / "vault"
    (v / "00_Inbox").mkdir(parents=True)
    tb = v / "99_Attachments/temp-backup"
    _w(tb / "old-note-2026-01-10-0900.md", "old backup\n")                  # _OLD = 3d ago
    _w(tb / "sub/deep-old.md", "nested old backup\n")
    _w(tb / "recent.md", "fresh backup\n", old=False)
    _w(tb / "note 2.md", "would be a dup elsewhere\n")                      # exempt from dup rule
    _w(v / "20_Areas/normal-old.md", "not in a retention dir\n")            # old but NOT expired class

    contract = vs.default_contract()
    contract["retention"] = {"99_Attachments/temp-backup": 2}               # 2-day TTL; _OLD is 3d
    f = vs.scan(v, contract)

    expired = {str(p.relative_to(v)).replace("\\", "/") for p in f.safe.get("retention_expired", [])}
    assert "99_Attachments/temp-backup/old-note-2026-01-10-0900.md" in expired
    assert "99_Attachments/temp-backup/sub/deep-old.md" in expired
    assert "99_Attachments/temp-backup/note 2.md" in expired                # TTL rule, not dup rule
    assert "99_Attachments/temp-backup/recent.md" not in expired
    assert not any("normal-old" in p for p in expired)
    assert "numbered_dups" not in f.safe and "numbered_dups" not in f.review

    vs.purge(v, f, contract)
    assert not (tb / "old-note-2026-01-10-0900.md").exists()
    assert (tb / "recent.md").exists()
    assert (v / "20_Areas/normal-old.md").exists()
    assert not (tb / "sub").exists()                                        # emptied → swept


def test_embedded_env_advisory(tmp_path):
    v = tmp_path / "vault"
    (v / "00_Inbox").mkdir(parents=True)
    _w(v / "30_Resources/tool/venv/lib/thing.py", "x\n")
    _w(v / "10_Projects/dash/frontend/node_modules/pkg/index.js", "x\n")
    _w(v / "30_Resources/normal/note.md", "fine\n")

    f = vs.scan(v, vs.default_contract())
    envs = {r["path"] for r in f.advisory.get("embedded_env", [])}
    assert "30_Resources/tool/venv" in envs
    assert "10_Projects/dash/frontend/node_modules" in envs
    assert len(envs) == 2
    # advisory only — never purgeable
    assert "embedded_env" not in f.safe
    vs.purge(v, f, vs.default_contract())
    assert (v / "30_Resources/tool/venv/lib/thing.py").exists()


def test_clean_vault_exits_zero(tmp_path, capsys):
    v = tmp_path / "clean"
    (v / "00_Inbox").mkdir(parents=True)
    _w(v / "CLAUDE.md", "x\n")
    rc = vs.main(["--vault", str(v), "--json"])
    env = json.loads(capsys.readouterr().out.strip())
    assert rc == 0 and env["ok"] is True and env["code"] == "ok"
