"""Pins for scripts/mine_corrections.py — the correction miner.

Per `.claude/rules/audits.md`, a scanner sitting at "0 findings" on a healthy
tree has proved nothing until it has been watched going red for **each failure
shape it claims to cover**. So every filter here is tested in both directions:
the thing it must catch, and the specific noise class it was built to reject.

Each rejection case below is a shape that was measured in the real corpus and
was, at some point during calibration, a false positive.
"""

from __future__ import annotations

import importlib.util
import json
import sys
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "scripts"))
sys.path.insert(0, str(REPO))

_spec = importlib.util.spec_from_file_location(
    "mine_corrections", REPO / "scripts" / "mine_corrections.py"
)
mc = importlib.util.module_from_spec(_spec)
assert _spec.loader is not None
# Register before exec: @dataclass resolves annotations through
# sys.modules[cls.__module__], which is None for an unregistered module.
sys.modules["mine_corrections"] = mc
_spec.loader.exec_module(mc)


# ------------------------------------------------------------------ fixtures


def _rec(text: str, *, ts: str, session: str, uid: str, **over) -> dict:
    rec = {
        "type": "user",
        "uuid": uid,
        "sessionId": session,
        "timestamp": ts,
        "message": {"role": "user", "content": text},
    }
    rec.update(over)
    return rec


def write_transcript(root: Path, project: str, name: str, records: list[dict]) -> Path:
    d = root / project
    d.mkdir(parents=True, exist_ok=True)
    p = d / f"{name}.jsonl"
    p.write_text(
        "\n".join(json.dumps(r, ensure_ascii=False) for r in records) + "\n",
        encoding="utf-8",
    )
    return p


# ------------------------------------------------- what a correction IS / ISN'T


@pytest.mark.parametrize(
    "text",
    [
        "no, you should use my session",
        "no, why you invent new thing, we do not have to discuss the options",
        "you ignored my suggestion about the browser extension",
        "don't run python through the console",
        "from now on, always lease a sandbox first",
        "I already told you to check the tracked files",
        "you should have read the treatment first",
        "不要每次都重新生成，说过了",
    ],
)
def test_detects_behaviour_correction(text):
    marks = mc.match_markers(text)
    assert marks, f"no marker fired on {text!r}"
    assert mc.is_behaviour_correction(text, marks)


@pytest.mark.parametrize(
    "text,why",
    [
        # A choice about the domain, not about the agent. This class was 38 of
        # 72 marker hits on the real corpus and would have buried everything.
        ("no, let us go with the renewables option - we want to switch soon", "domain choice"),
        ("no, another one", "picking a different option"),
        ("no, resume at 9:00", "a plain instruction"),
        # Bare "again"/"always" are ordinary requests. Both matched an early
        # pattern set and were cut.
        ("plan again?", "bare again"),
        ("shall we try this again?", "bare again"),
        ("applied, I guess it is okay - we can always claim the refund later", "bare always"),
    ],
)
def test_rejects_non_behaviour_turn(text, why):
    marks = mc.match_markers(text)
    assert not mc.is_behaviour_correction(text, marks), why


def test_long_turn_is_never_a_correction():
    """Median human turn is 41 chars. Pasted emails and task briefs contain
    every marker word; the length cap is what keeps them out."""
    brief = "Please review the plan below. " + ("context " * 80) + " you are wrong about this."
    assert len(brief) > mc.MAX_CORRECTION_CHARS
    assert mc.match_markers(brief) == ()


@pytest.mark.parametrize(
    "text,source",
    [
        ("Stop hook feedback:\n[continue until done]: the transcript shows...", None),
        ("This session is being continued from a previous conversation...", None),
        ("<command-name>/clear</command-name>", None),
        ("Caveat: The messages below were generated by the user while running...", None),
        ("no, you should not do that", "sdk"),
        ("no, you should not do that", "system"),
    ],
)
def test_machine_turns_are_not_human(text, source):
    assert mc.is_machine_turn(text, source)


def test_real_turn_is_not_machine():
    assert not mc.is_machine_turn("no, you should use my session", "typed")


# ------------------------------------------------------------------ tokenizer


def test_contraction_stems_are_not_terms():
    """The word tokenizer splits on the apostrophe, so "don't" yields "don".
    That token appeared in a third of all corrections and produced the
    top-scoring cluster on the first run — a pure artifact."""
    terms = mc.salient_terms("don't do that, you shouldn't have, it won't work")
    for stem in ("don", "shouldn", "won"):
        assert stem not in terms, f"{stem!r} leaked into terms"


def test_cjk_bigrams_become_terms():
    assert "画面" in mc.salient_terms("不要这么现实的画面")


# ----------------------------------------------------------------------- lift


def test_lift_separates_theme_from_generic_verb():
    """Measured separation the threshold was set from: a term used only when
    correcting scores far above one that every request contains."""
    theme = mc.term_lift(corr_df=3, n_corr=37, global_df=11, n_turns=1700)
    verb = mc.term_lift(corr_df=3, n_corr=37, global_df=37, n_turns=1700)
    assert theme > mc.MIN_TERM_LIFT > verb


def test_generic_verb_seeds_no_cluster():
    """A word appearing in every ordinary request must not become a theme even
    when it appears in several corrections."""
    turns = [
        mc.Turn(uid=f"g{i}", text="can you change the layout", ts="", session="s", project="p", path="")
        for i in range(200)
    ]
    corr = [
        mc.Correction(
            turn=mc.Turn(
                uid=f"c{i}", text="no, you should change the layout", ts="", session=f"s{i}",
                project="p", path="",
            ),
            markers=("opening-no",),
        )
        for i in range(4)
    ]
    mc.assign_terms(corr, turns + [c.turn for c in corr])
    assert all("change" not in c.terms for c in corr)


# ------------------------------------------------------------ sweep + clusters


def _corpus(root: Path) -> None:
    """Three sessions, one recurring behaviour correction, plus noise."""
    write_transcript(
        root,
        "proj",
        "s1",
        [
            _rec("no, use the browser extension, not python in the console",
                 ts="2026-08-01T10:00:00Z", session="s1", uid="u1"),
            _rec("no, another one", ts="2026-08-01T10:05:00Z", session="s1", uid="u2"),
        ],
    )
    write_transcript(
        root,
        "proj",
        "s2",
        [
            _rec("you ignored my browser extension suggestion again",
                 ts="2026-08-05T10:00:00Z", session="s2", uid="u3"),
            _rec("Stop hook feedback:\n[go on]: nothing to report",
                 ts="2026-08-05T10:01:00Z", session="s2", uid="u4"),
        ],
    )
    write_transcript(
        root,
        "proj",
        "s3",
        [
            _rec("don't do that, the browser extension is the elegant way",
                 ts="2026-08-09T10:00:00Z", session="s3", uid="u5"),
        ],
    )


def test_sweep_finds_the_recurring_theme(tmp_path):
    root = tmp_path / "projects"
    _corpus(root)
    clusters, _, n_turns, n_corr = mc.sweep([root], {}, now="2026-08-10T00:00:00Z", min_lift=1.0)
    assert n_turns == 4, "machine turns must not be counted as human"
    assert n_corr == 3
    cands = mc.candidates(clusters, min_count=3, min_sessions=2, include_resolved=False)
    # Co-occurring terms both seed a cluster on purpose (see assign_terms):
    # the same evidence can support more than one candidate theme, and the
    # human picks by reading the quotes. Here "browser" and "extension" appear
    # together in all three corrections, so both are legitimate names for it.
    by_term = {c.term: c for c in cands}
    assert "browser" in by_term
    assert by_term["browser"].count == 3
    assert len(set(by_term["browser"].sessions)) == 3


def test_one_session_is_not_a_pattern(tmp_path):
    """Three corrections inside one conversation are one argument being had.
    ``min_sessions`` — not ``min_count`` — is what makes a theme durable."""
    root = tmp_path / "projects"
    write_transcript(
        root,
        "proj",
        "only",
        [
            _rec(f"no, you should use the browser extension ({i})",
                 ts=f"2026-08-0{i+1}T10:00:00Z", session="same", uid=f"x{i}")
            for i in range(3)
        ],
    )
    clusters, _, _, _ = mc.sweep([root], {}, now="2026-08-10T00:00:00Z", min_lift=1.0)
    assert mc.candidates(clusters, min_count=3, min_sessions=2, include_resolved=False) == []
    assert mc.candidates(clusters, min_count=3, min_sessions=1, include_resolved=False)


def test_rerunning_does_not_inflate_counts(tmp_path):
    """Lifetime counts accumulate across runs because transcripts rotate — so
    the seen-set is the only thing standing between that and double counting."""
    root = tmp_path / "projects"
    _corpus(root)
    state: dict = {}
    clusters, seen, _, _ = mc.sweep([root], state, now="2026-08-10T00:00:00Z", min_lift=1.0)
    state = mc.to_state(clusters, seen)
    first = {c.term: c.count for c in clusters.values()}

    clusters2, seen2, _, _ = mc.sweep([root], state, now="2026-08-10T00:00:00Z", min_lift=1.0)
    assert {c.term: c.count for c in clusters2.values()} == first


def test_count_survives_transcript_rotation(tmp_path):
    """The evidence rotates away; the count must not."""
    root = tmp_path / "projects"
    _corpus(root)
    clusters, seen, _, _ = mc.sweep([root], {}, now="2026-08-10T00:00:00Z", min_lift=1.0)
    state = mc.to_state(clusters, seen)

    for p in root.rglob("*.jsonl"):
        p.unlink()
    clusters2, _, n_turns, _ = mc.sweep([root], state, now="2026-09-20T00:00:00Z", min_lift=1.0)
    assert n_turns == 0
    kept = [c for c in clusters2.values() if c.term == "browser"]
    assert kept and kept[0].count == 3
    assert kept[0].quotes == [], "quotes are re-derived live, never persisted"


def test_dismissed_theme_stays_dismissed(tmp_path):
    """A dismissal is a durable decision — the whole point of persisting state."""
    root = tmp_path / "projects"
    _corpus(root)
    clusters, seen, _, _ = mc.sweep([root], {}, now="2026-08-10T00:00:00Z", min_lift=1.0)
    for c in clusters.values():
        c.status = "dismissed"
        c.note = "one-off"
    state = mc.to_state(clusters, seen)

    clusters2, _, _, _ = mc.sweep([root], state, now="2026-08-11T00:00:00Z", min_lift=1.0)
    again = next(c for c in clusters2.values() if c.term == "browser")
    assert again.status == "dismissed" and again.note == "one-off"
    assert mc.candidates(clusters2, min_count=3, min_sessions=2, include_resolved=False) == []
    assert mc.candidates(clusters2, min_count=3, min_sessions=2, include_resolved=True)


def test_state_holds_no_transcript_text(tmp_path):
    """Turn text must never reach disk — a second copy of transcript content is
    exactly what the deferred agent-transcript leak scan exists to worry about."""
    root = tmp_path / "projects"
    _corpus(root)
    clusters, seen, _, _ = mc.sweep([root], {}, now="2026-08-10T00:00:00Z", min_lift=1.0)
    blob = json.dumps(mc.to_state(clusters, seen))
    assert "browser extension" not in blob
    assert "python in the console" not in blob


# ------------------------------------------------------------------------ cli


def test_cli_json_envelope(tmp_path, capsys):
    root = tmp_path / "projects"
    _corpus(root)
    rc = mc.main(
        [
            "--root", str(root),
            "--state", str(tmp_path / "state.json"),
            "--json", "--min-lift", "1.0", "--min-count", "3", "--min-sessions", "2",
        ]
    )
    payload = json.loads(capsys.readouterr().out)
    assert set(payload) == {"ok", "code", "message", "data"}
    assert rc == 1 and payload["ok"] is False, "findings mean not-ok, per agent-cli"
    assert payload["data"]["candidates"][0]["term"] == "browser"


def test_cli_dismiss_persists(tmp_path, capsys):
    root = tmp_path / "projects"
    _corpus(root)
    state = tmp_path / "state.json"
    common = ["--root", str(root), "--state", str(state), "--min-lift", "1.0"]

    mc.main(common + ["--json"])
    ids = [c["id"] for c in json.loads(capsys.readouterr().out)["data"]["candidates"]]
    cid = ids[0]

    for one in ids:
        mc.main(common + ["--json", "--dismiss", one[:6], "--note", "not a rule"])
        assert json.loads(capsys.readouterr().out)["data"]["status"] == "dismissed"

    rc = mc.main(common + ["--json"])
    out = json.loads(capsys.readouterr().out)
    assert rc == 0 and out["data"]["candidates"] == []
    assert json.loads(state.read_text(encoding="utf-8"))["clusters"][cid]["note"] == "not a rule"


def test_cli_accept_prints_a_stub(tmp_path, capsys):
    root = tmp_path / "projects"
    _corpus(root)
    state = tmp_path / "state.json"
    common = ["--root", str(root), "--state", str(state), "--min-lift", "1.0"]
    mc.main(common + ["--json"])
    cid = json.loads(capsys.readouterr().out)["data"]["candidates"][0]["id"]

    assert mc.main(common + ["--accept", cid[:6]]) == 0
    out = capsys.readouterr().out
    assert "type: feedback" in out and "**How to apply:**" in out


def test_cli_rejects_unknown_id(tmp_path, capsys):
    root = tmp_path / "projects"
    _corpus(root)
    rc = mc.main(
        ["--root", str(root), "--state", str(tmp_path / "s.json"), "--dismiss", "zzzzzz"]
    )
    assert rc == 2
    assert "no theme id" in capsys.readouterr().out


def test_missing_root_is_not_an_error(tmp_path, capsys):
    rc = mc.main(["--root", str(tmp_path / "nope"), "--state", str(tmp_path / "s.json")])
    assert rc == 0


def test_verdict_flags_are_mutually_exclusive(tmp_path):
    """Accepting and dismissing in one call is a mistake, not a last-flag-wins."""
    with pytest.raises(SystemExit):
        mc.main(["--accept", "aaa", "--dismiss", "bbb", "--state", str(tmp_path / "s.json")])


def test_evidence_carries_a_normalised_source_path(tmp_path, capsys):
    """A quote is only useful if you can go read what it was answering."""
    root = tmp_path / "projects"
    _corpus(root)
    mc.main(
        ["--root", str(root), "--state", str(tmp_path / "s.json"), "--json", "--min-lift", "1.0"]
    )
    quote = json.loads(capsys.readouterr().out)["data"]["candidates"][0]["quotes"][0]
    assert quote["path"].endswith(".jsonl")
    assert "\\" not in quote["path"], "windows separators must be normalised"


# ------------------------------------------------------------------- aliases


def test_co_occurring_terms_collapse_to_one_candidate(tmp_path):
    """"browser" and "extension" appear in all three of the same corrections —
    one theme wearing two names. Reporting both means reading the same quotes
    twice and judging them twice."""
    root = tmp_path / "projects"
    _corpus(root)
    clusters, _, _, _ = mc.sweep([root], {}, now="2026-08-10T00:00:00Z", min_lift=1.0)
    raw = [c for c in clusters.values() if c.term in {"browser", "extension"}]
    assert len(raw) == 2, "both terms still get their own stable cluster id"

    cands = mc.candidates(clusters, min_count=3, min_sessions=2, include_resolved=False)
    assert len(cands) == 1
    assert cands[0].aliases, "the loser must be reported as an alias, not dropped silently"


def test_a_verdict_covers_the_whole_alias_group(tmp_path, capsys):
    """Dismissing one name while its alias stays open would resurface the same
    three quotes next sweep under a different word."""
    root = tmp_path / "projects"
    _corpus(root)
    state = tmp_path / "state.json"
    common = ["--root", str(root), "--state", str(state), "--min-lift", "1.0"]

    mc.main(common + ["--json"])
    cid = json.loads(capsys.readouterr().out)["data"]["candidates"][0]["id"]
    mc.main(common + ["--json", "--dismiss", cid[:6]])
    assert json.loads(capsys.readouterr().out)["data"]["aliases"]

    stored = json.loads(state.read_text(encoding="utf-8"))["clusters"]
    judged = {r["term"]: r["status"] for r in stored.values() if r["term"] in {"browser", "extension"}}
    assert judged == {"browser": "dismissed", "extension": "dismissed"}

    rc = mc.main(common + ["--json"])
    assert rc == 0 and json.loads(capsys.readouterr().out)["data"]["candidates"] == []


def test_rotated_evidence_never_groups(tmp_path):
    """An empty evidence set means "cannot be grouped", not "groups with every
    other empty one" — otherwise a rotation would merge unrelated themes."""
    a = mc.Cluster(cid="a", term="one", count=3, sessions=["s1", "s2"])
    b = mc.Cluster(cid="b", term="two", count=3, sessions=["s1", "s2"])
    clusters = {"a": a, "b": b}
    assert mc.evidence_key(a) == frozenset()
    assert [c.cid for c in mc.alias_group(clusters, "a")] == ["a"]
    assert len(mc.candidates(clusters, min_count=3, min_sessions=2, include_resolved=False)) == 2


# ------------------------------------------------------------------- pruning


def _cl(**kw) -> "mc.Cluster":
    base = dict(cid="x", term="t", count=1, sessions=["s"], last_seen="2026-01-01T00:00:00Z")
    base.update(kw)
    return mc.Cluster(**base)


@pytest.mark.parametrize(
    "cluster,expected,why",
    [
        (_cl(), True, "open, never recurred, silent for a year"),
        (_cl(last_seen="2026-11-01T00:00:00Z"), False, "still recent"),
        (_cl(count=3), False, "at threshold — the accumulating count IS the mechanism"),
        (_cl(status="dismissed"), False, "a verdict is never forgotten"),
        (_cl(status="accepted"), False, "a verdict is never forgotten"),
    ],
)
def test_prune_rule(cluster, expected, why):
    assert mc.prunable(cluster, now="2027-01-01T00:00:00Z") is expected, why


def test_state_forgets_only_stale_noise(tmp_path):
    clusters = {
        "keep-recent": _cl(cid="keep-recent", term="recent", last_seen="2026-12-20T00:00:00Z"),
        "keep-real": _cl(cid="keep-real", term="real", count=4),
        "keep-judged": _cl(cid="keep-judged", term="judged", status="dismissed"),
        "drop": _cl(cid="drop", term="stale"),
    }
    stored = mc.to_state(clusters, {}, now="2027-01-01T00:00:00Z")["clusters"]
    assert set(stored) == {"keep-recent", "keep-real", "keep-judged"}


def test_pruning_is_opt_in(tmp_path):
    """to_state without a clock keeps everything — a caller that cannot date the
    sweep must not silently drop history."""
    clusters = {"drop": _cl(cid="drop")}
    assert set(mc.to_state(clusters, {})["clusters"]) == {"drop"}
