"""Unit tests for scripts/bus_sync_guard.py. Pure — no git, no daemon.

`_git` is monkeypatched with canned porcelain, because the interesting cases
(another session mid-edit, my own new file, a skill directory) are states that
are tedious to stage for real and easy to get subtly wrong in a fixture repo.

Both directions are pinned deliberately: a guard that never fires is useless,
and a guard that fires on your own staged work deletes it — which is exactly
what the first run of this script did.
"""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parent.parent


@pytest.fixture(scope="module")
def guard():
    spec = importlib.util.spec_from_file_location(
        "bus_sync_guard_under_test", REPO / "scripts" / "bus_sync_guard.py"
    )
    mod = importlib.util.module_from_spec(spec)
    sys.modules["bus_sync_guard_under_test"] = mod
    spec.loader.exec_module(mod)
    return mod


def _fake_git(status="", bus_status="", ls_files=""):
    """Stand in for _git, dispatching on the subcommand the caller used."""
    def run(*args):
        if args[0] == "ls-files":
            return ls_files
        if args[0] == "status":
            return bus_status if "--" in args else status
        return ""
    return run


# ── path mapping ──────────────────────────────────────────────────────


def test_native_for_maps_both_pairs(guard):
    assert guard._native_for(".agent-bus/rules/testing.md") == ".claude/rules/testing.md"
    assert guard._native_for(".agent-bus/skills/x/SKILL.md") == ".claude/skills/x/SKILL.md"


def test_native_for_ignores_files_with_no_native_counterpart(guard):
    """manifest.toml is generated by import, not mirrored from anywhere — it
    must never be classified as somebody's work-in-progress."""
    assert guard._native_for(".agent-bus/manifest.toml") is None
    assert guard._native_for(".agent-bus/sections/claude-testing.md") is None


# ── the index discriminator ───────────────────────────────────────────


def test_staged_native_is_not_foreign(guard, monkeypatch):
    """Staged means mine-in-this-commit. Treating it as foreign is what made
    the guard delete the skill it was being written for."""
    monkeypatch.setattr(guard, "_git", _fake_git(
        status="A  .claude/skills/mine/SKILL.md\nM  .claude/rules/mine.md\n"))
    assert guard._foreign_native() == set()


def test_unstaged_and_untracked_native_are_foreign(guard, monkeypatch):
    monkeypatch.setattr(guard, "_git", _fake_git(
        status=" M .claude/rules/theirs.md\n?? .claude/skills/theirs/\n"))
    assert guard._foreign_native() == {".claude/rules/theirs.md", ".claude/skills/theirs/"}


def test_partially_staged_native_counts_as_mine(guard, monkeypatch):
    """`MM` — staged AND further edited. The index says I claimed it, so the
    commit is mine to make; the worktree delta is my problem, not a foreign one."""
    monkeypatch.setattr(guard, "_git", _fake_git(status="MM .claude/rules/mine.md\n"))
    assert guard._foreign_native() == set()


# ── classification ────────────────────────────────────────────────────


def test_tracked_bus_file_is_reverted_untracked_is_removed(guard, monkeypatch):
    monkeypatch.setattr(guard, "_git", _fake_git(
        status=" M .claude/rules/theirs.md\n?? .claude/skills/newthing/\n",
        bus_status=" M .agent-bus/rules/theirs.md\n?? .agent-bus/skills/newthing/\n",
        ls_files=".agent-bus/rules/theirs.md\n",
    ))
    res = guard.scan()
    assert [r["bus"] for r in res["revert"]] == [".agent-bus/rules/theirs.md"]
    assert [r["bus"] for r in res["remove"]] == [".agent-bus/skills/newthing/"]


def test_clean_native_is_left_alone(guard, monkeypatch):
    """A bus file whose native is committed is a legitimate sync, not a
    capture — the common case, and the one a false positive would block."""
    monkeypatch.setattr(guard, "_git", _fake_git(
        status="",
        bus_status=" M .agent-bus/rules/settled.md\n M .agent-bus/manifest.toml\n",
        ls_files=".agent-bus/rules/settled.md\n.agent-bus/manifest.toml\n",
    ))
    assert guard.scan() == {"revert": [], "remove": []}


def test_untracked_skill_dir_matches_every_file_beneath_it(guard, monkeypatch):
    """git reports an untracked directory as one entry with a trailing slash,
    while the bus side lists files — so prefix matching is what connects them."""
    monkeypatch.setattr(guard, "_git", _fake_git(
        status="?? .claude/skills/theirs/\n",
        bus_status="?? .agent-bus/skills/theirs/SKILL.md\n"
                   "?? .agent-bus/skills/theirs/references/notes.md\n",
        ls_files="",
    ))
    assert len(guard.scan()["remove"]) == 2


def test_my_staged_skill_survives_alongside_their_untracked_one(guard, monkeypatch):
    """The scenario that motivated the index discriminator."""
    monkeypatch.setattr(guard, "_git", _fake_git(
        status="A  .claude/skills/mine/SKILL.md\n?? .claude/skills/theirs/\n",
        bus_status="?? .agent-bus/skills/mine/SKILL.md\n?? .agent-bus/skills/theirs/SKILL.md\n",
        ls_files="",
    ))
    removed = [r["bus"] for r in guard.scan()["remove"]]
    assert removed == [".agent-bus/skills/theirs/SKILL.md"]


# ── fail-loud contract ────────────────────────────────────────────────


def test_git_failure_raises_rather_than_reporting_clean(guard):
    """Empty output would read as 'nothing foreign' — the one wrong answer a
    safety check must never give."""
    # `rev-parse --unknown-flag` exits 0 (it echoes unrecognised options back),
    # so use a lookup that genuinely fails.
    with pytest.raises(RuntimeError, match="failed"):
        guard._git("rev-parse", "--verify", "refs/heads/definitely-no-such-branch")
