#!/bin/sh
# EmptyOS Docker entrypoint — first-boot bootstrap.
#
# Makes a naked `docker run -p 9000:9000 -v $HOME/vault:/vault emptyos:latest`
# work without any pre-existing config. Idempotent: re-runs are no-ops.
#
# Behavior:
#   1. Default network mode is "private" (binds 0.0.0.0, requires auth)
#      because Docker port mapping doesn't reach a 127.0.0.1 bind inside
#      the container. Override with -e EOS_NETWORK_MODE=local|public.
#   2. If $EOS_CONFIG (default /app/emptyos.toml) is missing, write a
#      minimal stub. EOS_* env vars override every field at runtime.
#   3. If no EOS_NETWORK_AUTH_TOKEN is set, generate one and persist it
#      to /app/data/.auth-token so it survives restarts. Print on first
#      generation only.
#   4. If /vault is empty, seed PARA folders so the kernel's vault
#      watcher and apps that probe folder existence don't trip.
#
# Mount points:
#   /vault       — your markdown vault (host bind-mount or named volume)
#   /app/data    — runtime state: events db, syslog, generated token

set -eu

EOS_CONFIG="${EOS_CONFIG:-/app/emptyos.toml}"
VAULT_PATH="${EOS_NOTES_PATH:-/vault}"
DATA_DIR="${EOS_OS_DATA_DIR:-/app/data}"
TOKEN_FILE="$DATA_DIR/.auth-token"

# 1. Sane Docker default for network mode.
if [ -z "${EOS_NETWORK_MODE:-}" ]; then
    EOS_NETWORK_MODE=private
    export EOS_NETWORK_MODE
fi

# 2. Ensure config exists. Kernel hard-requires the file (see
#    emptyos/kernel/config.py); env vars override field-by-field.
if [ ! -f "$EOS_CONFIG" ]; then
    mkdir -p "$(dirname "$EOS_CONFIG")"
    cat > "$EOS_CONFIG" <<EOF
# Auto-generated by docker/entrypoint.sh on first boot.
# Edit this file or use EOS_* environment variables to override fields.

[os]
name = "EmptyOS"
data_dir = "$DATA_DIR"
log_level = "INFO"

[notes]
path = "$VAULT_PATH"
watch = true

[network]
mode = "$EOS_NETWORK_MODE"
port = 9000

[demo]
enabled = false

[cloud]
consent = "ask"

[scheduler]
enabled = true
timezone = "UTC"

[apps]
path = "./apps"
autostart = []
EOF
    echo "[entrypoint] wrote default config to $EOS_CONFIG"
fi

# 3. Auth token: persist a generated one across restarts via the data volume.
mkdir -p "$DATA_DIR"
if [ -z "${EOS_NETWORK_AUTH_TOKEN:-}" ]; then
    if [ -f "$TOKEN_FILE" ]; then
        EOS_NETWORK_AUTH_TOKEN="$(cat "$TOKEN_FILE")"
        export EOS_NETWORK_AUTH_TOKEN
    else
        EOS_NETWORK_AUTH_TOKEN="$(python -c 'import secrets;print(secrets.token_urlsafe(32))')"
        export EOS_NETWORK_AUTH_TOKEN
        printf '%s' "$EOS_NETWORK_AUTH_TOKEN" > "$TOKEN_FILE"
        chmod 600 "$TOKEN_FILE" 2>/dev/null || true
        echo "============================================================"
        echo "  EmptyOS — generated a fresh auth token (save this once)"
        echo "  Token:     $EOS_NETWORK_AUTH_TOKEN"
        echo "  Persisted: $TOKEN_FILE (in the /app/data volume)"
        echo "  Override:  docker run -e EOS_NETWORK_AUTH_TOKEN=your-token ..."
        echo "============================================================"
    fi
fi

# 4. Seed an empty vault with PARA folders so apps that probe paths don't fail.
if [ -d "$VAULT_PATH" ] && [ -z "$(ls -A "$VAULT_PATH" 2>/dev/null)" ]; then
    for d in 00_Inbox 10_Projects 20_Areas 30_Resources 40_Archive 50_Journal; do
        mkdir -p "$VAULT_PATH/$d"
    done
    echo "[entrypoint] seeded empty vault at $VAULT_PATH with PARA folders"
fi

exec "$@"
