"""Quotes — generated by eos new-app, fixed by coding agent.

Original prompt: "A simple quote of the day app that picks a random
inspirational quote and shows it. Store quotes in app data."

quotes-data-not-vault: the collection is entirely human-curated content
someone builds up over years — CLAUDE.md's own storage rule says that
belongs in the vault, not data/apps/quotes/*.json (machine telemetry).
Migrated to a VaultLibrary-backed collection, one note per quote under
30_Resources/EmptyOS/quotes/. data/ now holds only the "last shown
index" cache (load_state/save_state) — genuinely ephemeral UI state,
the one thing the original note's own suggested fix said to keep there.
"""

import json
import random

from datetime import date, datetime, timezone

from emptyos.sdk import BaseApp, VaultLibrary, cli_command, scheduled, web_route
from emptyos.sdk.utils import is_truthy, path_segment_error, safe_path_segment, slugify

DEFAULT_QUOTES = [
    "The best way to get started is to quit talking and begin doing. - Walt Disney",
    "Don't let yesterday take up too much of today. - Will Rogers",
    "It's not whether you get knocked down, it's whether you get up. - Vince Lombardi",
    "Dream bigger. Do bigger.",
    "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
    "Great things never come from comfort zones.",
    "Push yourself, because no one else is going to do it for you.",
    "The OS itself is empty. You fill it. - EmptyOS",
]

TAG = "quote"
FOLDER = f"30_Resources/EmptyOS/{TAG}s"


def _quote_text(q) -> str:
    """A legacy (pre-migration) stored quote is either a plain string or
    {"text","category"}. Only used by the one-time migration reader."""
    return q.get("text", "") if isinstance(q, dict) else str(q)


def _quote_category(q) -> str:
    if isinstance(q, dict):
        return (q.get("category") or "general").strip().lower()
    return "general"


class QuoteLibrary(VaultLibrary):
    tag = TAG
    fields = {
        "text": str, "category": str, "favorite": str,  # frontmatter is string-typed
        "source": str, "created": str,
    }
    sort_key = "created"
    fallback_folder = FOLDER


class QuotesApp(BaseApp):
    async def setup(self):
        await super().setup()
        self.quotes = QuoteLibrary(self)
        self._migrate_legacy_if_needed()

    # ── One-time migration from data/apps/quotes/*.json ─────────────────
    def _migration_marker(self):
        return self.data_dir / ".migrated-to-vault"

    def _migrate_legacy_if_needed(self) -> None:
        """Idempotent: guarded by a sentinel file so it only ever runs
        once. The legacy quotes.json/favorites.json are left on disk
        untouched (never deleted) — this is a forward migration, not a
        destructive one."""
        marker = self._migration_marker()
        if marker.exists():
            return
        legacy_path = self.data_dir / "quotes.json"
        if not legacy_path.exists():
            marker.write_text(datetime.now(timezone.utc).isoformat())
            return
        try:
            legacy_quotes = json.loads(legacy_path.read_text())
        except (OSError, ValueError):
            legacy_quotes = []
        favs_path = self.data_dir / "favorites.json"
        try:
            legacy_favs = set(json.loads(favs_path.read_text())) if favs_path.exists() else set()
        except (OSError, ValueError):
            legacy_favs = set()

        existing_texts = {q["text"] for q in self._vault_quote_dicts()}
        for q in legacy_quotes:
            text = _quote_text(q).strip()
            if not text or text in existing_texts:
                continue
            self._create_quote(text, _quote_category(q), favorite=text in legacy_favs, source="migrated")
            existing_texts.add(text)
        marker.write_text(datetime.now(timezone.utc).isoformat())

    # ── Vault-backed storage ─────────────────────────────────────────────
    def _vault_quote_dicts(self) -> list[dict]:
        """[{text, category, favorite, file}] — the normalized shape every
        route works with, regardless of the underlying vault note."""
        out = []
        for item in self.quotes.list():
            text = str(item.get("text") or "").strip()
            if not text:
                continue
            out.append({
                "text": text,
                "category": (item.get("category") or "general").strip().lower(),
                "favorite": is_truthy(item.get("favorite")),
                "file": item.get("file", ""),
            })
        return out

    def _create_quote(self, text: str, category: str = "", favorite: bool = False, source: str = "user") -> dict:
        text = text.strip()
        category = (category or "").strip().lower() or "general"
        slug = slugify(text, max_len=40, fallback="quote")
        filename = f"{slug}.md"
        n = 2
        while self.quotes.find_file(filename):
            filename = f"{slug}-{n}.md"
            n += 1
        now = datetime.now(timezone.utc).isoformat()
        fm = {
            "tags": [TAG],
            "text": text,
            "category": category,
            "favorite": "true" if favorite else "false",
            "source": source,
            "created": now,
        }
        self.vault_create_note(f"{FOLDER}/{filename}", fm, text)
        return {"file": filename, "text": text, "category": category}

    def _resolve_filename(self, raw: str) -> tuple[str, dict | None]:
        stem = raw[:-3] if raw.endswith(".md") else raw
        safe = safe_path_segment(stem)
        if not safe:
            return "", {"error": path_segment_error(stem, "quote id") or "invalid quote id"}
        return f"{safe}.md", None

    def get_quote(self, category: str | None = None) -> str:
        """Pick a quote, optionally scoped to a category.

        Added for the quotes-no-categories gap: `DEFAULT_QUOTES` used to be
        a flat list with no way to filter for "confidence" / "calm" /
        "morning energy" the way competitor apps' focus areas work. Falls
        back to the full pool when the category has no matches, so a typo'd
        or empty category never returns nothing.
        """
        quotes = self._vault_quote_dicts() or [{"text": q, "category": "general"} for q in DEFAULT_QUOTES]
        if category:
            cat = category.strip().lower()
            pool = [q for q in quotes if q.get("category") == cat] or quotes
        else:
            pool = quotes
        if not pool:
            return ""
        state = self.load_state({"last": -1})
        idx = random.choice([i for i in range(len(pool)) if i != state["last"]] or [0])
        state["last"] = idx
        self.save_state(state)
        return pool[idx]["text"]

    # ── Daily nudge — routes through the shared proactive_notify gate
    # (quiet-hours + dedup + daily-cap), same mechanism `countdown`/`vlog`
    # use. Found dark during the 2026-08 gap-analysis pass: every
    # front-tier quote app leads with a scheduled push; this was pull-only.
    # Gated on the existing "New Quote Daily" setting — a user who's
    # turned off daily rotation has said they don't want the daily beat.

    @scheduled("0 9 * * *", id="quotes-daily-nudge")
    async def _daily_nudge(self):
        if not self.setting_or_config("quotes.auto_refresh", True):
            return
        quote = self.get_quote()
        if not quote:
            return
        await self.proactive_notify(
            "quotes",
            quote,
            dedup_key=f"quotes:{date.today().isoformat()}",
            link={"text": "Open quotes", "href": "/quotes/"},
        )

    # ── Hub panel contribution ──
    async def panel_quote(self) -> dict | None:
        """Quote of the day for the hub footer."""
        raw = self.get_quote()
        if not raw:
            return None
        # Split "text — author" heuristically
        text, author = raw, ""
        for sep in (" - ", " — ", " – "):
            if sep in raw:
                parts = raw.rsplit(sep, 1)
                text, author = parts[0].strip(), parts[1].strip()
                break
        return {"text": text, "author": author}

    # ── Voice Assistant contribution ──
    async def assistant_context(self) -> str | None:
        raw = self.get_quote()
        if not raw:
            return None
        for sep in (" - ", " — ", " – "):
            if sep in raw:
                parts = raw.rsplit(sep, 1)
                text, author = parts[0].strip(), parts[1].strip()
                return f"Daily inspiration: {text} ({author})"
        return f"Daily inspiration: {raw}"

    @cli_command("quotes", help="Show a random inspirational quote")
    async def cmd_quotes(self):
        print(f"\n  {self.get_quote()}\n")

    @web_route("GET", "/api/quote")
    async def api_quote(self, request):
        category = (request.query_params.get("category") or "").strip() or None
        quote = self.get_quote(category=category)
        await self.emit("quotes:shown", {"quote": quote[:80]})
        return {"quote": quote}

    @web_route("GET", "/api/list")
    async def api_list(self, request):
        """Normalized {text, category, file} rows so the manage-collection
        UI can display/filter by category and delete by stable id (its
        own vault filename) rather than a fragile positional index."""
        return self._vault_quote_dicts()

    @web_route("GET", "/api/categories")
    async def api_categories(self, request):
        cats = sorted({q["category"] for q in self._vault_quote_dicts()})
        return {"categories": cats}

    @web_route("POST", "/api/add")
    async def api_add(self, request):
        data = await request.json()
        quote = data.get("quote", "").strip()
        if not quote:
            return {"error": "quote is required"}
        category = (data.get("category") or "").strip().lower()
        self._create_quote(quote, category)
        return {"ok": True, "total": len(self._vault_quote_dicts())}

    @web_route("POST", "/api/delete")
    async def api_delete(self, request):
        """Body: {file: "<quote-note-filename>"}. Legacy {index: N} is
        still accepted for one release (index into the current /api/list
        order) so an already-open Manage Collection modal from before this
        migration doesn't hard-fail — file-based deletion is what the
        current frontend sends."""
        data = await request.json()
        file = (data.get("file") or "").strip()
        quotes = self._vault_quote_dicts()
        if not file:
            index = data.get("index")
            if index is None or not (0 <= index < len(quotes)):
                return {"error": "file (or a valid index) is required"}
            file = quotes[index]["file"]
        filename, err = self._resolve_filename(file)
        if err:
            return err
        path = self.quotes.find_file(filename)
        if not path:
            return {"error": "quote not found"}
        path.unlink()
        rel = self.vault_rel(path)
        if rel:
            self.vault_force_index(rel)
        return {"ok": True, "total": len(self._vault_quote_dicts())}

    @web_route("POST", "/api/generate")
    async def api_generate(self, request):
        """AI-generate a quote on a topic, optionally tagged with a category."""
        data = await request.json()
        topic = data.get("topic", "life and growth")
        category = (data.get("category") or "").strip().lower()
        result = await self.think_safe(
            f"Generate one original, inspiring quote about '{topic}'. "
            f"Return ONLY the quote text with attribution '- AI'. No explanation.",
            domain="text",
            temperature=0.9,
            fallback="",
        )
        if not result:
            return {"error": "AI is offline — try again when a provider is available."}
        quote = result.strip().strip('"')
        self._create_quote(quote, category, source="ai")
        await self.emit("quotes:generated", {"quote": quote[:80], "topic": topic})
        return {"quote": quote, "total": len(self._vault_quote_dicts()), "provenance": self.last_provenance()}

    @web_route("POST", "/api/vault-sync")
    async def api_vault_sync(self, request):
        """Save quote collection to vault as ONE markdown snapshot note —
        now a convenience export/backup (each quote already lives as its
        own vault note under 30_Resources/EmptyOS/quotes/); kept for the
        one-glance "read the whole collection at once" view."""
        quotes = self._vault_quote_dicts()
        favs = [q["text"] for q in quotes if q["favorite"]]

        lines = [
            "# Quote Collection",
            "",
            f"*{len(quotes)} quotes, {len(favs)} favorites*",
            "",
        ]

        if favs:
            lines.append("## Favorites")
            lines.append("")
            for text in favs:
                lines.append(f"> {text}")
                lines.append("")

        lines.append("## All Quotes")
        lines.append("")
        for q in quotes:
            cat = q["category"]
            lines.append(f"> {q['text']}" + (f"  *({cat})*" if cat != "general" else ""))
            lines.append("")

        self.vault_write("quotes-collection.md", "\n".join(lines))
        return {"synced": len(quotes), "favorites": len(favs)}

    @web_route("GET", "/api/favorites")
    async def api_favorites(self, request):
        return [q["text"] for q in self._vault_quote_dicts() if q["favorite"]]

    @web_route("POST", "/api/favorite")
    async def api_favorite(self, request):
        data = await request.json()
        quote = data.get("quote", "").strip()
        if not quote:
            return {"error": "quote is required"}
        match = next((q for q in self._vault_quote_dicts() if q["text"] == quote), None)
        if not match:
            return {"error": "quote not found in collection"}
        filename, err = self._resolve_filename(match["file"])
        if err:
            return err
        self.quotes.update(filename, {"favorite": "true"})
        total = sum(1 for q in self._vault_quote_dicts() if q["favorite"])
        return {"ok": True, "total": max(total, 1)}
