#!/usr/bin/env bash
# Runs once when the codespace is first created.
# Installs EmptyOS, generates a minimal emptyos.toml from Codespaces secrets,
# and prepares a writable scratch vault under data/vault.

set -euo pipefail

echo ""
echo "── EmptyOS codespace setup ─────────────────────"

echo "▶ installing EmptyOS (editable)…"
pip install --quiet --upgrade pip
pip install --quiet -e .

echo "▶ creating data dirs…"
mkdir -p data/vault data/logs

# ── Pick LLM provider from Codespaces secrets ────────────────────
# Add ANTHROPIC_API_KEY (recommended — anthropic SDK is already a hard dep)
# or OPENAI_API_KEY to your Codespaces user secrets, scoped to this repo.
PROVIDER=""
PROVIDER_BLOCK=""

if [ -n "${ANTHROPIC_API_KEY:-}" ]; then
    PROVIDER="anthropic"
    PROVIDER_BLOCK='[capabilities.think.anthropic]
model = "claude-haiku-4-5-20251001"
api_key_env = "ANTHROPIC_API_KEY"
max_tokens = 4096'
    echo "▶ using Anthropic (Claude Haiku 4.5)"
elif [ -n "${OPENAI_API_KEY:-}" ]; then
    PROVIDER="openai"
    pip install --quiet openai >/dev/null 2>&1 || true
    PROVIDER_BLOCK='[capabilities.think.openai]
host = "https://api.openai.com"
model = "gpt-4o-mini"
api_key_env = "OPENAI_API_KEY"'
    echo "▶ using OpenAI (gpt-4o-mini)"
else
    PROVIDER="human"
    echo "▶ ⚠ no LLM API key found in environment."
    echo "    The UI will load and you can pick exercises, but the partner"
    echo "    won't respond until you add ANTHROPIC_API_KEY (or OPENAI_API_KEY)"
    echo "    to your Codespaces user secrets and rebuild the container."
    echo "    Settings → Codespaces → New secret → scope it to this repo."
fi

# ── Write emptyos.toml (gitignored — never committed) ────────────
echo "▶ writing emptyos.toml…"
cat > emptyos.toml <<EOF
# Auto-generated by .devcontainer/setup.sh — do not commit.
[os]
name = "Improv Codespace"
data_dir = "./data"
log_level = "INFO"

[notes]
path = "./data/vault"
watch = false

[network]
host = "0.0.0.0"
port = 9000
mode = "private"

[capabilities.think]
providers = ["${PROVIDER}"]
timeout = 60

${PROVIDER_BLOCK}
EOF

# Seed a minimal vault skeleton so vault_create_note has somewhere to write.
mkdir -p "data/vault/30_Resources/EmptyOS/improv/sessions"

echo "▶ setup complete."
echo "── codespace ready — run 'bash .devcontainer/start.sh' or wait for"
echo "   the postStart hook to boot the daemon. ───────"
echo ""
