#!/usr/bin/env python3
"""Scan user-facing code for third-party product mentions.

Reads .eos-branding for regex patterns, scans app UIs, manifests, prompts,
and error messages. Plugin code is exempt (plugins necessarily name their service).

Usage:
    python scripts/check-branding.py              # scan all tracked files
    python scripts/check-branding.py --staged     # scan only staged files (for pre-commit)
    python scripts/check-branding.py --root DIR   # scan every file under DIR (release snapshot)
"""

import re
import sys
from pathlib import Path

from check_base import (
    REPO_ROOT,
    arg_value,
    files_under,
    git_staged,
    git_tracked,
    git_untracked,
)
from check_common import load_by_path

# Loaded by path, not as `emptyos.sdk.release_filter`: the package initialiser
# pulls in the daemon runtime, which a bare CI checkout does not have. That
# module keeps its own scope stdlib-only for this reason.
_is_never_published = load_by_path(
    "release_filter_paths_branding", "emptyos/sdk/release_filter.py"
).is_never_published

PATTERNS_FILE = ".eos-branding"

# Directories/files exempt from branding checks (they integrate with specific services)
EXEMPT_PREFIXES = (
    "plugins/",
    ".eos-branding",
    "scripts/check-branding.py",
    "scripts/",  # migration/utility scripts
    "CLAUDE.md",  # development rules reference product names for documentation
    "DESIGN.md",  # design tokens contract — references brands when stating "don't" rules
    "docs/",  # design docs may reference integrations
    ".claude/",  # claude code config
    ".agent-bus/",  # canonical mirror of .claude/ + boot files for the Agent Context Bus
    ".agents/",  # non-Claude agent mirror of .claude/ (skills/rules), generated by the bus
    "skills/",  # skill definitions
    "data/",  # runtime data
    "tests/",  # test fixtures
    "results/",  # benchmark/test results
    ".gitignore",  # folder names like .obsidian
    "emptyos.example.toml",
    "release.toml",  # build manifest — plugin IDs are functional identifiers
    # Provider-selector code: model-id prefix detection (gpt-*, chatgpt-*) is
    # functional routing, not user-facing branding (.eos-branding: "OK in
    # provider selectors"). Narrow file exemption — the rest of model-bench
    # (UI text, prompts) stays checked.
    "apps/extension/dev/model-bench/agent_bench.py",
    # Capability providers are the kernel-layer twin of plugins/: a provider
    # necessarily names the service it wraps, and CLAUDE.md rule 14's exception
    # ("plugin code that integrates with a specific service may reference it")
    # applies for the same reason. codex_cli.py's module docstring states which
    # subscription the CLI authenticates against — a developer-facing technical
    # fact, not user-facing branding, and rewording it would lose the precision
    # that makes the docstring useful. Narrow file exemption rather than the whole
    # providers/ directory, so a brand name in a provider's *error message* (which
    # does reach the user) still gets caught.
    "emptyos/capabilities/providers/codex_cli.py",
)

# Binary extensions to skip
BINARY_EXT = {
    ".png",
    ".jpg",
    ".jpeg",
    ".gif",
    ".ico",
    ".wav",
    ".mp3",
    ".mp4",
    ".woff",
    ".woff2",
    ".ttf",
    ".eot",
    ".db",
    ".sqlite",
    ".pyc",
}

# Files where product names are functional identifiers (provider selectors, CSS classes)
FUNCTIONAL_FILES = {
    "apps/assistant/pages/index.html",  # backend selector uses provider names
    "emptyos/web/static/topology.html",  # service registry uses service names
    "apps/extension/dev/model-bench/agent_bench.py",  # model-id prefix selector (gpt-/o1/chatgpt-)
}

# Line-level patterns that are NOT branding violations (technical identifiers)
FALSE_POSITIVE_RE = [
    re.compile(r"\.obsidian"),  # .obsidian folder name
    re.compile(r"obsidian://"),  # URI scheme (technical protocol)
    re.compile(
        r"Obsidian(Search|CLI|Provider|Plugin)"
    ),  # code identifiers (CLI plugin, search provider)
    re.compile(r"obsidian-cli"),  # plugin ID
    re.compile(r"obs-link|obs-icon"),  # CSS class names
    re.compile(r'"vault-obsidian-format"'),  # skill ID
    re.compile(r'"suno[_-]'),  # legacy field alias (backwards compat)
]


def load_patterns(path: str) -> list[re.Pattern]:
    p = Path(path)
    if not p.exists():
        print(f"Warning: {path} not found, no patterns to check")
        return []
    patterns = []
    for line in p.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        try:
            patterns.append(re.compile(line))
        except re.error as e:
            print(f"Warning: invalid pattern '{line}': {e}")
    return patterns


def get_files(
    staged_only: bool = False,
    include_untracked: bool = False,
    root: Path | None = None,
) -> list[str]:
    if root is not None:
        # The release snapshot: every file under it, not this repo's index
        # (see check_base.files_under).
        return files_under(root)
    paths = git_staged() if staged_only else git_tracked()
    if include_untracked:
        paths = paths + git_untracked()
    return [p.relative_to(REPO_ROOT).as_posix() for p in paths]


def is_exempt(filepath: str) -> bool:
    normalized = filepath.replace("\\", "/")
    if any(normalized.startswith(prefix) for prefix in EXEMPT_PREFIXES):
        return True
    # Subtrees git-tracked in the private repo but pruned from every public
    # snapshot (see emptyos/sdk/release_filter.py, where the list sits beside
    # the prune that enforces it and the assertion that proves it). Rule 14 is
    # about what a *shipped* UI says; a personal app that integrates with a
    # named service is the same case as `plugins/` above.
    return _is_never_published(normalized)


def is_false_positive(line: str) -> bool:
    return any(fp.search(line) for fp in FALSE_POSITIVE_RE)


def main():
    staged_only = "--staged" in sys.argv
    # Untracked files are invisible to both scopes above — see the note on
    # check_base.git_untracked. Opt-in, so default behaviour is unchanged.
    include_untracked = "--include-untracked" in sys.argv and not staged_only
    root_arg = arg_value("--root")
    root = Path(root_arg).resolve() if root_arg else None
    if root is not None and not root.is_dir():
        print(f"ERROR: --root {root_arg} is not a directory", file=sys.stderr)
        sys.exit(2)
    base = root or REPO_ROOT
    patterns = load_patterns(str(base / PATTERNS_FILE))
    if not patterns:
        if root is not None:
            # A snapshot scanned with no patterns reports clean for the wrong
            # reason — the same refusal check-personal makes for `--patterns`.
            print(f"ERROR: no branding patterns under {root} — refusing to report clean.",
                  file=sys.stderr)
            sys.exit(2)
        sys.exit(0)

    files = get_files(staged_only, include_untracked, root)
    violations = []

    for filepath in files:
        if is_exempt(filepath):
            continue
        if Path(filepath).suffix.lower() in BINARY_EXT:
            continue
        normalized = filepath.replace("\\", "/")
        if normalized in FUNCTIONAL_FILES:
            continue

        try:
            content = (base / filepath).read_text(encoding="utf-8", errors="ignore")
        except (OSError, UnicodeDecodeError):
            continue

        for lineno, line in enumerate(content.splitlines(), 1):
            stripped = line.strip()
            # Skip comments in Python files
            if filepath.endswith(".py") and stripped.startswith("#"):
                continue
            # Skip Python docstrings (triple-quoted) — internal documentation
            if stripped.startswith(('"""', "'''")):
                continue
            # Skip import/class/def lines (code identifiers, not user-facing)
            if stripped.startswith(("import ", "from ", "class ", "def ")):
                continue
            # Skip CSS comments
            if stripped.startswith("/*") or stripped.startswith("*"):
                continue
            # Skip JS comments
            if stripped.startswith("//"):
                continue

            for pattern in patterns:
                if pattern.search(line):
                    # Check false positives (folder names, URI schemes, code identifiers)
                    if is_false_positive(line):
                        continue
                    violations.append((filepath, lineno, pattern.pattern, stripped[:120]))

    if violations:
        print(f"\n{'=' * 60}", file=sys.stderr)
        print(f"  THIRD-PARTY BRANDING in {len(violations)} location(s)", file=sys.stderr)
        print(f"{'=' * 60}\n", file=sys.stderr)
        for filepath, lineno, pattern, preview in violations:
            # Sanitize for console output
            safe = preview.encode("ascii", "replace").decode("ascii")
            print(f"  {filepath}:{lineno}", file=sys.stderr)
            print(f"    Pattern: {pattern}", file=sys.stderr)
            print(f"    Content: {safe}", file=sys.stderr)
            print(file=sys.stderr)
        print("Use generic terms instead. See .eos-branding for details.", file=sys.stderr)
        print("Exempt: plugin code, docs, CLAUDE.md, provider selectors\n", file=sys.stderr)
        sys.exit(1)
    else:
        if staged_only:
            mode = "staged files"
        elif include_untracked:
            mode = "all tracked + untracked files"
        else:
            mode = "all tracked files"
        print(
            f"OK: No third-party branding found in {mode} ({len(files)} files, {len(patterns)} patterns)"
        )
        sys.exit(0)


if __name__ == "__main__":
    main()
