#!/usr/bin/env python3
"""Scan committed files for personal data patterns.

Reads .eos-personal for regex patterns, scans all git-tracked files,
and reports matches. Exit code 0 = clean, 1 = personal data found.

Usage:
    python scripts/check-personal.py              # scan all tracked files
    python scripts/check-personal.py --staged     # scan only staged files (for pre-commit)
    python scripts/check-personal.py --install-hook   # write .git/hooks/pre-commit
"""

import subprocess
import sys
from pathlib import Path

# Make `emptyos.sdk` importable when the script is run from the repo root,
# even before `pip install -e .`. Pre-commit hooks and the release snapshot
# scanner both invoke this script from a checkout that has `emptyos/` on
# disk but may not have it installed in the active venv.
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from emptyos.sdk.personal_patterns import load as _load_personal_patterns

PATTERNS_FILE = ".eos-personal"
# Files that are allowed to contain personal patterns
ALLOWLIST = {
    ".eos-personal",  # the patterns file itself
    "scripts/check-personal.py",  # this script
    "data/personal-defaults.json",
    ".claude/settings.local.json",  # machine-specific auto-approve rules
}
# Binary extensions to skip
BINARY_EXT = {
    ".png",
    ".jpg",
    ".jpeg",
    ".gif",
    ".ico",
    ".wav",
    ".mp3",
    ".mp4",
    ".woff",
    ".woff2",
    ".ttf",
    ".eot",
    ".db",
    ".sqlite",
    ".pyc",
}


def load_patterns(path: str):
    if not Path(path).exists():
        print(f"Warning: {path} not found, no patterns to check")
        return []
    return _load_personal_patterns(
        path,
        on_error=lambda line, err: print(f"Warning: invalid pattern '{line}': {err}"),
    )


def get_files(staged_only: bool = False) -> list[str]:
    if staged_only:
        cmd = ["git", "diff", "--cached", "--name-only", "--diff-filter=ACM"]
    else:
        cmd = ["git", "ls-files"]
    result = subprocess.run(cmd, capture_output=True, text=True)
    return [f for f in result.stdout.strip().split("\n") if f]


HOOK_BODY = """#!/bin/sh
# Auto-generated by `python scripts/check-personal.py --install-hook`.
# Blocks commits that introduce patterns banned by .eos-personal.
exec python scripts/check-personal.py --staged
"""


def install_hook() -> int:
    repo_root = subprocess.run(
        ["git", "rev-parse", "--show-toplevel"],
        capture_output=True, text=True,
    ).stdout.strip()
    if not repo_root:
        print("Not inside a git repository.")
        return 1
    hook = Path(repo_root) / ".git" / "hooks" / "pre-commit"
    if hook.exists():
        existing = hook.read_text(encoding="utf-8", errors="ignore")
        if "check-personal.py" in existing:
            print(f"OK: pre-commit hook already invokes check-personal.py ({hook})")
            return 0
        backup = hook.with_suffix(".pre-eos.bak")
        hook.rename(backup)
        print(f"NOTE: existing hook moved to {backup}")
    hook.write_text(HOOK_BODY, encoding="utf-8")
    try:
        hook.chmod(0o755)
    except OSError:
        pass
    print(f"OK: installed pre-commit hook at {hook}")
    return 0


def main():
    if "--install-hook" in sys.argv:
        sys.exit(install_hook())
    staged_only = "--staged" in sys.argv
    patterns = load_patterns(PATTERNS_FILE)
    if not patterns:
        sys.exit(0)

    files = get_files(staged_only)
    violations = []

    for filepath in files:
        if filepath in ALLOWLIST:
            continue
        if Path(filepath).suffix.lower() in BINARY_EXT:
            continue
        try:
            content = Path(filepath).read_text(encoding="utf-8", errors="ignore")
        except (OSError, UnicodeDecodeError):
            continue

        for lineno, line in enumerate(content.splitlines(), 1):
            for pattern in patterns:
                if pattern.search(line):
                    violations.append((filepath, lineno, pattern.pattern, line.strip()[:120]))

    if violations:
        print(f"\n{'=' * 60}")
        print(f"  PERSONAL DATA DETECTED in {len(violations)} location(s)")
        print(f"{'=' * 60}\n")
        for filepath, lineno, pattern, preview in violations:
            print(f"  {filepath}:{lineno}")
            print(f"    Pattern: {pattern}")
            print(f"    Content: {preview}")
            print()
        print(f"Fix these before committing. Patterns defined in {PATTERNS_FILE}")
        print("Move personal values to data/personal-defaults.json (git-ignored)\n")
        sys.exit(1)
    else:
        mode = "staged files" if staged_only else "all tracked files"
        print(
            f"OK: No personal data found in {mode} ({len(files)} files, {len(patterns)} patterns)"
        )
        sys.exit(0)


if __name__ == "__main__":
    main()
