#!/usr/bin/env python3
"""Boot-smoke a source tree: compile every module, then actually boot the daemon.

The release pipeline's static scans (check-personal, check-branding, tier
filters, doc gates) all read files — none of them ever *runs* the code. That
gap cost four consecutive releases (v0.2.7 → v0.2.10): a locally-edited module
compiled fine inside the already-running daemon (its modules were cached), but
the fresh public snapshot failed to import on the VPS. Each release shipped,
failed to boot, got patched, and re-shipped.

This check closes that class by doing what the VPS does — boot the tree:

  1. Compile every ``.py`` in the tree (syntax errors, fast, ~5-10s).
  2. Spawn ``python -m emptyos start`` against the tree on a throwaway port,
     with an isolated data dir + vault, and poll ``/api/health``.
  3. Fail if the daemon never answers, **or** if it answers with apps in the
     ``error`` state — app load failures are fail-soft (the daemon still binds),
     so "it booted" is not the same as "it booted clean".

Step 2 is the load-bearing one: only a real boot catches an undefined import,
a bad relative import under the ``eos_apps.<id>`` namespace, or a public app
that silently depends on a plugin the tier filter dropped.

Usage:
    python scripts/check_snapshot_boot.py                    # boot the working tree
    python scripts/check_snapshot_boot.py /path/to/snapshot  # boot a pruned snapshot
    python scripts/check_snapshot_boot.py --timeout 120
    python scripts/check_snapshot_boot.py --keep-scratch     # keep logs + config

Exit codes:
    0  tree compiled and booted clean
    1  compile error, boot failure, or apps in error state
    2  cannot run (tree missing / not a source tree)

Safety: the daemon this spawns is a child process **this script owns**, on an
ephemeral port, with its data dir and vault in a scratch temp dir. It never
touches the user's :9000 / :9001 daemons and never terminates a PID it did not
spawn — see `.claude/rules/daemon-handling.md`.
"""

from __future__ import annotations

import argparse
import os
import re
import shutil
import socket
import subprocess
import sys
import tempfile
import time
from pathlib import Path

# Windows consoles default to cp1252, which can't encode the arrows / marks
# below. Match release-public.py and force utf-8.
if hasattr(sys.stdout, "reconfigure"):
    # line_buffering so the step log interleaves correctly with the child's
    # stderr when this runs under a pipe (release-public.py, CI).
    sys.stdout.reconfigure(encoding="utf-8", line_buffering=True)
    sys.stderr.reconfigure(encoding="utf-8")

ROOT = Path(__file__).resolve().parent.parent

EXIT_OK = 0
EXIT_FAIL = 1
EXIT_CANNOT_RUN = 2

# Never smoke-boot onto a port a real daemon may hold: :9000 main, :9001
# dogfood sidecar, :9002+ sandbox-pool members.
RESERVED_PORTS = frozenset(range(9000, 9010))

# Directories that never contain shippable source. Used by the snapshot walk;
# in a working tree `git ls-files` already excludes them. `results/` holds
# LLM conv-test output whose fixtures are deliberately un-compilable.
SKIP_DIRS = frozenset(
    {
        "data",
        "dist",
        "build",
        "results",
        "node_modules",
        "venv",
        "__pycache__",
    }
)

# Mirrors plugins/sandbox-pool SANDBOX_CONFIG_TEMPLATE. The five plugin
# disables are load-bearing: without them the smoke daemon spawns its own
# pool / sidecar (port fights) and duplicate tray icons + hotkey grabs.
SMOKE_CONFIG_TEMPLATE = """\
# Auto-generated by scripts/check_snapshot_boot.py — throwaway boot smoke.
# Everything stateful points at a scratch dir OUTSIDE the tree under test,
# so booting can never write into a snapshot that is about to be shipped.

[os]
data_dir = "{data_dir}"

[apps]
path = "{apps_path}"

[plugins]
path = "{plugins_path}"

[engines]
path = "{engines_path}"

[notes]
path = "{notes_path}"

[network]
mode = "local"
port = {port}
host = "127.0.0.1"

# The smoke daemon must NOT spawn its own sandbox pool. Recursion guard.
[plugins.sandbox-pool]
enabled = false

# ...nor the dogfood :9001 sidecar — nested daemons fight for the port.
[plugins.dogfood-demo]
enabled = false

# OS-level user-facing surfaces have no place in a headless throwaway daemon:
# duplicate tray icons, a fought-over global hotkey, an extra launcher window.
[plugins.system-tray]
enabled = false

[plugins.global-hotkey]
enabled = false

[plugins.command-launcher]
enabled = false

# We are testing that the tree boots, not that it can think.
[capabilities.think]
providers = ["human"]
"""


def step(label: str) -> None:
    print(f"\n  → {label}")


def fail(msg: str) -> int:
    print(f"\n  ✗ {msg}\n", file=sys.stderr)
    return EXIT_FAIL


# ── Tier (a): compile every module ──────────────────────────────────────────


def _skipped(rel: Path) -> bool:
    # Dot-dirs cover .git/.venv/.pytest_cache/.tmp-pytest-* — the last of which
    # holds fixtures with *intentionally* broken syntax.
    return any(
        part in SKIP_DIRS or part.startswith(".") or part.startswith("sandbox-")
        for part in rel.parts[:-1]
    )


def iter_py_files(tree: Path):
    """Yield the .py files that would actually ship.

    In a working tree, ask git — untracked scratch (``results/`` conv-test
    output, ``.tmp-pytest-*`` fixtures) is deliberately un-compilable and must
    not redden the gate. In a snapshot there is no ``.git``, so walk and filter;
    the snapshot has already been cruft-swept by then. Same working-tree-vs-
    snapshot split as ``check_no_private_apps`` in release-public.py.
    """
    if (tree / ".git").exists():
        try:
            out = subprocess.run(
                ["git", "ls-files", "-z", "--", "*.py"],
                cwd=str(tree),
                capture_output=True,
                text=True,
                timeout=60,
                check=True,
            ).stdout
        except (OSError, subprocess.SubprocessError):
            out = None
        if out is not None:
            for name in out.split("\0"):
                if not name:
                    continue
                rel = Path(name)
                if _skipped(rel):
                    continue
                path = tree / rel
                if path.is_file():
                    yield path
            return

    for path in tree.rglob("*.py"):
        if not _skipped(path.relative_to(tree)):
            yield path


def verify_package_resolution(tree: Path) -> str | None:
    """Prove ``import emptyos`` inside the tree resolves to *the tree's* package.

    Load-bearing anti-false-pass guard. EmptyOS is normally pip-installed
    (editable) from the working tree, so a tree that lacks its own ``emptyos/``
    package silently falls back to the installed one — the smoke would then boot
    the working-tree code and report the *snapshot* healthy. A snapshot missing
    its kernel would sail straight through the gate it exists to fail.

    Returns an error string, or None when the tree's own package wins.
    """
    probe = "import emptyos, sys; sys.stdout.write(emptyos.__file__ or '')"
    try:
        result = subprocess.run(
            # -B: importing emptyos would otherwise leave
            # `emptyos/__pycache__/__init__.pyc` inside the snapshot, and the
            # cruft sweep has already run — the bytecode would ship.
            [sys.executable, "-B", "-c", probe],
            cwd=str(tree),
            capture_output=True,
            text=True,
            timeout=60,
            check=False,
        )
    except (OSError, subprocess.TimeoutExpired) as e:
        return f"could not probe package resolution: {e}"
    if result.returncode != 0:
        return f"`import emptyos` failed inside the tree:\n{(result.stderr or '').strip()}"
    resolved = Path((result.stdout or "").strip())
    if not resolved.name:
        return "`import emptyos` yielded no __file__"
    try:
        resolved.resolve().relative_to(tree.resolve())
    except ValueError:
        return (
            f"`import emptyos` resolved to {resolved} — OUTSIDE the tree under test.\n"
            "    The tree has no emptyos/ package of its own, so the boot would "
            "silently test\n    the installed copy instead. This is not an EmptyOS source tree."
        )
    return None


def compile_tree(tree: Path) -> list[str]:
    """Compile every module in-process. Returns a list of error strings.

    Deliberately not ``python -m compileall``: that writes ``__pycache__``
    into the tree, and the release script's cruft sweep has already run by
    the time this gate fires — the bytecode would ship. ``compile()`` writes
    nothing and gives an exact file:line.
    """
    import warnings

    errors: list[str] = []
    count = 0
    for path in iter_py_files(tree):
        count += 1
        try:
            source = path.read_text(encoding="utf-8")
        except UnicodeDecodeError as e:
            errors.append(f"{path.relative_to(tree)}: not valid utf-8 ({e})")
            continue
        try:
            with warnings.catch_warnings():
                # A module can compile cleanly while emitting SyntaxWarning
                # (e.g. `\ ` inside an ASCII-art docstring). Not our concern.
                warnings.simplefilter("ignore", SyntaxWarning)
                compile(source, str(path), "exec")
        except SyntaxError as e:
            errors.append(f"{path.relative_to(tree)}:{e.lineno}: {e.msg}")
    print(f"    compiled {count} modules")
    return errors


# ── Advisory: declared deps actually resolve ────────────────────────────────

_DEP_NAME_RE = re.compile(r"^[A-Za-z0-9._-]+")


def check_declared_deps(tree: Path) -> list[str]:
    """Warn when a dependency declared in pyproject.toml isn't importable.

    Advisory only. The smoke boot runs against the *parent* interpreter's
    site-packages, so a dep that is installed locally but missing from
    pyproject would still boot here and still fail the VPS Docker build
    (which installs from pyproject). This catches the inverse — declared but
    absent — and partially covers that blind spot.
    """
    import tomllib
    from importlib.metadata import PackageNotFoundError, distribution

    pyproject = tree / "pyproject.toml"
    if not pyproject.exists():
        return []
    try:
        with open(pyproject, "rb") as f:
            data = tomllib.load(f)
    except Exception as e:
        return [f"pyproject.toml unparseable: {e}"]

    missing: list[str] = []
    for raw in data.get("project", {}).get("dependencies", []) or []:
        m = _DEP_NAME_RE.match(str(raw).strip())
        if not m:
            continue
        name = m.group(0)
        try:
            distribution(name)
        except PackageNotFoundError:
            missing.append(name)
        except Exception:
            pass
    return missing


# ── Tier (c): boot the tree ─────────────────────────────────────────────────


def port_in_use(port: int) -> bool:
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        s.settimeout(0.5)
        return s.connect_ex(("127.0.0.1", port)) == 0


def pick_free_port() -> int:
    """Bind :0 and read back the ephemeral port the OS handed us."""
    for _ in range(10):
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
            s.bind(("127.0.0.1", 0))
            port = s.getsockname()[1]
        if port not in RESERVED_PORTS:
            return port
    raise RuntimeError("could not find a free non-reserved port")


def write_smoke_config(scratch: Path, tree: Path, port: int) -> Path:
    data_dir = scratch / "data"
    vault = scratch / "vault"
    data_dir.mkdir(parents=True, exist_ok=True)
    vault.mkdir(parents=True, exist_ok=True)
    # VaultIndex warns loudly on an empty vault; seed it like sandbox-pool does.
    (vault / "README.md").write_text(
        "# Boot smoke vault\n\nThrowaway. Created by scripts/check_snapshot_boot.py.\n",
        encoding="utf-8",
    )

    def p(path: Path) -> str:
        return str(path.resolve()).replace("\\", "/")

    cfg = scratch / "emptyos.toml"
    cfg.write_text(
        SMOKE_CONFIG_TEMPLATE.format(
            data_dir=p(data_dir),
            apps_path=p(tree / "apps"),
            plugins_path=p(tree / "plugins"),
            engines_path=p(tree / "engines"),
            notes_path=p(vault),
            port=port,
        ),
        encoding="utf-8",
    )
    return cfg


def _read_lines(path: Path) -> list[str] | None:
    try:
        return path.read_text(encoding="utf-8", errors="replace").splitlines()
    except OSError:
        return None


def tail(path: Path, n: int = 40) -> str:
    lines = _read_lines(path)
    if lines is None:
        return "      (no output captured)"
    if not lines:
        return "      (empty)"
    return "\n".join(f"      {line}" for line in lines[-n:])


def grep_tail(path: Path, needle: str, n: int = 15) -> str:
    """Last `n` lines containing `needle` — the signal, not the whole boot log."""
    lines = _read_lines(path)
    if not lines:
        return tail(path, n)
    hits = [line for line in lines if needle in line]
    if not hits:
        return tail(path, n)
    return "\n".join(f"      {line}" for line in hits[-n:])


def dump_logs(out_log: Path, err_log: Path, *, stdout_needle: str | None = None) -> None:
    """Print the child's output — the whole diagnostic payload on any failure.

    stdout comes first because app_loader logs load failures through syslog's
    console sink, which is stdout; stderr only carries an outright crash.
    """
    print("\n    ── stdout (tail) ──")
    print(grep_tail(out_log, stdout_needle) if stdout_needle else tail(out_log, n=20))
    print("    ── stderr (tail) ──")
    print(tail(err_log, n=20))


def kill_child(proc: subprocess.Popen, port: int) -> None:
    """Terminate the daemon we spawned, then wait for the port to free.

    Reuses `emptyos.sdk.daemon_supervisor.terminate_daemon` (terminate → kill
    → port-free poll). The port-free wait matters on Windows: the child holds
    SQLite handles under scratch, and rmtree races an unreaped process.
    """
    if proc.poll() is not None:
        return
    import asyncio

    from emptyos.sdk.daemon_supervisor import terminate_daemon

    async def _probe() -> bool:
        return port_in_use(port)

    try:
        asyncio.run(terminate_daemon(proc, probe=_probe))
    except Exception:
        pass
    # Escalate only against the PID tree we own, and only if it survived.
    if proc.poll() is None and os.name == "nt":
        subprocess.run(
            ["taskkill", "/F", "/T", "/PID", str(proc.pid)],
            capture_output=True,
            check=False,
        )
        try:
            proc.wait(timeout=5)
        except Exception:
            pass


def rmtree_scratch(path: Path) -> None:
    """Remove the scratch dir, tolerating Windows read-only files.

    Falls back to a plain rmtree: `emptyos.sdk` pulls heavy runtime deps and
    this script must stay usable in a bare checkout.
    """
    try:
        from emptyos.sdk.release_filter import rmtree_forgiving

        rmtree_forgiving(path)
    except Exception:
        shutil.rmtree(path, ignore_errors=True)


def boot_and_probe(tree: Path, scratch: Path, timeout: int) -> int:
    from emptyos.sdk.daemon_launcher import fetch_health, poll_health
    from emptyos.sdk.daemon_supervisor import spawn_emptyos_daemon

    port = pick_free_port()
    cfg = write_smoke_config(scratch, tree, port)
    out_log = scratch / "daemon.log"
    err_log = scratch / "daemon.err.log"

    print(f"    booting {tree} on :{port} (timeout {timeout}s)")
    started = time.monotonic()
    with open(out_log, "wb") as out, open(err_log, "wb") as err:
        proc = spawn_emptyos_daemon(
            config_path=cfg,
            cwd=tree,
            # PYTHONDONTWRITEBYTECODE: without it the boot sprays __pycache__
            # through the snapshot, which commit_and_push would then ship —
            # the cruft sweep runs long before this gate.
            # EOS_SANDBOX_POOL_MEMBER: belt-and-braces recursion guard on top
            # of the config-level plugin disables.
            extra_env={"PYTHONDONTWRITEBYTECODE": "1", "EOS_SANDBOX_POOL_MEMBER": "1"},
            stdout=out,
            stderr=err,
        )
        try:
            base = f"http://127.0.0.1:{port}"
            # "Ready" here means apps mounted, not merely a 200 — a tree whose
            # apps/ never resolved answers {"status": "starting", "apps": 0}.
            result = poll_health(
                base,
                proc=proc,
                timeout=timeout,
                interval=1.0,
                ready=lambda b: b.get("status") == "ok",
            )
            if not result.ok:
                if result.reason == "proc_died":
                    print(f"\n    daemon exited with code {proc.returncode} before answering")
                elif result.payload:
                    # Answered but never mounted apps — usually apps/ not resolving.
                    print(f"    last /api/health payload: {result.payload}")
                dump_logs(out_log, err_log)
                return fail(
                    f"{tree.name} failed to boot — the snapshot would not start on the VPS."
                    if result.reason == "proc_died"
                    else f"daemon did not become healthy within {timeout}s"
                )

            health = result.payload or {}
            elapsed = time.monotonic() - started
            print(f"    OK: daemon healthy in {elapsed:.1f}s ({health.get('apps')} apps)")

            # "It booted" != "it booted clean". App load failures are fail-soft
            # (kernel logs them and moves on), so the daemon binds with a broken
            # app. That's precisely the v0.2.x failure class — check for it.
            # ?full=true walks the capability chain and probes external provider
            # hosts (ollama/comfyui/voice-api) that aren't up here — each burns
            # its connect timeout, so give the call a generous client timeout.
            full = fetch_health(base, query="full=true", timeout=60.0)
            # An unreadable signal is NOT a pass. Reporting "clean" because the
            # diagnostics call timed out is how a gate silently stops gating.
            if not isinstance(full, dict):
                dump_logs(out_log, err_log)
                return fail(
                    "daemon is up but /api/health?full=true was unreadable — "
                    "cannot verify app load state, refusing to pass"
                )
            apps = full.get("apps")
            if not isinstance(apps, dict) or "errors" not in apps:
                return fail(
                    f"/api/health?full=true returned an unexpected shape "
                    f"(apps={apps!r}) — cannot verify app load state"
                )
            errors = apps.get("errors")
            if errors:
                print("\n    Apps that failed to load:")
                for app_id in errors:
                    print(f"      - {app_id}")
                dump_logs(out_log, err_log, stdout_needle="failed for")
                return fail(
                    f"{len(errors)} app(s) failed to load in the fresh tree "
                    "(fail-soft at runtime, but broken on arrival)"
                )

            svc_errors = [
                s.get("name")
                for s in (full.get("services") or [])
                if isinstance(s, dict) and s.get("status") == "error"
            ]
            if svc_errors:
                # Services legitimately degrade when an external host is absent
                # (ollama, comfyui, voice-api). Never a release blocker.
                print(f"    NOTE: services unavailable in smoke env: {', '.join(svc_errors)}")

            by_state = apps.get("by_state") or {}
            summary = ", ".join(f"{v} {k}" for k, v in sorted(by_state.items()))
            print(f"    OK: no app load errors ({summary or 'no state reported'})")
            return EXIT_OK
        finally:
            kill_child(proc, port)


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Compile + boot a source tree to prove it starts from scratch."
    )
    parser.add_argument(
        "tree",
        nargs="?",
        default=str(ROOT),
        help="Source tree to smoke (default: this repo). Usually a release snapshot.",
    )
    parser.add_argument("--timeout", type=int, default=90, help="Boot timeout in seconds")
    parser.add_argument(
        "--keep-scratch",
        action="store_true",
        help="Keep the scratch dir (config + daemon logs) for debugging",
    )
    args = parser.parse_args()

    tree = Path(args.tree).resolve()
    if not tree.is_dir():
        print(f"  ✗ not a directory: {tree}", file=sys.stderr)
        return EXIT_CANNOT_RUN

    print(f"\n  Boot smoke: {tree}")

    if not (tree / "emptyos" / "__init__.py").exists():
        print(
            f"  ✗ {tree} has no emptyos/ package — not an EmptyOS source tree",
            file=sys.stderr,
        )
        return EXIT_CANNOT_RUN

    step("Compile every module in the tree")
    errors = compile_tree(tree)
    if errors:
        print()
        for e in errors[:15]:
            print(f"      {e}")
        if len(errors) > 15:
            print(f"      ... and {len(errors) - 15} more")
        return fail(f"{len(errors)} module(s) failed to compile")
    print("    OK: no syntax errors")

    step("Verify `import emptyos` resolves to the tree under test")
    err = verify_package_resolution(tree)
    if err:
        return fail(err)
    print("    OK: the tree's own emptyos/ package wins over any installed copy")

    step("Check declared dependencies resolve (advisory)")
    missing = check_declared_deps(tree)
    if missing:
        print(f"    WARNING: declared in pyproject.toml but not installed: {', '.join(missing)}")
        print("    The VPS Docker build installs from pyproject — verify these exist.")
    else:
        print("    OK: all declared dependencies importable")

    step("Boot the tree as a throwaway daemon and probe /api/health")
    scratch = Path(tempfile.mkdtemp(prefix="eos-boot-smoke-"))
    try:
        return boot_and_probe(tree, scratch, args.timeout)
    finally:
        if args.keep_scratch:
            print(f"\n    scratch kept at: {scratch}")
        else:
            rmtree_scratch(scratch)


if __name__ == "__main__":
    rc = main()
    if rc == EXIT_OK:
        print("\n  ✓ Tree compiles and boots clean\n")
    sys.exit(rc)
