"""Download real CC0 PBR textures from ambientCG, replacing the placeholder
baseColor.jpg files generated by `scripts/generate_placeholder_textures.py`.

For each material in `_ASSETS`, fetches the 1K JPEG bundle from ambientCG,
extracts Color + NormalGL + Roughness maps, and saves them under
`engines/articulated/textures/<name>/`:

    baseColor.jpg     # carries the colour (placeholder generator wrote here too)
    normal.jpg        # NormalGL (OpenGL convention) — surface bumpiness
    roughness.jpg     # per-pixel roughness variation

After download, the robot-modeller's gltf exporter embeds all three maps into the
output.glb so the three.js viewer and Blender renderer both see them.

Asset IDs were curated against ambientCG's category pages (Mar 2026 — IDs
are stable IF still present on ambientCG; the script gracefully skips any
that 404). Run from repo root:

    python scripts/download_textures.py

Idempotent: skips materials where baseColor + normal + roughness already
exist on disk. Pass `--force` to re-download.

License: ambientCG textures are CC0 1.0. https://ambientcg.com/license
"""

from __future__ import annotations

import io
import shutil
import sys
import urllib.request
import zipfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from engines.articulated.materials import textures_root  # noqa: E402


# Curated asset IDs — each maps a library preset name to an ambientCG asset.
# Verified against ambientCG categories Mar 2026. Replace any individual ID
# without breaking the rest. The ambientCG license is CC0 (see module doc).
_ASSETS: dict[str, str] = {
    "oak":           "Wood049",      # warm mid-brown wood, visible grain
    "walnut":        "Wood051",      # dark espresso wood
    "pine":          "Wood048",      # pale, plain, smooth (works as pine-ish)
    "linen":         "Fabric036",    # clean smooth woven, off-white
    "cotton":        "Fabric036",    # same as linen — both are smooth woven (no distinct cotton asset)
    "wool":          "Fabric019",    # tagged wool, woven
    "leather":       "Leather037",   # brown clean dark
    "brushed-steel": "Metal009",     # brushed silver steel
    "brass":         "Metal034",     # gold smooth yellow
    "copper":        "Metal035",     # copper orange smooth
    "matte-paint":   "Plastic010",   # white smooth (paint category is all cracked/shiny — substitute)
    "glossy-paint":  "Paint005",     # genuinely glossy paint
    "marble":        "Marble020",    # beige reflective marble
    "concrete":      "Concrete020",  # generic grey concrete
    "matte-plastic": "Plastic011",   # grey smooth plastic
}


# Inside each ZIP, look for files matching these patterns (case-sensitive).
# Returns (substring_match_for_zip_entry, save_as_filename) pairs.
_MAP_PATTERNS = [
    ("_Color.jpg",     "baseColor.jpg"),
    ("_NormalGL.jpg",  "normal.jpg"),
    ("_Roughness.jpg", "roughness.jpg"),
]


def download_asset(name: str, asset_id: str, out_dir: Path, *, force: bool = False) -> dict:
    """Download one asset's 1K-JPG bundle, extract the 3 maps. Idempotent.

    Returns a dict with `name`, `asset_id`, `status` (`written`, `kept`,
    `missing_id`, `download_failed`, `partial`), `maps` (the maps actually
    saved this call). Never raises.
    """
    targets = {fname: out_dir / fname for _, fname in _MAP_PATTERNS}
    if not force and all(p.exists() and p.stat().st_size > 100 for p in targets.values()):
        return {"name": name, "asset_id": asset_id, "status": "kept", "maps": []}

    url = f"https://ambientcg.com/get?file={asset_id}_1K-JPG.zip"
    # ambientCG's CDN rejects bare urllib (default User-Agent gets a 403);
    # send a generic browser-style UA. CC0 license; no scraping concerns.
    req = urllib.request.Request(url, headers={
        "User-Agent": "Mozilla/5.0 (robot-modeller-texture-fetcher; CC0 textures)",
    })
    try:
        with urllib.request.urlopen(req, timeout=60) as r:
            zip_bytes = r.read()
            if len(zip_bytes) < 1024:
                # Tiny response usually means a 404 HTML page slipped through.
                return {"name": name, "asset_id": asset_id, "status": "missing_id", "maps": []}
    except Exception as exc:
        return {"name": name, "asset_id": asset_id, "status": "download_failed",
                "maps": [], "error": str(exc)[:200]}

    out_dir.mkdir(parents=True, exist_ok=True)
    saved: list[str] = []
    try:
        with zipfile.ZipFile(io.BytesIO(zip_bytes)) as z:
            entries = z.namelist()
            for substr, save_as in _MAP_PATTERNS:
                # Find the first ZIP entry whose name ends with the pattern
                # (handles both `Wood049_1K-JPG_Color.jpg` and any subdir layout).
                match = next((e for e in entries if e.endswith(substr)), None)
                if match is None:
                    continue
                with z.open(match) as src, open(out_dir / save_as, "wb") as dst:
                    shutil.copyfileobj(src, dst)
                saved.append(save_as)
    except zipfile.BadZipFile:
        return {"name": name, "asset_id": asset_id, "status": "bad_zip", "maps": []}

    if not saved:
        return {"name": name, "asset_id": asset_id, "status": "partial",
                "maps": [], "note": "zip had no matching files"}
    if len(saved) < 3:
        return {"name": name, "asset_id": asset_id, "status": "partial", "maps": saved}

    # Build a glTF-spec metallicRoughness.jpg by channel-packing:
    #   G channel  ← roughness.jpg (grayscale ambientCG file)
    #   B channel  ← metallic constant (255 for metals, 0 for non-metals)
    # glTF MeshStandardMaterial reads G=roughness, B=metallic. ambientCG
    # doesn't ship metallic maps separately, so the metallic constant is
    # uniform across the surface — fine for matte materials (always 0)
    # and for fully-metallic ones (always 255). Future: source actual
    # metallic maps if a mixed-metal material is needed.
    try:
        from PIL import Image
        rough = Image.open(out_dir / "roughness.jpg").convert("L")
        # Look up the metallic constant from the library entry. We avoid
        # importing TEXTURE_LIBRARY at module top because that module also
        # imports `pygltflib` transitively via `__init__.py`; lazy load here
        # keeps the script daemon-side.
        from engines.articulated.materials import TEXTURE_LIBRARY
        metallic_constant = int(255 * TEXTURE_LIBRARY.get(name, {}).get("default_metallic", 0.0))
        red = Image.new("L", rough.size, 0)
        metal = Image.new("L", rough.size, metallic_constant)
        mr = Image.merge("RGB", (red, rough, metal))
        mr.save(out_dir / "metallicRoughness.jpg", "JPEG", quality=88)
        saved.append("metallicRoughness.jpg")
    except Exception as exc:
        # Non-fatal: viewer falls back to uniform metallic + roughness factors.
        print(f"  [warn] {name}: metallicRoughness packing failed: {exc}")

    return {"name": name, "asset_id": asset_id, "status": "written", "maps": saved}


def main() -> None:
    force = "--force" in sys.argv
    root = textures_root()
    root.mkdir(parents=True, exist_ok=True)

    print(f"Downloading {len(_ASSETS)} CC0 PBR textures from ambientCG...")
    print(f"  destination: {root}")
    print()

    results = []
    total_bytes = 0
    for name, asset_id in _ASSETS.items():
        out_dir = root / name
        result = download_asset(name, asset_id, out_dir, force=force)
        results.append(result)
        # Print status line
        status = result["status"]
        if status == "written":
            sizes = sum((out_dir / m).stat().st_size for m in result["maps"])
            total_bytes += sizes
            maps = "+".join(m.replace(".jpg", "") for m in result["maps"])
            print(f"  [write]   {name:14s} ← {asset_id:10s}  ({maps}, {sizes // 1024} KB)")
        elif status == "kept":
            existing = sum((out_dir / m).stat().st_size for m in ("baseColor.jpg", "normal.jpg", "roughness.jpg")
                           if (out_dir / m).exists())
            total_bytes += existing
            print(f"  [keep]    {name:14s} ← already on disk ({existing // 1024} KB)")
        elif status == "partial":
            print(f"  [partial] {name:14s} ← {asset_id:10s}  got: {result.get('maps', [])}")
        elif status == "missing_id":
            print(f"  [skip]    {name:14s} ← {asset_id:10s}  (404 or empty response)")
        elif status == "download_failed":
            print(f"  [fail]    {name:14s} ← {asset_id:10s}  {result.get('error', '')[:80]}")
        elif status == "bad_zip":
            print(f"  [fail]    {name:14s} ← {asset_id:10s}  (bad zip)")
        else:
            print(f"  [???]     {name:14s} ← {result}")

    print()
    written = sum(1 for r in results if r["status"] == "written")
    kept = sum(1 for r in results if r["status"] == "kept")
    failed = sum(1 for r in results if r["status"] in ("missing_id", "download_failed", "bad_zip", "partial"))
    print(f"Done. {written} written, {kept} kept, {failed} failed/partial. Total disk: {total_bytes // (1024*1024)} MB.")
    if failed:
        print()
        print("Failed/partial entries kept their existing files (likely placeholders).")
        print("To retry: drop the affected dirs and re-run, OR edit `_ASSETS` with a different ambientCG ID.")


if __name__ == "__main__":
    main()
