#!/usr/bin/env python3
"""Regenerate the standalone Vowel Crosswalk artifact's data block.

The 151 sound-spelling correspondences have exactly one source of truth —
``apps/extension/english-learning/dictionary/crosswalk.py``. The daemon-served
page reads them over HTTP; the standalone artifact cannot (it is published to
claude.ai and a strict CSP blocks every external host), so it carries an inlined
copy. That copy is generated here rather than maintained by hand, and
``--check`` fails when the two disagree — the same shape as
``gen_trust_loop_tables.py``, so a divergence is drift rather than an editing
oversight.

Only the block between the markers is generated. The artifact's prose, layout,
styling and renderer are hand-authored and are never touched.

    python scripts/gen_vowel_crosswalk_artifact.py            # rewrite
    python scripts/gen_vowel_crosswalk_artifact.py --check    # exit 1 on drift

Field names differ between the two consumers and the mapping lives here, in one
place: the app uses ``group`` / ``vowel`` / ``grapheme`` / ``examples`` /
``strength`` / ``caveat``; the artifact's renderer predates it and uses ``g`` /
``p`` / ``g`` / ``ex`` / ``s`` / ``cav``. Renaming inside the artifact was the
alternative and was rejected — ``\\be\\.g\\b`` also matches "e.g." in prose, so a
sweep there is a foot-gun for no gain.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from scanner_lib import emit_json  # noqa: E402 — shared agent-cli envelope

ROOT = Path(__file__).resolve().parents[1]
ARTIFACT = ROOT / "apps/extension/english-learning/dictionary/artifact/vowel-crosswalk.html"

START = "// @generated-data-start"
END = "// @generated-data-end"


def load_crosswalk():
    """Import the app module without booting the kernel."""
    parent = ROOT / "apps" / "extension" / "english-learning"
    if str(parent) not in sys.path:
        sys.path.insert(0, str(parent))
    from dictionary import crosswalk  # noqa: E402

    return crosswalk


def _obj(pairs: list[tuple[str, object]]) -> str:
    """One-line JS object literal, skipping None so the output stays readable."""
    body = ", ".join(
        f"{k}:{json.dumps(v, ensure_ascii=False)}" for k, v in pairs if v is not None
    )
    return "{ " + body + " }"


def render_block(cw) -> str:
    phonemes = [v for v in cw.VOWELS if not v.get("rhotic")]
    rhotic = [v for v in cw.VOWELS if v.get("rhotic")]

    out: list[str] = [
        START,
        "// Generated by scripts/gen_vowel_crosswalk_artifact.py from",
        "// apps/extension/english-learning/dictionary/crosswalk.py — do not hand-edit.",
        "// Everything outside these markers is hand-authored.",
        "//",
        "// x = backness (0 front -> 1 back), y = height (0 close -> 1 open): the two",
        "// axes of the IPA vowel quadrilateral. Diphthongs sit at their nucleus.",
        "const PHONEMES = [",
    ]
    for v in phonemes:
        out.append("  " + _obj([
            ("id", v["id"]), ("ipa", v["ipa"]), ("key", v["key"]), ("g", v["group"]),
            ("x", v["x"]), ("y", v["y"]), ("di", v.get("di")), ("note", v["note"]),
        ]) + ",")
    out += [
        "];",
        "",
        "// R-coloured — their own band; usually analysed as vowel + /r/, which is also",
        "// why they carry no ARPABET phone and never join the error store in the app.",
        "const RHOTIC = [",
    ]
    for v in rhotic:
        out.append("  " + _obj([
            ("id", v["id"]), ("ipa", v["ipa"]), ("key", v["key"]),
            ("g", v["group"]), ("note", v["note"]),
        ]) + ",")
    out += [
        "];",
        "",
        "// Every correspondence carries real example words.",
        "// strength: core = the main pattern · common · rare = a handful of words.",
        "const EDGES = [",
    ]
    for e in cw.EDGES:
        out.append("  " + _obj([
            ("p", e["vowel"]), ("g", e["grapheme"]), ("ex", e["examples"]),
            ("s", e["strength"]), ("cav", e["caveat"]),
        ]) + ",")
    out += ["];", END]
    return "\n".join(out)


def splice(html: str, block: str) -> str:
    i, j = html.find(START), html.find(END)
    if i == -1 or j == -1:
        raise SystemExit(
            f"markers not found in {ARTIFACT.name} — expected {START} … {END}"
        )
    return html[:i] + block + html[j + len(END):]


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if the artifact's data block is stale")
    ap.add_argument("--json", action="store_true", help="machine-readable envelope")
    args = ap.parse_args()

    rel = str(ARTIFACT.relative_to(ROOT)).replace("\\", "/")

    # The public snapshot drops the whole dictionary app, and with it both the
    # module and the artifact. There is nothing to drift, so skip rather than
    # fail. A present app with a missing artifact is still a failure, below.
    app_dir = ARTIFACT.parents[1]
    if not app_dir.is_dir():
        app_rel = str(app_dir.relative_to(ROOT)).replace("\\", "/")
        msg = f"app absent at {app_rel} — nothing to check"
        return emit_json(True, "skipped", msg, {"artifact": rel}) if args.json \
            else _plain(f"skip  {msg}", 0)

    if not ARTIFACT.exists():
        return emit_json(False, "missing", f"artifact source missing at {rel}",
                         {"artifact": rel}) if args.json else _plain(
                             f"FAIL: artifact source missing at {rel}", 1)

    cw = load_crosswalk()
    current = ARTIFACT.read_text(encoding="utf-8")
    updated = splice(current, render_block(cw))
    counts = {"artifact": rel, "vowels": len(cw.VOWELS), "edges": len(cw.EDGES)}
    tally = f"{len(cw.VOWELS)} vowels, {len(cw.EDGES)} correspondences"

    if current == updated:
        msg = f"artifact data block matches crosswalk.py ({tally})"
        return emit_json(True, "ok", msg, counts) if args.json else _plain(f"OK: {msg}", 0)

    if args.check:
        msg = ("the artifact's inlined data no longer matches crosswalk.py — "
               "run scripts/gen_vowel_crosswalk_artifact.py")
        return emit_json(False, "drift", msg, counts) if args.json else _plain(
            f"DRIFT: {msg}", 1)

    ARTIFACT.write_text(updated, encoding="utf-8", newline="\n")
    msg = f"regenerated {rel} ({tally})"
    return emit_json(True, "ok", msg, counts) if args.json else _plain(msg, 0)


def _plain(message: str, code: int) -> int:
    print(message)
    return code


if __name__ == "__main__":
    raise SystemExit(main())
