"""Generate docs/TIERS.md from release.toml — the packages/distributions reference.

Reads tiers, platforms, and release targets via `doc_data.scan_release()` (with
`extends` chains resolved) and renders the authoritative "what's in each package"
doc. Operators read this to know what a `package-release.py <tier>` produces.

Usage:
    python scripts/generate_tiers_doc.py            # write docs/TIERS.md
    python scripts/generate_tiers_doc.py --check     # exit 1 if out of date (CI / preflight)

See docs/DOC-SYSTEM.md for how this fits the documentation system.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

import doc_data  # noqa: E402

OUT = ROOT / "docs" / "TIERS.md"
BANNER = "<!-- auto-generated by scripts/generate_tiers_doc.py — do not hand-edit. Run the script to refresh. -->"

# Render tiers in a product-map reading order.
_TIER_ORDER = [
    "core",
    "standard",
    "plus",
    "business",
    "english-learning",
    "englishos-cloud",
    "plekto",
    "basic-engineer",
    "engineering",
    "portfolio",
    "macro-studio",
    "labs",
    "demo",
    "dev",
]

_KIND_ORDER = ["platform", "distribution", "operational"]

_KIND_TITLES = {
    "platform": "Foundation tiers",
    "distribution": "Application distributions",
    "operational": "Operational bundles",
}


def _ordered(tiers: dict) -> list[str]:
    return [t for t in _TIER_ORDER if t in tiers] + [t for t in tiers if t not in _TIER_ORDER]


def _kind_of(tier: dict) -> str:
    return tier.get("kind") or "distribution"


def _scope(tier: dict) -> str:
    if tier.get("private"):
        return "private"
    if _kind_of(tier) == "operational":
        return "internal"
    return "public"


def _dash(value) -> str:
    return str(value) if value else "-"


def render(public_only: bool = False) -> str:
    rel = doc_data.scan_release()
    tiers = rel["tiers"]
    platforms = rel["platforms"]
    targets = rel["targets"]
    product_lines = rel["product_lines"]

    if public_only:
        # Mirror filter_release_toml: a tier marked private is not for the
        # public snapshot. Run inside the snapshot this is a near no-op (the
        # release already pruned release.toml), which is the point — the doc
        # and its source agree instead of the doc being dropped wholesale.
        # Held from v0.4.5 to v0.5.0 because the doc shipped while nothing
        # regenerated it; this is the mode that lets it ship truthfully.
        private = {n for n, t in tiers.items() if t.get("private")}
        tiers = {n: t for n, t in tiers.items() if n not in private}
        targets = {n: t for n, t in targets.items() if t.get("tier") not in private}

    ordered = _ordered(tiers)
    L: list[str] = [
        BANNER,
        "",
        "# EmptyOS Tiers & Packages",
        "",
        f"> Release manifest v{rel['version']} · {len(tiers)} tiers · {len(platforms)} platforms · {len(targets)} targets.",
        "",
        "A **tier** is a named app/plugin/skill bundle in [`release.toml`](../release.toml). "
        "`core` and `standard` are the only platform tiers. Every other tier is a "
        "packaged distribution/profile for a concrete audience or operating context. "
        "`python scripts/package-release.py <tier>` produces a self-contained bundle. "
        "Tiers compose via `extends`; the counts below are the *resolved* sets (parent + own). "
        "This doc is generated by `scripts/generate_tiers_doc.py` — see [DOC-SYSTEM.md](DOC-SYSTEM.md).",
        "",
        "## At a glance",
        "",
        "| Tier | Name | Kind | Audience | Scope | Delivery | Extends | Apps | Plugins | Skills | Purpose |",
        "|---|---|---|---|---|---|---|---|---|---|---|",
    ]
    for name in ordered:
        t = tiers[name]
        L.append(
            f"| **{name}** | {_dash(t.get('display_name'))} | {_kind_of(t)} | "
            f"{_dash(t.get('audience'))} | {_scope(t)} | {_dash(t.get('delivery'))} | "
            f"{_dash(t['extends'])} | {len(t['apps'])} | "
            f"{len(t['plugins'])} | {len(t['skills'])} | {t['description'] or '—'} |"
        )
    L.append("")
    # Derived, never written down: a literal here would be a number sitting
    # under a generated table that contradicts it, and `--check` could never
    # notice because both sides come from the same string. The public build
    # renders a filtered subset, where the count is genuinely different.
    n_none = sum(
        1 for t in tiers.values() if str(t.get("delivery", "")).startswith("none")
    )
    noun = "tier" if n_none == 1 else "tiers"
    verb = "exists" if n_none == 1 else "exist"
    pron = "It" if n_none == 1 else "They"
    L.append(
        "**Delivery** is how a tier actually reaches a user — a `[targets.*]` "
        f"entry, a `products/*/product.toml`, a Dockerfile, or nothing. {n_none} "
        f"{noun} here {'reads' if n_none == 1 else 'read'} `none`: {pron} "
        f"{verb} as a folder invariant for "
        "`check-tier-folder.py` and as documentation, and package only on demand "
        "via `package-release.py <tier>`. That is a real state, not a defect — "
        "but before this column you could only discover it by grepping the repo, "
        "which is how a tier stays under-used without anyone noticing."
    )
    L.append("")

    L.append("## Product Map")
    L.append("")
    L.append("| Product line | Tier(s) | Audience | Notes |")
    L.append("|---|---|---|---|")
    for line_id, ln in product_lines.items():
        # Rows come from `[product_lines.*]` plus each tier's `product_line`, so
        # the map cannot name a tier this doc does not contain, and a held line
        # vanishes with its tiers (a public tier in a private line is refused
        # by `check_tier_lines.py`, which the release also runs on the filtered
        # file, so no separate line filter is needed). The line names, audiences
        # and notes used to be a hardcoded table in this script, which ships —
        # the "held thing named by a shipped file" shape that leaked the tier
        # inventory in v0.4.5-v0.5.0. (`_TIER_ORDER` above still names tier ids.)
        # Operational tiers are tooling, not product.
        present = [n for n in ordered
                   if tiers[n].get("product_line") == line_id and _kind_of(tiers[n]) != "operational"]
        if not present:
            continue
        L.append(
            f"| {ln.get('display_name') or line_id} | {', '.join('`' + n + '`' for n in present)} "
            f"| {_dash(ln.get('audience'))} | {_dash(ln.get('notes'))} |"
        )
    L.append("")

    # Per-tier detail.
    L.append("## Tiers in detail")
    L.append("")
    for kind in _KIND_ORDER + sorted({_kind_of(tiers[n]) for n in ordered} - set(_KIND_ORDER)):
        names = [n for n in ordered if _kind_of(tiers[n]) == kind]
        if not names:
            continue
        L.append(f"### {_KIND_TITLES.get(kind, kind.title())}")
        L.append("")
        for name in names:
            t = tiers[name]
            title = t.get("display_name") or name
            L.append(f"#### `{name}` - {title}")
            L.append("")
            L.append(t["description"] or "_No description._")
            L.append("")
            meta = []
            if t["extends"]:
                meta.append(f"extends **{t['extends']}**")
            if t["target_platform"]:
                meta.append(f"target platform **{t['target_platform']}**")
            meta.append(f"scope **{_scope(t)}**")
            meta.append(f"{len(t['apps'])} apps · {len(t['plugins'])} plugins · {len(t['skills'])} skills (resolved)")
            L.append("- " + " · ".join(meta))
            if t["own_apps"] and t["extends"]:
                L.append(f"- adds on top of `{t['extends']}`: {', '.join(f'`{a}`' for a in t['own_apps'])}")
            L.append("")
            L.append("<details><summary>Resolved app list</summary>")
            L.append("")
            L.append(", ".join(f"`{a}`" for a in t["apps"]) or "_none_")
            L.append("")
            L.append("</details>")
            L.append("")

    # Platforms.
    L.append("## Platforms")
    L.append("")
    L.append("Deployment profiles. Plugins declare compatibility; tiers with a `target_platform` "
             "auto-filter incompatible plugins at package time.")
    L.append("")
    L.append("| Platform | Capabilities | Description |")
    L.append("|---|---|---|")
    for name, p in platforms.items():
        caps = ", ".join(p.get("caps", []) or []) or "—"
        L.append(f"| **{name}** | {caps} | {p.get('description', '')} |")
    L.append("")

    # Targets / distributions.
    L.append("## Release targets (distributions)")
    L.append("")
    L.append("Where a tier is shipped. `strip_personal` removes machine-specific content; "
             "`strip_branding` removes third-party brand names.")
    L.append("")
    L.append("| Target | Tier | Repo | Visibility | Strip personal | Strip branding | Deploy |")
    L.append("|---|---|---|---|---|---|---|")
    for name, tg in targets.items():
        L.append(
            f"| **{name}** | {tg.get('tier','')} | `{tg.get('repo','')}` | {tg.get('visibility','')} | "
            f"{tg.get('strip_personal','')} | {tg.get('strip_branding','')} | {tg.get('deploy','')} |"
        )
    L.append("")
    L.append("---")
    L.append("")
    L.append("Build a tier: `python scripts/package-release.py <tier> --check`. Add a new package "
             "by adding a `[tiers.<name>]` block to `release.toml` — the packaging script handles "
             "arbitrary tiers. See [RELEASING.md](RELEASING.md) and [DEPLOYMENT.md](DEPLOYMENT.md).")
    L.append("")
    return "\n".join(L)


def main() -> int:
    ap = argparse.ArgumentParser(description="Generate docs/TIERS.md")
    ap.add_argument("--check", action="store_true", help="exit 1 if TIERS.md is out of date")
    ap.add_argument(
        "--public-only",
        action="store_true",
        help=(
            "drop private tiers + their targets (mirrors filter_release_toml, NOT "
            "PUBLIC_TIERS — a non-private tier can still ship nothing; the release "
            "runs this only after prune_release_toml_to_snapshot has already "
            "pruned release.toml to what ships)"
        ),
    )
    args = ap.parse_args()
    content = render(public_only=args.public_only)
    if "--check" in sys.argv:
        old = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if old.strip() != content.strip():
            print("docs/TIERS.md is OUT OF DATE — run: python scripts/generate_tiers_doc.py", file=sys.stderr)
            return 1
        print("docs/TIERS.md up to date.")
        return 0
    OUT.write_text(content, encoding="utf-8")
    print(f"Wrote {OUT.relative_to(ROOT)} ({content.count(chr(10)) + 1} lines).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
