"""Generate docs/TIERS.md from release.toml — the packages/distributions reference.

Reads tiers, platforms, and release targets via `doc_data.scan_release()` (with
`extends` chains resolved) and renders the authoritative "what's in each package"
doc. Operators read this to know what a `package-release.py <tier>` produces.

Usage:
    python scripts/generate_tiers_doc.py            # write docs/TIERS.md
    python scripts/generate_tiers_doc.py --check     # exit 1 if out of date (CI / preflight)

See docs/DOC-SYSTEM.md for how this fits the documentation system.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

import doc_data  # noqa: E402

OUT = ROOT / "docs" / "TIERS.md"
BANNER = "<!-- auto-generated by scripts/generate_tiers_doc.py — do not hand-edit. Run the script to refresh. -->"

# Render tiers in a product-map reading order.
_TIER_ORDER = [
    "core",
    "standard",
    "plus",
    "english-learning",
    "englishos-cloud",
    "plekto",
    "basic-engineer",
    "engineering",
    "portfolio",
    "labs",
    "demo",
    "dev",
]

_KIND_ORDER = ["platform", "distribution", "operational"]

_KIND_TITLES = {
    "platform": "Foundation tiers",
    "distribution": "Application distributions",
    "operational": "Operational bundles",
}


def _ordered(tiers: dict) -> list[str]:
    return [t for t in _TIER_ORDER if t in tiers] + [t for t in tiers if t not in _TIER_ORDER]


def _kind_of(tier: dict) -> str:
    return tier.get("kind") or "distribution"


def _scope(tier: dict) -> str:
    if tier.get("private"):
        return "private"
    if _kind_of(tier) == "operational":
        return "internal"
    return "public"


def _dash(value) -> str:
    return str(value) if value else "-"


def render() -> str:
    rel = doc_data.scan_release()
    tiers = rel["tiers"]
    platforms = rel["platforms"]
    targets = rel["targets"]

    ordered = _ordered(tiers)
    L: list[str] = [
        BANNER,
        "",
        "# EmptyOS Tiers & Packages",
        "",
        f"> Release manifest v{rel['version']} · {len(tiers)} tiers · {len(platforms)} platforms · {len(targets)} targets.",
        "",
        "A **tier** is a named app/plugin/skill bundle in [`release.toml`](../release.toml). "
        "`core` and `standard` are the only platform tiers. Every other tier is a "
        "packaged distribution/profile for a concrete audience or operating context. "
        "`python scripts/package-release.py <tier>` produces a self-contained bundle. "
        "Tiers compose via `extends`; the counts below are the *resolved* sets (parent + own). "
        "This doc is generated by `scripts/generate_tiers_doc.py` — see [DOC-SYSTEM.md](DOC-SYSTEM.md).",
        "",
        "## At a glance",
        "",
        "| Tier | Name | Kind | Audience | Scope | Extends | Apps | Plugins | Skills | Purpose |",
        "|---|---|---|---|---|---|---|---|---|---|",
    ]
    for name in ordered:
        t = tiers[name]
        L.append(
            f"| **{name}** | {_dash(t.get('display_name'))} | {_kind_of(t)} | "
            f"{_dash(t.get('audience'))} | {_scope(t)} | {_dash(t['extends'])} | {len(t['apps'])} | "
            f"{len(t['plugins'])} | {len(t['skills'])} | {t['description'] or '—'} |"
        )
    L.append("")

    L.append("## Product Map")
    L.append("")
    L.append("| Product line | Tier(s) | Audience | Notes |")
    L.append("|---|---|---|---|")
    L.append("| EmptyOS Core | `core` | Kernel-level install | Minimal runnable OS. |")
    L.append("| EmptyOS Standard | `standard` | Default public/community install | The general-purpose OS layer other packages build from. |")
    L.append("| EmptyOS Plus | `plus` | Paid / premium users | Research + intelligence surfaces held out of the free public release. |")
    L.append("| EnglishOS | `english-learning`, `englishos-cloud` | English learners | Local learning bundle plus hosted per-learner cloud daemon. |")
    L.append("| Coding Agent | `plekto` | Coding-agent users | Branded as Plekto: persistent memory, project workspaces, multi-agent rooms. |")
    L.append("| Engineer | `basic-engineer`, `engineering`, `portfolio` | Engineering users/builders | Calculator workbench, full power-systems bundle, and live portfolio distribution. |")
    L.append("")

    # Per-tier detail.
    L.append("## Tiers in detail")
    L.append("")
    for kind in _KIND_ORDER + sorted({_kind_of(tiers[n]) for n in ordered} - set(_KIND_ORDER)):
        names = [n for n in ordered if _kind_of(tiers[n]) == kind]
        if not names:
            continue
        L.append(f"### {_KIND_TITLES.get(kind, kind.title())}")
        L.append("")
        for name in names:
            t = tiers[name]
            title = t.get("display_name") or name
            L.append(f"#### `{name}` - {title}")
            L.append("")
            L.append(t["description"] or "_No description._")
            L.append("")
            meta = []
            if t["extends"]:
                meta.append(f"extends **{t['extends']}**")
            if t["target_platform"]:
                meta.append(f"target platform **{t['target_platform']}**")
            meta.append(f"scope **{_scope(t)}**")
            meta.append(f"{len(t['apps'])} apps · {len(t['plugins'])} plugins · {len(t['skills'])} skills (resolved)")
            L.append("- " + " · ".join(meta))
            if t["own_apps"] and t["extends"]:
                L.append(f"- adds on top of `{t['extends']}`: {', '.join(f'`{a}`' for a in t['own_apps'])}")
            L.append("")
            L.append("<details><summary>Resolved app list</summary>")
            L.append("")
            L.append(", ".join(f"`{a}`" for a in t["apps"]) or "_none_")
            L.append("")
            L.append("</details>")
            L.append("")

    # Platforms.
    L.append("## Platforms")
    L.append("")
    L.append("Deployment profiles. Plugins declare compatibility; tiers with a `target_platform` "
             "auto-filter incompatible plugins at package time.")
    L.append("")
    L.append("| Platform | Capabilities | Description |")
    L.append("|---|---|---|")
    for name, p in platforms.items():
        caps = ", ".join(p.get("caps", []) or []) or "—"
        L.append(f"| **{name}** | {caps} | {p.get('description', '')} |")
    L.append("")

    # Targets / distributions.
    L.append("## Release targets (distributions)")
    L.append("")
    L.append("Where a tier is shipped. `strip_personal` removes machine-specific content; "
             "`strip_branding` removes third-party brand names.")
    L.append("")
    L.append("| Target | Tier | Repo | Visibility | Strip personal | Strip branding | Deploy |")
    L.append("|---|---|---|---|---|---|---|")
    for name, tg in targets.items():
        L.append(
            f"| **{name}** | {tg.get('tier','')} | `{tg.get('repo','')}` | {tg.get('visibility','')} | "
            f"{tg.get('strip_personal','')} | {tg.get('strip_branding','')} | {tg.get('deploy','')} |"
        )
    L.append("")
    L.append("---")
    L.append("")
    L.append("Build a tier: `python scripts/package-release.py <tier> --check`. Add a new package "
             "by adding a `[tiers.<name>]` block to `release.toml` — the packaging script handles "
             "arbitrary tiers. See [RELEASING.md](RELEASING.md) and [DEPLOYMENT.md](DEPLOYMENT.md).")
    L.append("")
    return "\n".join(L)


def main() -> int:
    ap = argparse.ArgumentParser(description="Generate docs/TIERS.md")
    ap.add_argument("--check", action="store_true", help="exit 1 if TIERS.md is out of date")
    ap.parse_args()
    content = render()
    if "--check" in sys.argv:
        old = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if old.strip() != content.strip():
            print("docs/TIERS.md is OUT OF DATE — run: python scripts/generate_tiers_doc.py", file=sys.stderr)
            return 1
        print("docs/TIERS.md up to date.")
        return 0
    OUT.write_text(content, encoding="utf-8")
    print(f"Wrote {OUT.relative_to(ROOT)} ({content.count(chr(10)) + 1} lines).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
