"""Generate docs/APPS.md from the live app tree — the app catalog.

Reads facts via `doc_data.scan_apps()` (depth-agnostic, never drifts) and polishes
one-line summaries via `doc_llm.enrich_apps()` (best-effort, cached). Groups apps
by track → group (public/core, public/standard, public/labs, extension/<group>).

Usage:
    python scripts/generate_apps_doc.py            # write docs/APPS.md
    python scripts/generate_apps_doc.py --llm      # also LLM-polish summaries (needs daemon)
    python scripts/generate_apps_doc.py --check     # exit 1 if out of date (CI / preflight)

See docs/DOC-SYSTEM.md for how this fits the documentation system.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

import doc_data  # noqa: E402
import doc_llm  # noqa: E402

OUT = ROOT / "docs" / "APPS.md"
BANNER = "<!-- auto-generated by scripts/generate_apps_doc.py — do not hand-edit. Run the script to refresh. -->"

# Tiers that ship in the public OSS release — the one definition, shared with
# release-public.py. `--public-only` restricts the catalog to these apps — used
# for the shipped copy so a public reader doesn't see extension/labs apps absent
# from their bundle.
from emptyos.sdk.release_tiers import PUBLIC_TIERS  # noqa: E402

# Track/group display order + heading text.
_GROUP_ORDER = ["public/core", "public/standard", "public/englishos", "public/labs"]
_GROUP_TITLE = {
    "public/core": "Core — minimum OS (always installed)",
    "public/standard": "Standard — full builder OS",
    "public/englishos": "EnglishOS — open English-learning edition",
    "public/labs": "Labs — experimental / pre-1.0",
}
_EXT_TITLE = {
    "engineering": "Extension · Engineering — power-systems calculators (tracked, never public)",
    "english-learning": "Extension · English-learning (tracked, never public)",
    "dev": "Extension · Dev tooling (tracked, never public)",
    "others": "Extension · Others (tracked, never public)",
    "portfolio": "Extension · Portfolio (tracked, never public)",
    "plekto": "Extension · Plekto distribution (tracked, never public)",
    "plus": "Extension · Plus — premium distribution (tracked, never public)",
    "business": "Extension · Business — consulting tools (tracked, never public)",
    "labs": "Extension · Labs — experiments (tracked, never public)",
}


def _key(app: dict) -> str:
    return f"{app['track']}/{app['group']}" if app["group"] else app["track"]


def render() -> str:
    public_only = "--public-only" in sys.argv
    rel = doc_data.scan_release()
    apps = [a for a in doc_data.scan_apps() if a["track"] in ("public", "extension")]
    if public_only:
        # Restrict to the apps that actually ship publicly (PUBLIC_TIERS resolved).
        public_ids: set[str] = set()
        for t in PUBLIC_TIERS:
            public_ids.update(rel["tiers"].get(t, {}).get("apps", []))
        apps = [a for a in apps if a["track"] == "public" and a["id"] in public_ids]
    summaries = doc_llm.enrich_apps(apps, use_llm="--llm" in sys.argv)

    total = len(apps)
    plugins = len(doc_data.scan_plugins())
    caps = len(doc_data.scan_capabilities())

    groups: dict[str, list[dict]] = {}
    for a in apps:
        groups.setdefault(_key(a), []).append(a)

    intro = (
        ["> The apps that ship in a public EmptyOS release (the `core`, `standard` and `englishos` tiers)."]
        if public_only
        else [
            "> All apps are first-class — same manifest, same lifecycle, same loader. App **ids** are",
            "> independent of folder location. A public `git clone` ships `public/core`, `public/standard` and `public/englishos`;",
            "> `extension/` and `personal/` are filtered out of public releases.",
        ]
    )
    L: list[str] = [
        BANNER,
        "",
        "# EmptyOS Apps",
        "",
        f"> {total} apps · {plugins} plugins · {caps} capabilities · release v{rel['version']}.",
        ">",
        *intro,
        "",
        "Live inventory is authoritative — run `eos app list`, or `eos app info <id>` for any app's",
        "self-generated docs. This catalog is regenerated from manifests by",
        "`scripts/generate_apps_doc.py`; see [DOC-SYSTEM.md](DOC-SYSTEM.md).",
        "",
    ]

    def table(rows: list[dict]) -> list[str]:
        out = ["| App | What it does | Capabilities |", "|---|---|---|"]
        for a in sorted(rows, key=lambda x: x["id"]):
            summ = summaries.get(a["id"], {}).get("summary", "") or "—"
            caps = ", ".join(a["capabilities"]) if a["capabilities"] else "—"
            out.append(f"| **{a['id']}** | {summ} | {caps} |")
        return out

    # Public tracks in fixed order.
    for key in _GROUP_ORDER:
        rows = groups.get(key)
        if not rows:
            continue
        L.append(f"## {_GROUP_TITLE.get(key, key)}")
        L.append("")
        L.append(f"*{len(rows)} apps.*")
        L.append("")
        L += table(rows)
        L.append("")

    # Extension groups, alphabetical.
    ext_keys = sorted(k for k in groups if k.startswith("extension/"))
    if ext_keys:
        L.append("## Extension track")
        L.append("")
        L.append(
            "Tracked in the repo but **never shipped to the public OSS release** — engineering "
            "calculators, English-learning, dev tooling, and branded-distribution apps."
        )
        L.append("")
        for key in ext_keys:
            grp = key.split("/", 1)[1]
            rows = groups[key]
            # An unmapped group used to render as a bare `Extension · <grp>`
            # heading, which reads like a deliberate title — so a new extension
            # group could sit untitled in the shipped catalog indefinitely
            # (apps/extension/labs did, until 2026-08-30). Degrade loudly.
            L.append(
                f"### {_EXT_TITLE[grp]}"
                if grp in _EXT_TITLE
                else f"### Extension · {grp} — UNTITLED GROUP (add it to _EXT_TITLE)"
            )
            L.append("")
            L.append(f"*{len(rows)} apps.*")
            L.append("")
            L += table(rows)
            L.append("")

    L.append("---")
    L.append("")
    L.append("**Personal apps** (`apps/personal/`) are gitignored and machine-specific — never listed here.")
    L.append("Every app follows `manifest.toml` + `app.py` (+ optional `pages/`). Apps without `pages/`")
    L.append("get an auto-generated UI. See [APP-DEVELOPMENT.md](APP-DEVELOPMENT.md).")
    L.append("")
    return "\n".join(L)


def main() -> int:
    ap = argparse.ArgumentParser(description="Generate docs/APPS.md")
    ap.add_argument("--check", action="store_true", help="exit 1 if APPS.md is out of date")
    ap.add_argument("--llm", action="store_true", help="LLM-polish summaries (needs daemon)")
    ap.add_argument("--public-only", action="store_true",
                    help="restrict to apps shipped publicly (PUBLIC_TIERS) — for the shipped copy")
    ap.parse_args()
    content = render()
    if "--check" in sys.argv:
        old = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if old.strip() != content.strip():
            print("docs/APPS.md is OUT OF DATE — run: python scripts/generate_apps_doc.py", file=sys.stderr)
            return 1
        print("docs/APPS.md up to date.")
        return 0
    OUT.write_text(content, encoding="utf-8")
    print(f"Wrote {OUT.relative_to(ROOT)} ({content.count(chr(10)) + 1} lines).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
