"""Generate docs/SKILLS.md from the live skill trees — the skill matrix.

Scans the two repo skill roots and renders one matrix per root, plus a
"needs attention" self-audit section reusing check_skills.lint_one (per
.claude/rules/self-audit-loops.md — the doc is a rerunnable audit surface,
not a hand-maintained catalog):

  .claude/skills/   project skills — read natively by the Claude Code harness
                    AND by the daemon agent's discover_skills()
  skills/           bundled product skills — daemon-side only (agent app);
                    a machine's ~/.claude/skills copies override these

The user-global store (~/.claude/skills) is deliberately NOT rendered here —
this doc is committed and must stay machine-independent. That store's index
is ~/.claude/skills/_skills-index.md (regenerated by its _generate_index.py).

Usage:
    python scripts/generate_skills_doc.py           # write docs/SKILLS.md
    python scripts/generate_skills_doc.py --check   # exit 1 if out of date (CI / preflight)
"""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "scripts"))

import check_skills  # noqa: E402  — reuse FM_RE + lint_one, don't re-roll

OUT = ROOT / "docs" / "SKILLS.md"
BANNER = (
    "<!-- auto-generated by scripts/generate_skills_doc.py — do not hand-edit. "
    "Run the script to refresh. -->"
)

PROJECT = ROOT / ".claude" / "skills"
BUNDLED = ROOT / "skills"

# Theme buckets for the project (eos-*) tree — curated here so a new skill
# lands visibly in "other" until someone files it. Bundled skills derive
# their family from the name prefix instead.
PROJECT_THEMES: dict[str, str] = {
    "preflight": "session lifecycle",
    "env-check": "session lifecycle",
    "eos-session-resume": "session lifecycle",
    "eos-session-wrapup": "session lifecycle",
    "eos-devlog-publish": "session lifecycle",
    "eos-architecture-review": "audit / review",
    "eos-bug-audit": "audit / review",
    "eos-kb-audit": "audit / review",
    "eos-simplify": "audit / review",
    "eos-design-system-audit": "audit / review",
    "eos-page-design-review": "audit / review",
    "eos-security-review": "audit / review",
    "eos-geo-audit": "audit / review",
    "eos-ui-walk": "audit / review",
    "eos-usecase-audit": "audit / review",
    "eos-model-bench-scenario-audit": "audit / review",
    "eos-insights": "reflection",
    "eos-life-insights": "reflection",
    "eos-week-review": "reflection",
    "eos-new-app": "scaffold / extract",
    "eos-new-plugin": "scaffold / extract",
    "eos-sdk-extract": "scaffold / extract",
    "eos-repo-extract": "scaffold / extract",
    "eos-restructure": "scaffold / extract",
    "eos-vault-migration": "scaffold / extract",
    "eos-legacy-data-borrow": "scaffold / extract",
    "eos-release": "release / deploy",
    "eos-release-public": "release / deploy",
    "eos-system-install": "release / deploy",
    "eos-deploy-homepc": "release / deploy",
    "eos-external-vault-connector": "release / deploy",
    "eos-kb-atomize": "kb / vault",
    "eos-vault-study-pack": "kb / vault",
    "eos-tutorial": "kb / vault",
    "eos-tutorial-verify": "kb / vault",
    "eos-orgs-create": "orgs",
    "eos-orgs-list": "orgs",
    "eos-orgs-member-add": "orgs",
    "eos-orgs-run-scenario": "orgs",
    "eos-fix-drain": "self-fix loop",
    "eos-commit-mine": "git hygiene",
    "eos-worktree-gc": "git hygiene",
    "eos-screenshot": "media / publishing",
    "eos-image-edit": "media / publishing",
    "eos-article-diagrams": "media / publishing",
    "eos-podcast": "media / publishing",
    "eos-viz-pattern-seed": "media / publishing",
    "eos-communication-define-your-reader": "media / publishing",
    "eos-fde-engagement": "engagements",
}

USE_SPLIT_RE = re.compile(r"\s+(?:Use when|Use this|Run this|Use at|Use whenever)\b", re.I)
TRIGGER_RE = re.compile(r'"([^"]{2,60})"')
ROUTE_RE = re.compile(r"\(use ([^)]+)\)", re.I)
SLUG_RE = re.compile(r"\b[a-z0-9]+(?:-[a-z0-9]+)+\b")


def _essential_skills() -> set[str]:
    """Parse ESSENTIAL_SKILLS from the store app so the doc can't drift from it."""
    src = ROOT / "apps" / "public" / "core" / "store" / "app.py"
    try:
        m = re.search(r"ESSENTIAL_SKILLS\s*=\s*\{([^}]*)\}", src.read_text(encoding="utf-8"))
        if m:
            return set(re.findall(r'"([^"]+)"', m.group(1)))
    except OSError:
        pass
    return {"eos-session-resume", "eos-session-wrapup"}


def _description(d: Path) -> str:
    """The `description:` line from a skill dir's SKILL.md frontmatter (regex, like check_skills)."""
    f = d / "SKILL.md"
    if not f.exists():
        return ""
    m = check_skills.FM_RE.match(f.read_text(encoding="utf-8", errors="replace"))
    if not m:
        return ""
    dm = re.search(r"^description:\s*(.+?)\s*$", m.group(1), re.M)
    return dm.group(1).strip().strip("'\"") if dm else ""


def _purpose(desc: str) -> str:
    head = USE_SPLIT_RE.split(desc)[0].strip()
    if len(head) > 160:
        head = head[:157].rstrip() + "..."
    return head


def _triggers(desc: str) -> str:
    hits = TRIGGER_RE.findall(desc)[:3]
    return ", ".join(f'"{h}"' for h in hits)


def _routes(desc: str, known: set[str]) -> str:
    targets: list[str] = []
    for grp in ROUTE_RE.findall(desc):
        for slug in SLUG_RE.findall(grp):
            if slug in known and slug not in targets:
                targets.append(slug)
    return ", ".join(targets)


def _gitignored(paths: list[Path]) -> set[Path]:
    """Subset of ``paths`` that git is deliberately ignoring.

    This doc is TRACKED and ships in a public release, but the generator walks
    the filesystem — so a skill excluded on purpose via .gitignore would still
    have its name and description written into it. Three such skills were
    caught that way (.gitignore:75-77).

    Fails OPEN: if git is unavailable the doc is generated as before rather
    than silently losing rows.
    """
    if not paths:
        return set()
    try:
        proc = subprocess.run(
            ["git", "check-ignore", "--stdin"],
            input="\n".join(str(p) for p in paths),
            capture_output=True, text=True, cwd=str(ROOT), timeout=15,
        )
    except (OSError, subprocess.SubprocessError):
        return set()
    # rc 0 = some ignored, 1 = none ignored, 128 = not a repo / error.
    if proc.returncode not in (0, 1):
        return set()
    out = {Path(line.strip()) for line in proc.stdout.splitlines() if line.strip()}
    return {p for p in paths if p in out or Path(str(p)) in out}


def _skill_dirs(root: Path) -> list[Path]:
    if not root.is_dir():
        return []
    dirs = sorted(
        p for p in root.iterdir() if p.is_dir() and not p.name.startswith(("_", "."))
    )
    ignored = _gitignored(dirs)
    return [p for p in dirs if p not in ignored]


def _esc(s: str) -> str:
    return s.replace("|", "\\|")


def _table(dirs: list[Path], theme_of, known: set[str], essentials: set[str]) -> list[str]:
    rows = [
        "| Skill | Theme | Purpose | Trigger cues | Routes to |",
        "|---|---|---|---|---|",
    ]
    for d in sorted(dirs, key=lambda p: (theme_of(p.name), p.name)):
        desc = _description(d)
        star = " ⭐" if d.name in essentials else ""
        rows.append(
            f"| **{d.name}**{star} | {theme_of(d.name)} | {_esc(_purpose(desc))} "
            f"| {_esc(_triggers(desc))} | {_esc(_routes(desc, known))} |"
        )
    return rows


def render() -> str:
    project_dirs = _skill_dirs(PROJECT)
    bundled_dirs = _skill_dirs(BUNDLED)
    retired = sorted(p.name for p in (PROJECT / "_retired").glob("*") if p.is_dir())
    essentials = _essential_skills()

    known = {d.name for d in project_dirs} | {d.name for d in bundled_dirs}
    # user-global-only siblings referenced in routing (kept minimal + name-only,
    # so the committed doc stays machine-independent):
    known |= {
        "vault-source-digest", "vault-ai-conversation-digest", "vault-yt-digest",
        "vault-info-ripple", "vault-semantic-search", "tool-academic-search",
        "tool-pdf-reader", "tool-youtube-transcript", "creative-suno-archive",
        "life-communication-written", "life-communication-speaking",
        "life-communication-playbook", "eos-deploy-homepc",
    }

    def project_theme(name: str) -> str:
        return PROJECT_THEMES.get(name, "other")

    def bundled_theme(name: str) -> str:
        # bundled skills are prefix-namespaced (creative-*, life-*, vault-*, …)
        return name.split("-", 1)[0]

    lines: list[str] = [
        BANNER,
        "",
        "# EmptyOS Skills — the skill matrix",
        "",
        f"> {len(project_dirs)} project skills + {len(bundled_dirs)} bundled skills"
        " across two repo roots (plus a per-machine user-global store).",
        ">",
        "> **Discovery precedence** (`apps/public/standard/agent/skills.py`):"
        " bundled `skills/` → project `.claude/skills/` → user `~/.claude/skills/`,"
        " later wins. The Claude Code harness reads the project + user roots natively;"
        " the daemon agent reads all three. `_`-prefixed dirs (`_retired/`) are skipped"
        " everywhere.",
        ">",
        "> **Authoring contract** (enforced by `scripts/check_skills.py`, see that file's"
        " docstring): frontmatter `name` == dir slug; single-line `description` with no"
        " colon-space, shaped as *what-it-does — Use when \"trigger\", \"trigger\" — NOT for X"
        " (use other-skill)*. The routing column below is parsed from those NOT-for clauses.",
        ">",
        "> **Progressive disclosure** (not machine-checked — judgment): the harness loads only"
        " `SKILL.md`. Past ~250 lines, move templates, example outputs, lookup tables, and"
        " command detail into siblings (`templates.md`, `examples.md`, `cli-reference.md`, …)"
        " and add a `## Reference files (read on demand)` table naming each with an absolute"
        " `<SKILL_DIR>/<file>` path and a *read when* column. Workflow steps, routing tables,"
        " and **every safety rule** stay in the spine — never behind an on-demand read.",
        ">",
        "> **Living-memory sidecar**: a skill that accumulates state across sessions keeps it in"
        " `<topic>-memory.md` beside its SKILL.md (current-state snapshot, dated updates,"
        " learnings). The SKILL.md must say *read it first* and *update it after* — a sidecar"
        " no SKILL.md mentions is dead weight. Memory files are per-machine living data and are"
        " never copied into the bundled `skills/` tree (`scripts/sync_user_skills.py` skips them).",
        "",
        "Regenerate — `python scripts/generate_skills_doc.py` · essential (never"
        " uninstallable via the Store) marked ⭐ — parsed from"
        " `apps/public/core/store/app.py`.",
        "",
        "## Project skills — `.claude/skills/` (harness + daemon)",
        "",
    ]
    lines += _table(project_dirs, project_theme, known, essentials)
    lines += [
        "",
        "## Bundled product skills — `skills/` (daemon-side; user-global copies override)",
        "",
    ]
    lines += _table(bundled_dirs, bundled_theme, known, essentials)

    if retired:
        lines += [
            "",
            "## Retired — `.claude/skills/_retired/`",
            "",
        ]
        lines += [f"- `{name}`" for name in retired]

    # Self-audit tail — same checks the preflight gate runs; an empty section is
    # the healthy state (audits.md: never ship a noisy report).
    findings: list[str] = []
    for d in project_dirs:
        hard, soft = check_skills.lint_one(d)
        findings += [f"HARD — {x}" for x in hard] + [f"soft — {x}" for x in soft]
    for d in bundled_dirs:
        hard, soft = check_skills.lint_one(d, mirror_root=None)
        findings += [f"HARD — [bundled] {x}" for x in hard] + [f"soft — [bundled] {x}" for x in soft]

    lines += ["", "## Needs attention", ""]
    if findings:
        lines += [f"- {f}" for f in findings]
    else:
        lines += ["Nothing — every skill satisfies the authoring contract."]
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    text = render()
    if "--check" in sys.argv:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != text:
            print("docs/SKILLS.md is out of date — run: python scripts/generate_skills_doc.py")
            return 1
        print("docs/SKILLS.md is current")
        return 0
    OUT.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
