#!/usr/bin/env python3
"""Generate EmptyOS site pages from live system state.

Scans app/plugin manifests and capability definitions, then writes
auto-generated markdown pages into the EmptyOS site source folder.

Usage:
    python scripts/generate_emptyos_site.py              # apply changes
    python scripts/generate_emptyos_site.py --dry-run     # show what would change
    python scripts/generate_emptyos_site.py --vault PATH  # explicit vault path
"""

import argparse
import json
import re
import sys
import tomllib
from datetime import date
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent

AUTOGEN_HEADER = "<!-- auto-generated by scripts/generate_emptyos_site.py — do not edit by hand -->"

STATS_START = "<!-- stats:start -->"
STATS_END = "<!-- stats:end -->"

CAPABILITIES = [
    ("think", "LLM reasoning", "ollama, openai, claude-cli, human"),
    ("read", "Read files", "filesystem, human"),
    ("write", "Write files", "filesystem, human"),
    ("search", "Find content", "grep, human"),
    ("speak", "Text to speech", "voice-api (kokoro, edge-tts, xtts)"),
    ("listen", "Speech to text", "voice-api (whisper)"),
    ("draw", "Image generation", "comfyui"),
]

APP_CATEGORIES = {
    "Infrastructure": [
        "quick-action",
        "note",
        "task",
        "link",
        "tmpl",
        "run",
        "git",
    ],
    "Productivity": [
        "search",
        "journal",
        "briefing",
        "expense",
        "contacts",
        "projects",
        "assistant",
        "focus",
        "tracker",
        "review",
        "timeline",
        "nutrition",
        "reader",
        "items",
        "places",
        "news-center",
        "quotes",
        "dictionary",
        "healing",
        "media",
        "divination",
        "meditation",
        "bookmarks",
        "habits",
        "quickref",
        "recipes",
        "reminders",
        "sleep",
        "weather",
        "workout",
        "reflect",
    ],
    "Creative": [
        "music-studio",
        "studio",
        "gpts",
        "publish",
        "fiction-engine",
        "comfyui-app",
        "3d-studio",
    ],
    "Voice & Language": [
        "english",
        "speaking",
        "voice-review",
        "shadowing",
        "tts",
        "lessons",
    ],
    "Career": [
        "jobs",
        "github-connector",
    ],
    "Engineering": [
        "cable",
        "sheath-voltage",
    ],
    "System": [
        "settings",
        "system-log",
        "billing",
        "app-analytics",
        "app-gen",
        "reactor",
        "model-bench",
        "integrity",
        "finance",
        "hub",
        "web-analytics",
        "plugin-gen",
        "release",
        "tests",
        "ai-queue",
    ],
    "Composition": [
        "digest",
        "staff",
        "podcast",
    ],
}


def resolve_vault_path(explicit: str | None = None) -> Path | None:
    conn_file = PROJECT_ROOT / ".claude" / "vault-connection.json"
    if explicit:
        return Path(explicit)
    if conn_file.exists():
        data = json.loads(conn_file.read_text())
        if data.get("connected") and data.get("vault_path"):
            return Path(data["vault_path"])
    toml_file = PROJECT_ROOT / "emptyos.toml"
    if toml_file.exists():
        with open(toml_file, "rb") as f:
            cfg = tomllib.load(f)
        p = cfg.get("notes", {}).get("path", "")
        if p:
            return Path(p)
    return None


def scan_manifests(base_dirs: list[Path], key: str = "app") -> list[dict]:
    results = []
    for base in base_dirs:
        if not base.exists():
            continue
        for mf in sorted(base.glob("*/manifest.toml")):
            if "_retired" in str(mf) or "_example" in str(mf):
                continue
            try:
                with open(mf, "rb") as f:
                    data = tomllib.load(f)
                entry = data.get(key, {})
                entry["_path"] = mf.parent
                entry["_has_ui"] = (mf.parent / "pages" / "index.html").exists()
                entry["_provides"] = data.get("provides", {})
                entry["_requires"] = data.get("requires", {})
                results.append(entry)
            except Exception:
                continue
    return results


def count_endpoints() -> int:
    count = 0
    for pyfile in PROJECT_ROOT.rglob("*.py"):
        rel = pyfile.relative_to(PROJECT_ROOT)
        parts = rel.parts
        if parts[0] not in ("apps", "plugins"):
            continue
        if "_retired" in str(pyfile):
            continue
        try:
            text = pyfile.read_text(encoding="utf-8", errors="ignore")
            count += text.count("@web_route")
        except Exception:
            continue
    return count


def categorize_app(app_id: str) -> str | None:
    for cat, ids in APP_CATEGORIES.items():
        if app_id in ids:
            return cat
    return None


def generate_apps_md(apps: list[dict]) -> str:
    categorized: dict[str, list[dict]] = {}
    uncategorized = []
    for app in apps:
        cat = categorize_app(app.get("id", ""))
        if cat:
            categorized.setdefault(cat, []).append(app)
        else:
            uncategorized.append(app)

    total = len(apps)
    lines = [
        "---",
        "title: App Catalog",
        "type: page",
        "publish: true",
        "nav_order: 3",
        "nav_label: Apps",
        f"summary: All {total} apps organized by category — infrastructure, productivity, creative, voice, and system",
        "---",
        "",
        AUTOGEN_HEADER,
        "",
    ]

    cat_order = list(APP_CATEGORIES.keys())
    for cat in cat_order:
        cat_apps = categorized.get(cat, [])
        if not cat_apps:
            continue
        lines.append(f"## {cat}")
        lines.append("")
        lines.append("| App | What It Does |")
        lines.append("|---|---|")
        for app in cat_apps:
            name = f"**{app.get('id', '?')}**"
            desc = app.get("description", "").rstrip(".")
            lines.append(f"| {name} | {desc} |")
        lines.append("")

    if uncategorized:
        lines.append("## Other")
        lines.append("")
        lines.append("| App | What It Does |")
        lines.append("|---|---|")
        for app in uncategorized:
            name = f"**{app.get('id', '?')}**"
            desc = app.get("description", "").rstrip(".")
            lines.append(f"| {name} | {desc} |")
        lines.append("")

    lines.append("## The Pattern")
    lines.append("")
    lines.append("Every app follows the same structure:")
    lines.append("")
    lines.append("```")
    lines.append("apps/{id}/")
    lines.append("├── manifest.toml    # Declares id, capabilities, events, routes")
    lines.append("├── app.py           # Python class extending BaseApp")
    lines.append("├── __init__.py")
    lines.append("└── pages/           # HTML files for custom UI (optional)")
    lines.append("    └── index.html")
    lines.append("```")
    lines.append("")
    lines.append(
        "Apps without `pages/` get an auto-generated UI. Apps with custom pages get hot-reloaded HTML — edit and refresh, no restart needed."
    )
    lines.append("")
    return "\n".join(lines)


def generate_plugins_md(plugins: list[dict]) -> str:
    lines = [
        "---",
        "title: Plugins",
        "type: page",
        "publish: true",
        "nav_order: 4",
        "nav_label: Plugins",
        "summary: How plugins extend EmptyOS — services, enhancers, and graceful degradation",
        "---",
        "",
        AUTOGEN_HEADER,
        "",
        "## Plugin Types",
        "",
        "Plugins come in two flavors:",
        "",
        '**Service plugins** expose named services that apps access explicitly via `self.require("name")` or `self.service("name")`.',
        "",
        "**Enhancer plugins** dynamically inject providers into capabilities at startup. If the plugin is absent or offline, the capability falls back to the next provider. No app code changes needed.",
        "",
        "This is the **Graceful Enhancement** pattern: capabilities degrade silently when a plugin goes offline. Your search still works without the search enhancer — it just loses graph-aware features.",
        "",
        "## Active Plugins",
        "",
        "| Plugin | Type | What It Does |",
        "|---|---|---|",
    ]

    plugin_types = {
        "health": "Service",
        "ollama": "Enhancer (think)",
        "comfyui": "Enhancer (draw)",
        "voice-api": "Enhancer (speak+listen)",
        "applio": "Service",
        "notifications": "Service",
        "telegram": "Service",
        "blender": "Service",
    }

    for p in plugins:
        pid = p.get("id", "?")
        desc = p.get("description", "").rstrip(".")
        ptype = plugin_types.get(pid, "Service")
        lines.append(f"| **{pid}** | {ptype} | {desc} |")

    lines.extend(
        [
            "",
            "## How Enhancers Work",
            "",
            "When the Ollama plugin starts, it registers itself as a provider for the `think` capability at priority 0 (highest). The capability's provider chain becomes:",
            "",
            "```",
            "think: ollama → openai → claude-cli → human",
            "```",
            "",
            "If Ollama crashes mid-request, the capability automatically falls back to OpenAI. Apps never see the failure — they just get a response.",
            "",
            "```python",
            "# This code never changes regardless of which providers are available",
            'result = await self.think("Analyze this code", domain="code")',
            "```",
            "",
            "## Plugin Configuration",
            "",
            "Plugins are configured in `emptyos.toml`:",
            "",
            "```toml",
            "[plugins.ollama]",
            'url = "http://localhost:11434"',
            "",
            "[plugins.comfyui]",
            'url = "http://127.0.0.1:8188"',
            'launcher = "D:/ComfyUI/run.bat"',
            "",
            "[plugins.telegram]",
            'token = "bot-token-here"',
            "allowed_users = [123456789]",
            "```",
            "",
            "Plugins with a `launcher` config can auto-start their external service when EmptyOS boots.",
            "",
            "## Auto-Start Pattern",
            "",
            "External services use embedded runtimes with headless launch:",
            "",
            "```python",
            "# Plugin auto_start() — no visible windows",
            "subprocess.Popen(",
            '    [python_exe, "-s", main_py, "--flags"],',
            "    cwd=launcher_dir,",
            "    creationflags=subprocess.CREATE_NO_WINDOW,",
            "    stdout=subprocess.DEVNULL,",
            "    stderr=subprocess.DEVNULL,",
            ")",
            "```",
            "",
            "The health plugin polls each service endpoint until ready, with a 60-second timeout.",
            "",
            "## Writing a Plugin",
            "",
            "```python",
            "class MyPlugin(BasePlugin):",
            "    async def on_start(self):",
            "        # Register as a service",
            '        self.register_service("my_service", self)',
            "        ",
            "        # Or inject into a capability (enhancer pattern)",
            '        self.inject_provider("think", MyProvider(), priority=0)',
            "    ",
            "    async def on_stop(self):",
            "        pass",
            "```",
            "",
            "Place in `plugins/my-plugin/` with a `plugin.py` and manifest. The plugin loader discovers it automatically.",
            "",
        ]
    )
    return "\n".join(lines)


def generate_capabilities_md() -> str:
    lines = [
        "---",
        "title: Capabilities",
        "type: page",
        "publish: true",
        "nav_order: 5",
        "nav_label: Capabilities",
        "summary: The 7 capabilities that every EmptyOS app accesses — think, read, write, search, speak, listen, draw",
        "---",
        "",
        AUTOGEN_HEADER,
        "",
        "## The Capability Model",
        "",
        "Every app accesses the world through capabilities, never direct tools. A capability is a human verb — think, read, write, search, speak, listen, draw — with a chain of providers that try in order until one succeeds.",
        "",
        "Human is always the final fallback. If every tool is offline, the system asks you.",
        "",
        "## 7 Capabilities",
        "",
        "| Capability | Purpose | Providers |",
        "|---|---|---|",
    ]
    for name, purpose, providers in CAPABILITIES:
        lines.append(f"| **{name}** | {purpose} | {providers} |")

    lines.extend(
        [
            "",
            "## Provider Chains",
            "",
            "Providers are tried in priority order. Plugins inject high-priority providers at startup (enhancer pattern).",
            "",
            "```",
            "think: ollama → openai → claude-cli → human",
            "read:  filesystem → human",
            "write: filesystem → human",
            "search: grep → human",
            "speak: voice-api (kokoro → edge-tts → xtts)",
            "listen: voice-api (whisper)",
            "draw:  comfyui",
            "```",
            "",
            "If a plugin is absent, its provider simply isn't in the chain. Apps never know which provider answered — they just call `self.think()` or `self.search()`.",
            "",
            "## Domain Routing",
            "",
            "The `think` capability supports domain-specific routing. Different domains can use different models:",
            "",
            "```python",
            "# Uses the domain-specific provider chain for 'code'",
            'result = await self.think("Analyze this", domain="code")',
            "",
            "# Default chain",
            'result = await self.think("Summarize this article")',
            "```",
            "",
            "Domains are configured in `emptyos.toml` under `[capabilities.think.domains]`.",
            "",
        ]
    )
    return "\n".join(lines)


def inject_stats(content: str, stats_block: str) -> str:
    if STATS_START in content and STATS_END in content:
        pattern = re.compile(
            re.escape(STATS_START) + r".*?" + re.escape(STATS_END),
            re.DOTALL,
        )
        replacement = f"{STATS_START}\n{stats_block}\n{STATS_END}"
        return pattern.sub(replacement, content)
    return content


def fetch_integrity_audit() -> dict | None:
    """Fetch current integrity score from a running daemon.

    Returns None if the daemon isn't reachable — graceful degradation so the
    script still works offline. Also returns None on malformed responses.
    """
    try:
        import urllib.request

        with urllib.request.urlopen(
            "http://localhost:9000/integrity/api/audit",
            timeout=3,
        ) as resp:
            data = json.loads(resp.read())
            if isinstance(data, dict) and "total_score" in data:
                return data
    except Exception:
        pass
    return None


def build_stats_block(apps: list[dict], plugins: list[dict], endpoints: int) -> str:
    total_apps = len(apps)
    plugin_count = len(plugins)
    cap_count = len(CAPABILITIES)

    audit = fetch_integrity_audit()
    if audit is None:
        print(
            "  note: integrity audit unreachable (daemon offline?) — score badge omitted",
            file=sys.stderr,
        )

    pct = audit.get("pct", 0) if audit else None

    metric_parts = [f"{total_apps} Apps"]
    if pct is not None:
        metric_parts.append(f"{pct}% Integrity")
    metric_parts += [f"{cap_count} Capabilities", f"{plugin_count} Plugins"]
    metric_line = "<!-- metrics: " + " · ".join(metric_parts) + " -->"

    return metric_line + f"\n\n_Generated {date.today().isoformat()} from live system state._"


def update_architecture_counts(content: str, app_count: int) -> str:
    content = re.sub(
        r"Apps \(\d+, all first-class\)",
        f"Apps ({app_count}, all first-class)",
        content,
    )
    content = re.sub(
        r"all \d+ apps",
        f"all {app_count} apps",
        content,
    )
    return content


def main():
    parser = argparse.ArgumentParser(description="Generate EmptyOS site pages")
    parser.add_argument("--dry-run", action="store_true", help="Show changes without writing")
    parser.add_argument("--vault", type=str, help="Vault path override")
    parser.add_argument(
        "--include-personal",
        action="store_true",
        help="Scan apps/personal/ too (default: community apps only — "
        "the public site should not list machine-specific apps)",
    )
    args = parser.parse_args()

    vault = resolve_vault_path(args.vault)
    if not vault or not vault.exists():
        print(f"ERROR: vault path not found: {vault}", file=sys.stderr)
        sys.exit(1)

    site_dir = vault / "30_Resources" / "EmptyOS-Site"
    if not site_dir.exists():
        print(f"ERROR: site source dir not found: {site_dir}", file=sys.stderr)
        sys.exit(1)

    app_scan_dirs = [PROJECT_ROOT / "apps"]
    if args.include_personal:
        app_scan_dirs.append(PROJECT_ROOT / "apps" / "personal")
    apps = scan_manifests(app_scan_dirs, key="app")

    plugins = scan_manifests([PROJECT_ROOT / "plugins"], key="plugin")

    endpoints = count_endpoints()

    print(f"Scanned: {len(apps)} apps, {len(plugins)} plugins, {endpoints} endpoints")

    changes = []

    # --- apps.md (fully generated) ---
    apps_md = generate_apps_md(apps)
    apps_file = site_dir / "apps.md"
    old = apps_file.read_text(encoding="utf-8") if apps_file.exists() else ""
    if apps_md != old:
        changes.append(("apps.md", apps_md, old))

    # --- plugins.md (fully generated) ---
    plugins_md = generate_plugins_md(plugins)
    plugins_file = site_dir / "plugins.md"
    old = plugins_file.read_text(encoding="utf-8") if plugins_file.exists() else ""
    if plugins_md != old:
        changes.append(("plugins.md", plugins_md, old))

    # --- capabilities.md (new, generated) ---
    caps_md = generate_capabilities_md()
    caps_file = site_dir / "capabilities.md"
    old = caps_file.read_text(encoding="utf-8") if caps_file.exists() else ""
    if caps_md != old:
        changes.append(("capabilities.md", caps_md, old))

    # --- index.md (inject stats block) ---
    index_file = site_dir / "index.md"
    if index_file.exists():
        index_content = index_file.read_text(encoding="utf-8")
        stats_block = build_stats_block(apps, plugins, endpoints)
        if STATS_START in index_content:
            new_content = inject_stats(index_content, stats_block)
        else:
            new_content = index_content
        if new_content != index_content:
            changes.append(("index.md", new_content, index_content))

    # --- architecture.md (update app count in ASCII art) ---
    arch_file = site_dir / "architecture.md"
    if arch_file.exists():
        arch_content = arch_file.read_text(encoding="utf-8")
        new_arch = update_architecture_counts(arch_content, len(apps))
        if new_arch != arch_content:
            changes.append(("architecture.md", new_arch, arch_content))

    if not changes:
        print("No changes needed — site is up to date.")
        return

    print(f"\n{'DRY RUN — ' if args.dry_run else ''}{len(changes)} file(s) to update:")
    for name, new, old in changes:
        old_lines = len(old.splitlines()) if old else 0
        new_lines = len(new.splitlines())
        print(f"  {name}: {old_lines} -> {new_lines} lines")

    if args.dry_run:
        print("\nRe-run without --dry-run to apply.")
        return

    for name, new, _old in changes:
        target = site_dir / name
        target.write_text(new, encoding="utf-8")
        print(f"  OK {name}")

    print(f"\nDone. {len(changes)} file(s) updated in {site_dir}")
    print("Run 'POST /publish/api/build' or use the Publish app to rebuild the site.")


if __name__ == "__main__":
    main()
