"""Wrapper around the CodeBoarding CLI for the EmptyOS repo.

CodeBoarding (https://github.com/CodeBoarding/CodeBoarding) generates
interactive architecture diagrams by combining static analysis with LLM
reasoning. This wrapper routes its LLM calls through EmptyOS's `think`
capability via the ``/v1/chat/completions`` facade — so generation uses
your existing provider chain (claude-cli first via the Max subscription =
typically free, ollama fallback, openai-mini, …) instead of CodeBoarding's
default direct-OpenAI/Anthropic path.

The bridge:

    codeboarding (LiteLLM under the hood)
        ↓ POST /v1/chat/completions  ← configured in ~/.codeboarding/config.toml
        ↓ Authorization: Bearer <EmptyOS auth_token>
    EmptyOS daemon on :9000
        ↓ kernel.capability("think").execute(messages=...)
    Provider chain (claude-cli → ollama → openai-mini → …)

This wrapper writes the bridge config on first run (or repairs it if
broken) so you don't have to think about it. To use the upstream's direct
LLM access instead, run `codeboarding` by hand without this wrapper.

Output lands at `.codeboarding/` at the repo root (CodeBoarding's own
convention) and is rendered inline by the Architecture tab on /topology.

Usage:
    python scripts/run_codeboarding.py            # auto-detect full vs incremental
    python scripts/run_codeboarding.py --mode full
    python scripts/run_codeboarding.py --check    # report install + bridge state, do nothing else
    python scripts/run_codeboarding.py --setup    # (re)write the bridge config and exit

Architecture-map app integration (set when spawned from apps/architecture-map/):
    --scope {full,kernel,apps,custom}   # tag the run for the UI
    --scope-path PATH                   # absolute path codeboarding analyses
    --run-id RUN_ID                     # ID of the architecture-map app run
    --run-dir DIR                       # data/apps/architecture-map/runs/<id>/

When --run-dir is set, the wrapper writes state.json updates to that dir on
start, end, and at intervals, and points codeboarding's --output-dir at
<run-dir>/output/ so each run has its own .codeboarding/ output (no
overwrite between runs).
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
import tomllib
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
CODEBOARDING_DIR = REPO_ROOT / ".codeboarding"
CB_CONFIG_DIR = Path.home() / ".codeboarding"
CB_CONFIG_FILE = CB_CONFIG_DIR / "config.toml"

# The model name we ask CodeBoarding to send. The facade ignores it for
# provider selection (chain order decides) but echoes it back so client
# logs look right. Use the openai/ prefix so LiteLLM routes via its OpenAI
# adapter (which speaks our facade's OpenAI shape) — any other prefix
# would route to a different LiteLLM backend.
FACADE_MODEL = "openai/eos-think"
FACADE_BASE = "http://localhost:9000/v1"

INSTALL_HINT = """\
codeboarding CLI not found on PATH. Install one-time with:

    pipx install codeboarding --python python3.12

Reason for pipx (not pip): codeboarding pulls 30+ heavy deps (langchain,
duckdb, ipykernel, …) that conflict with your main Python env. pipx
isolates them per-tool.

After install, re-run this script. (No `codeboarding-setup` needed — this
wrapper writes the config pointing at EmptyOS automatically.)
"""


def _check_installed() -> str | None:
    """Return path to codeboarding binary, or None if not installed."""
    return shutil.which("codeboarding")


def _read_eos_auth_token() -> str:
    """Pull the auth_token from emptyos.toml so the bridge can authenticate."""
    cfg = REPO_ROOT / "emptyos.toml"
    if not cfg.exists():
        return ""
    try:
        data = tomllib.loads(cfg.read_text(encoding="utf-8"))
    except Exception:
        return ""
    return str((data.get("network") or {}).get("auth_token", "") or "")


def _bridge_config_text(auth_token: str) -> str:
    """Build the ~/.codeboarding/config.toml body that routes LiteLLM through
    EmptyOS's /v1 facade. Format follows CodeBoarding's own config schema —
    LiteLLM accepts `api_base` to redirect OpenAI-shaped calls to a custom
    endpoint."""
    return f"""# Auto-generated by emptyos/scripts/run_codeboarding.py
# Routes CodeBoarding's LLM calls through EmptyOS's /v1 facade so the
# think provider chain (claude-cli first, etc.) handles the work.
# Hand-edit if you want to bypass EmptyOS and hit OpenAI/Anthropic direct.

[llm]
agent_model = "{FACADE_MODEL}"
parsing_model = "{FACADE_MODEL}"

[providers.openai]
api_key = "{auth_token}"
api_base = "{FACADE_BASE}"
"""


def _ensure_bridge_config(force: bool = False) -> tuple[bool, str]:
    """Write the bridge config if missing or if --force.

    Returns (was_written, message).
    """
    auth_token = _read_eos_auth_token()
    if not auth_token:
        return (
            False,
            "[warn] emptyos.toml has no [network] auth_token — bridge config NOT written. "
            "Either set one or hand-configure ~/.codeboarding/config.toml.",
        )

    if CB_CONFIG_FILE.exists() and not force:
        # Check it actually points at our facade — if a stale install-time
        # config exists, we still warn the user but don't overwrite (their
        # choice).
        try:
            existing = tomllib.loads(CB_CONFIG_FILE.read_text(encoding="utf-8"))
        except Exception:
            existing = {}
        api_base = (
            (existing.get("providers") or {}).get("openai") or {}
        ).get("api_base", "")
        if api_base == FACADE_BASE:
            return (False, f"[ok] bridge config already in place at {CB_CONFIG_FILE}")
        return (
            False,
            f"[warn] {CB_CONFIG_FILE} exists but points at {api_base or '<unknown>'} "
            f"(not the EmptyOS facade). Run with --setup to overwrite.",
        )

    CB_CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    CB_CONFIG_FILE.write_text(_bridge_config_text(auth_token), encoding="utf-8")
    return (True, f"[ok] bridge config written to {CB_CONFIG_FILE}")


def _facade_reachable() -> tuple[bool, str]:
    """Best-effort probe — confirm /v1/models responds before kicking off a
    long generation. Stdlib-only so the wrapper doesn't drag in requests."""
    auth_token = _read_eos_auth_token()
    if not auth_token:
        return (False, "no auth_token in emptyos.toml")
    import urllib.error
    import urllib.request

    req = urllib.request.Request(
        f"{FACADE_BASE}/models",
        headers={"Authorization": f"Bearer {auth_token}"},
    )
    try:
        with urllib.request.urlopen(req, timeout=5) as resp:
            if resp.status == 200:
                return (True, f"facade reachable at {FACADE_BASE}")
            return (False, f"facade returned HTTP {resp.status}")
    except urllib.error.HTTPError as e:
        return (False, f"facade returned HTTP {e.code}")
    except urllib.error.URLError as e:
        return (False, f"facade unreachable: {e.reason}")
    except Exception as e:  # noqa: BLE001
        return (False, f"facade probe failed: {e!r}")


def _detect_mode() -> str:
    """Pick `full` on cold start, `incremental` once a real analysis exists.

    Check for `.codeboarding/overview.md` specifically — codeboarding creates
    the `.codeboarding/` directory itself during setup/cache init even when
    no analysis has been produced, so directory existence alone is not a
    reliable signal of "has prior analysis".
    """
    return "incremental" if (CODEBOARDING_DIR / "overview.md").exists() else "full"


def _update_state(run_dir: Path | None, **fields) -> None:
    """Merge fields into run-dir/state.json. Quiet no-op when run_dir is None."""
    if run_dir is None:
        return
    state_path = run_dir / "state.json"
    try:
        existing = json.loads(state_path.read_text(encoding="utf-8")) if state_path.exists() else {}
    except Exception:
        existing = {}
    existing.update(fields)
    try:
        state_path.write_text(json.dumps(existing, indent=2, sort_keys=True), encoding="utf-8")
    except Exception:
        pass


def main() -> int:
    parser = argparse.ArgumentParser(description="Run CodeBoarding against the EmptyOS repo.")
    parser.add_argument(
        "--mode",
        choices=("full", "incremental", "auto"),
        default="auto",
        help="full = re-analyze everything; incremental = only changed; auto = detect",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Report install + bridge state and exit; do not run the CLI",
    )
    parser.add_argument(
        "--setup",
        action="store_true",
        help="(Re)write the bridge config pointing at EmptyOS's /v1 facade and exit",
    )
    parser.add_argument(
        "--force-config",
        action="store_true",
        help="Overwrite an existing ~/.codeboarding/config.toml even if it looks valid",
    )
    # Architecture-app integration knobs (optional; standalone use ignores them).
    parser.add_argument("--scope", default="", help="Scope tag for the architecture app")
    parser.add_argument(
        "--scope-path",
        default="",
        help="Absolute path to analyse (overrides REPO_ROOT when set)",
    )
    parser.add_argument("--run-id", default="", help="Run ID set by the architecture app")
    parser.add_argument(
        "--run-dir",
        default="",
        help="Directory under data/apps/architecture-map/runs/<id>/ for state + output",
    )
    args = parser.parse_args()

    if args.setup:
        written, msg = _ensure_bridge_config(force=args.force_config)
        print(msg)
        return 0 if written or "[ok]" in msg else 1

    bin_path = _check_installed()
    if args.check:
        # Report all three states: install, bridge, facade.
        if bin_path:
            print(f"[ok] codeboarding installed at {bin_path}")
            print(
                f"[ok] output dir: {CODEBOARDING_DIR} "
                f"({'exists' if CODEBOARDING_DIR.exists() else 'will be created on first run'})"
            )
        else:
            print("[not installed]")
            print(INSTALL_HINT)

        # Bridge config state (doesn't require codeboarding installed)
        if CB_CONFIG_FILE.exists():
            try:
                d = tomllib.loads(CB_CONFIG_FILE.read_text(encoding="utf-8"))
                api_base = ((d.get("providers") or {}).get("openai") or {}).get("api_base", "")
                if api_base == FACADE_BASE:
                    print(f"[ok] bridge config points at EmptyOS facade ({FACADE_BASE})")
                else:
                    print(f"[warn] bridge config points at {api_base or '<unknown>'} — run --setup to fix")
            except Exception as e:
                print(f"[warn] {CB_CONFIG_FILE} present but unreadable: {e}")
        else:
            print(f"[absent] bridge config not yet written — first run will create it")

        # Facade reachability
        ok, msg = _facade_reachable()
        print(f"[{'ok' if ok else 'warn'}] {msg}")

        return 0 if bin_path else 1

    if not bin_path:
        print(INSTALL_HINT, file=sys.stderr)
        return 1

    # Ensure bridge config is set up before running.
    written, msg = _ensure_bridge_config()
    print(msg)
    if "[warn]" in msg and "exists but points at" in msg:
        print("       Aborting. Run with --setup --force-config to overwrite.", file=sys.stderr)
        return 1

    # Probe the facade — long generation against a dead daemon wastes the run.
    ok, fmsg = _facade_reachable()
    if not ok:
        print(f"[error] {fmsg}", file=sys.stderr)
        print(
            "        Start EmptyOS first (restart.bat) — bridge needs :9000 reachable.",
            file=sys.stderr,
        )
        return 1
    print(f"[ok] {fmsg}")

    mode = _detect_mode() if args.mode == "auto" else args.mode

    # Architecture-app integration: per-run output dir + state tracking.
    run_dir = Path(args.run_dir).resolve() if args.run_dir else None
    target_path = Path(args.scope_path).resolve() if args.scope_path else REPO_ROOT
    if run_dir:
        output_dir = run_dir / "output"
        output_dir.mkdir(parents=True, exist_ok=True)
    else:
        output_dir = None

    print()
    print(f"[run] codeboarding {mode} --local {target_path}")
    if output_dir:
        print(f"[run] --output-dir {output_dir}")
    if args.run_id:
        print(f"[run] architecture-app run id: {args.run_id}")
    print(f"[note] LLM calls route through {FACADE_BASE} → EmptyOS think chain")
    print(f"[note] cost depends on which provider in the chain handles each call")
    print()

    cmd = [bin_path, mode, "--local", str(target_path)]
    if output_dir:
        cmd += ["--output-dir", str(output_dir)]
    # Make sure the subprocess can't accidentally pick up a different OpenAI
    # key from the env (which would bypass the bridge).
    env = dict(os.environ)
    auth_token = _read_eos_auth_token()
    if auth_token:
        env["OPENAI_API_KEY"] = auth_token
        env["OPENAI_API_BASE"] = FACADE_BASE
        env["OPENAI_BASE_URL"] = FACADE_BASE  # LiteLLM honors both names
    # Force UTF-8 mode for the entire codeboarding subprocess tree.
    # CodeBoarding's static_analyzer/scanner.py calls subprocess.run(text=True)
    # without encoding=, so on Windows it decodes tokei's JSON output via
    # cp1252 — which crashes on the first byte >0x7F. PYTHONUTF8=1 flips
    # Python's I/O default to UTF-8 everywhere in that subprocess tree.
    # See .claude/rules/environment.md (the cp1252 trap).
    env["PYTHONUTF8"] = "1"
    env["PYTHONIOENCODING"] = "utf-8"

    start_ts = datetime.now(timezone.utc)
    try:
        result = subprocess.run(cmd, cwd=str(REPO_ROOT), env=env, check=False)
    except KeyboardInterrupt:
        print("\n[interrupted] codeboarding run cancelled", file=sys.stderr)
        _finalize_state(run_dir, "cancelled", 130, start_ts)
        return 130

    end_ts = datetime.now(timezone.utc)

    if result.returncode != 0:
        print(f"[error] codeboarding exited {result.returncode}", file=sys.stderr)
        _finalize_state(run_dir, "failed", result.returncode, start_ts, end_ts)
        return result.returncode

    # Primary success signal is analysis.json (codeboarding's structured
    # output). overview.md is only produced when codeboarding renders its own
    # markdown self-docs — `--output-dir` runs emit JSON, which our app
    # renders into HTML at view time.
    analysis = (output_dir / "analysis.json") if output_dir else (CODEBOARDING_DIR / "analysis.json")
    overview = (output_dir / ".codeboarding" / "overview.md") if output_dir else (CODEBOARDING_DIR / "overview.md")
    if analysis.exists() or overview.exists():
        print()
        produced = overview if overview.exists() else analysis
        print(f"[ok] output written: {produced}")
        if args.run_id:
            print(f"[ok] view in browser: http://localhost:9000/architecture-map/?run={args.run_id}")
        else:
            print(f"[ok] view in browser: http://localhost:9000/architecture-map/")
        _finalize_state(run_dir, "completed", 0, start_ts, end_ts)
    else:
        print(f"[warn] codeboarding succeeded but neither analysis.json nor overview.md found", file=sys.stderr)
        _finalize_state(run_dir, "failed", 1, start_ts, end_ts)
        return 1
    return 0


def _finalize_state(
    run_dir: Path | None,
    status: str,
    exit_code: int,
    start_ts: datetime,
    end_ts: datetime | None = None,
) -> None:
    """Write the terminal state for an architecture-app-spawned run."""
    if run_dir is None:
        return
    end_ts = end_ts or datetime.now(timezone.utc)
    _update_state(
        run_dir,
        status=status,
        exit_code=exit_code,
        ended_at=end_ts.isoformat(),
        duration_s=(end_ts - start_ts).total_seconds(),
    )


if __name__ == "__main__":
    sys.exit(main())
