#!/usr/bin/env python3
"""Apply a browser-captured conversation-ingest batch.

The capture JSON is generated by an authenticated browser session. A separate
human/agent-authored spec supplies the fact-checked digest and 15-domain scan.
This runner builds the immutable source, proves the prospective evidence graph,
then writes source -> digest -> derived notes -> ledger through the EmptyOS
Vault API with readback after every operation.
"""

from __future__ import annotations

import argparse
import hashlib
import importlib.util
import json
import re
import sys
import tomllib
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path
from typing import Any, Callable


SCRIPT_DIR = Path(__file__).resolve().parent
REPO = SCRIPT_DIR.parents[3]
CONFIG = REPO / "emptyos.toml"

LEDGER_PATH = "30_Resources/conversations/ai-conversation-ingestion-ledger.md"
DOMAIN_LABELS = (
    "Personal chronology",
    "Emotional and health",
    "People and relationships",
    "Work and career",
    "Projects and execution",
    "Tasks and commitments",
    "Knowledge fragments",
    "Calculations and engineering",
    "Tools, code, and calculators",
    "Finance and assets",
    "Legal, immigration, and administration",
    "Media and creative work",
    "Preferences and operating principles",
    "Open questions and contradictions",
    "Transient/no durable delta",
)
VALID_STATUSES = {
    "delta",
    "mentioned-no-delta",
    "not-present",
    "needs-review",
}
SECRET_PATTERNS = (
    ("Google API key", re.compile(r"AIza[0-9A-Za-z_-]{30,}")),
    ("OpenAI API key", re.compile(r"sk-(?!ant-)(?:proj-)?[A-Za-z0-9_-]{20,}")),
    ("Anthropic API key", re.compile(r"sk-ant-[A-Za-z0-9_-]{20,}")),
    ("GitHub token", re.compile(r"gh[pousr]_[A-Za-z0-9]{30,}")),
    ("AWS access key", re.compile(r"AKIA[0-9A-Z]{16}")),
    ("Slack token", re.compile(r"xox[abpr]-[A-Za-z0-9-]{10,}")),
    (
        "JWT",
        re.compile(
            r"eyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}"
        ),
    ),
    (
        "Bearer token",
        re.compile(r"(?i)authorization:\s*bearer\s+[A-Za-z0-9._-]{20,}"),
    ),
)


def redact_secrets(text: str) -> tuple[str, set[str]]:
    """Remove credential-shaped values before an immutable source reaches Vault."""
    result = text
    findings: set[str] = set()
    for name, pattern in SECRET_PATTERNS:
        result, count = pattern.subn(f"[REDACTED {name}]", result)
        if count:
            findings.add(name)
    return result, findings


def load_module(name: str, path: Path) -> Any:
    spec = importlib.util.spec_from_file_location(name, path)
    if not spec or not spec.loader:
        raise RuntimeError(f"Cannot load {path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


AUDIT = load_module("conversation_evidence_audit", SCRIPT_DIR / "audit_evidence_graph.py")
QUEUE = AUDIT.load_queue_helper()


# The agent-cli envelope (.claude/rules/agent-cli.md). These runners are driven
# by an agent, never typed by a human, so the envelope is emitted always rather
# than behind --json — there is no human mode to be the default.
if str(REPO / "scripts") not in sys.path:
    sys.path.insert(0, str(REPO / "scripts"))
from scanner_lib import emit_json  # noqa: E402


class ApplyRefused(Exception):
    """A refusal that carries its evidence as data, not as a message string.

    Refusals used to be `raise RuntimeError(json.dumps(evidence))`, uncaught by
    main(). The exit code was right but stdout was empty and stderr held a
    traceback with JSON embedded mid-message, so an agent consumer doing
    `json.loads(stdout)` could not read *why* it was refused — the one thing it
    needed. The payload rides here and lands under the envelope's `data`.
    """

    def __init__(self, message: str, payload: Any = None) -> None:
        super().__init__(message)
        self.payload = payload


def run_cli(build_receipts: Callable[[], list], *, noun: str = "receipts") -> int:
    """Run a batch and emit exactly one envelope on stdout, success or failure."""
    try:
        receipts = build_receipts()
    except ApplyRefused as exc:
        return emit_json(False, "refused", str(exc), exc.payload)
    except (ValueError, KeyError, FileNotFoundError) as exc:
        return emit_json(False, "invalid_input", f"{type(exc).__name__}: {exc}")
    except (urllib.error.URLError, urllib.error.HTTPError, OSError) as exc:
        return emit_json(False, "daemon_unreachable", f"{type(exc).__name__}: {exc}")
    return emit_json(True, "ok", f"{len(receipts)} {noun}", {"receipts": receipts})


def connection(config_path: Path = CONFIG) -> tuple[str, dict[str, str]]:
    with config_path.open("rb") as handle:
        config = tomllib.load(handle)
    network = config.get("network", {})
    host = str(network.get("host", "127.0.0.1"))
    if host in {"0.0.0.0", "::"}:
        host = "127.0.0.1"
    port = int(network.get("port", 9000))
    token = str(network.get("auth_token", ""))
    headers = {"Authorization": f"Bearer {token}"} if token else {}
    return f"http://{host}:{port}", headers


def api_read(base_url: str, headers: dict[str, str], path: str) -> str | None:
    url = f"{base_url}/api/vault/read?" + urllib.parse.urlencode({"path": path})
    request = urllib.request.Request(url, headers=headers)
    try:
        with urllib.request.urlopen(request, timeout=30) as response:
            return str(json.load(response)["content"])
    except urllib.error.HTTPError as error:
        if error.code == 404:
            return None
        raise


def api_write(
    base_url: str, headers: dict[str, str], path: str, content: str
) -> None:
    request = urllib.request.Request(
        f"{base_url}/api/vault/write",
        data=json.dumps({"path": path, "content": content}).encode("utf-8"),
        method="POST",
        headers={**headers, "Content-Type": "application/json"},
    )
    with urllib.request.urlopen(request, timeout=30) as response:
        result = json.load(response)
    if not result.get("ok"):
        raise RuntimeError(f"Vault write failed for {path}: {result}")


def write_exact(
    base_url: str, headers: dict[str, str], path: str, content: str
) -> str:
    current = api_read(base_url, headers, path)
    if current is None:
        api_write(base_url, headers, path, content)
        if api_read(base_url, headers, path) != content:
            raise RuntimeError(f"Readback mismatch for {path}")
        return "written"
    if current != content:
        raise RuntimeError(f"Unexpected existing content at {path}")
    return "reused"


def write_update_exact(
    base_url: str,
    headers: dict[str, str],
    path: str,
    before: str | None,
    after: str,
) -> str:
    current = api_read(base_url, headers, path)
    if current == after:
        return "reused"
    if current != before:
        raise RuntimeError(f"Concurrent or unexpected change at {path}")
    api_write(base_url, headers, path, after)
    if api_read(base_url, headers, path) != after:
        raise RuntimeError(f"Readback mismatch for {path}")
    return "written" if before is None else "updated"


def yaml_quote(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def source_body(item: dict[str, Any], spec: dict[str, Any]) -> str:
    messages = item.get("messages") or []
    safe_messages: list[tuple[dict[str, Any], str]] = []
    redacted: set[str] = set()
    for message in messages:
        safe_text, findings = redact_secrets(str(message.get("text") or ""))
        safe_messages.append((message, safe_text))
        redacted.update(findings)

    lines = [
        f"# {spec['title']}",
        "",
        "> Source capture. Message wording is preserved; provider UI chrome is omitted.",
    ]
    note = str(spec.get("capture_note") or "").strip()
    if note:
        lines.extend(["", f"> Capture limitation: {note}"])
    if redacted:
        labels = ", ".join(sorted(redacted))
        lines.extend(
            [
                "",
                f"> Security redaction: credential-shaped value(s) removed ({labels}).",
            ]
        )
    lines.extend(["", "## Messages", ""])
    for ordinal, (message, text) in enumerate(safe_messages, 1):
        role = "User" if message.get("role") == "user" else "Gemini"
        lines.append(f"### {ordinal:03d} · {role}")
        lines.append("")
        if text:
            lines.append(text)
        else:
            lines.append(
                "> No rendered text was available in the provider DOM for this turn."
            )
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def note_paths(spec: dict[str, Any], provider_id: str) -> tuple[str, str]:
    date = str(spec["ingestion_date"])
    slug = str(spec["slug"])
    short_id = provider_id[:8]
    private = bool(spec.get("private"))
    source_root = (
        "40_Archive/AI Conversations/originals/gemini"
        if private
        else "30_Resources/conversations/originals/gemini"
    )
    source = f"{source_root}/{date}-{slug}--{short_id}.md"
    digest = f"30_Resources/conversations/{date}-{slug}.md"
    return source, digest


def source_markdown(
    item: dict[str, Any], spec: dict[str, Any], provider_id: str
) -> tuple[str, str, str]:
    source_path, digest_path = note_paths(spec, provider_id)
    body = source_body(item, spec)
    body_hash = hashlib.sha256(body.encode("utf-8")).hexdigest()
    fidelity = str(spec.get("capture_fidelity") or "verbatim-text")
    raw_status = "partial" if fidelity == "partial" else "complete"
    tags = [
        "conversation",
        "conversation-source",
        "gemini",
        *[str(tag) for tag in spec.get("tags") or []],
    ]
    if spec.get("private") and "private" not in tags:
        tags.append("private")
    tag_lines = "\n".join(f"  - {tag}" for tag in dict.fromkeys(tags))
    source = f"""---
record_kind: conversation-source
archive_schema: eos-ai-conversation-v1
author: both
provider: gemini
source_conversation_id: {provider_id}
source_url: https://gemini.google.com/app/{provider_id}
title: {yaml_quote(str(spec['title']))}
conversation_started: unknown
conversation_ended: unknown
provider_list_date: {spec.get('provider_list_date', 'unknown')}
captured_at: {spec['captured_at']}
capture_method: browser-rendered-dom
capture_fidelity: {fidelity}
raw_status: {raw_status}
message_count: {len(item.get('messages') or [])}
content_sha256: {body_hash}
tags:
{tag_lines}
related:
  - "[[{digest_path.removesuffix('.md')}]]"
---

{body}"""
    return source_path, digest_path, source


def coverage_table(spec: dict[str, Any]) -> str:
    coverage = spec.get("domain_coverage")
    if not isinstance(coverage, dict):
        raise ValueError("domain_coverage must be an object")
    default_row = coverage.get("*")
    if default_row is not None and not isinstance(default_row, dict):
        raise ValueError("domain_coverage '*' default must be an object")
    lines = ["| Domain | Status | Notes |", "|---|---|---|"]
    for domain in DOMAIN_LABELS:
        row = coverage.get(domain, default_row)
        if not isinstance(row, dict):
            raise ValueError(f"Missing domain coverage: {domain}")
        status = str(row.get("status") or "")
        if status not in VALID_STATUSES:
            raise ValueError(f"Invalid status for {domain}: {status}")
        note = str(row.get("notes") or "-").replace("|", "\\|")
        lines.append(f"| {domain} | {status} | {note} |")
    return "\n".join(lines)


def bullet_list(values: list[str], *, empty: str) -> str:
    return "\n".join(f"- {value}" for value in values) if values else f"- {empty}"


def routing_table(
    spec: dict[str, Any], digest_path: str, derived_paths: list[str]
) -> str:
    rows = spec.get("delta_dispositions") or []
    if not rows:
        if derived_paths:
            return (
                "The listed living Vault note mutations were completed through "
                "the Vault API and are linked in the evidence chain below."
            )
        return (
            "No non-transient durable delta was found. The source is preserved "
            "for provenance; no living Vault note should be mutated."
        )
    lines = [
        "| Domain | Disposition | Target | Reason | Routing evidence |",
        "|---|---|---|---|---|",
    ]
    for row in rows:
        domain = str(row["domain"])
        disposition = str(row.get("disposition") or "digest-contained")
        reason = str(row["reason"]).replace("|", "\\|")
        target = str(
            row.get("target")
            or f"[[{digest_path.removesuffix('.md')}]]"
        )
        routing_evidence = str(row.get("routing_evidence") or "-").replace(
            "|", "\\|"
        )
        lines.append(
            f"| {domain} | {disposition} | {target} | {reason} | "
            f"{routing_evidence} |"
        )
    if derived_paths:
        lines.extend(
            [
                "",
                "The listed living Vault note mutations were completed through "
                "the Vault API and are linked in the evidence chain below.",
            ]
        )
    else:
        lines.extend(
            [
                "",
                "No living Vault note was changed. This is an explicit routing "
                "decision, not a missing Vault operation.",
            ]
        )
    return "\n".join(lines)


def digest_markdown(
    spec: dict[str, Any],
    provider_id: str,
    source_path: str,
    digest_path: str,
    message_count: int,
) -> str:
    tags = ["conversation", *[str(tag) for tag in spec.get("tags") or []]]
    tag_lines = "\n".join(f"  - {tag}" for tag in dict.fromkeys(tags))
    source_url = f"https://gemini.google.com/app/{provider_id}"
    fidelity = str(spec.get("capture_fidelity") or "verbatim-text")
    derived_paths = [
        str(row["path"]) for row in spec.get("derived_mutations") or []
    ]
    derived_frontmatter = (
        "\n"
        + "\n".join(
            f'  - "[[{path.removesuffix(".md")}]]"' for path in derived_paths
        )
        if derived_paths
        else "[]"
    )
    derived_evidence = (
        "\n".join(
            f"- [[{path.removesuffix('.md')}]]" for path in derived_paths
        )
        if derived_paths
        else "- none; durable deltas, if any, are explicitly dispositioned."
    )
    return f"""---
record_kind: conversation-digest
author: ai
provider: gemini
source_conversation_id: {provider_id}
source_url: {source_url}
title: {yaml_quote(str(spec['title']))}
created: {spec['ingestion_date']}
status: audited-complete
tags:
{tag_lines}
source_archive: "[[{source_path.removesuffix('.md')}]]"
derived_notes: {derived_frontmatter}
related:
  - "[[ai-conversation-ingestion-ledger]]"
---

## Digest

{str(spec['digest']).strip()}

## Domain coverage

{coverage_table(spec)}

## Decisions and durable deltas

{bullet_list([str(v) for v in spec.get('decisions') or []], empty='No durable decision.')}

## Fact-check notes

{bullet_list([str(v) for v in spec.get('fact_checks') or []], empty='No external factual claim required verification; capture limitations are stated explicitly.')}

## Routing

{routing_table(spec, digest_path, derived_paths)}

## Evidence chain

- Provider conversation: {source_url}
- Immutable source: [[{source_path.removesuffix('.md')}]]
- This digest: [[{digest_path.removesuffix('.md')}]]
- Derived notes:
{derived_evidence}
- Completion receipt: [[{LEDGER_PATH.removesuffix('.md')}]]

## Source

- Archived original: [[{source_path.removesuffix('.md')}]]
- Provider ID: `{provider_id}`
- Capture: `{fidelity}`, {message_count} messages.
- Gemini list displayed `{spec.get('provider_list_label', 'unknown')}`; no exact
  provider timestamp was exposed, so the filename uses the ingestion date and
  the displayed date is preserved in source frontmatter.
"""


def check_derived_path(path: str, *, provider_id: str) -> None:
    """Refuse a derived-note path that would invent a folder from a title.

    Source and digest paths are slugified before use; a derived path is
    hand-authored in the reviewed spec and reached the Vault API unvalidated.
    A note titled "Import/export and mutation transaction contract" was written
    verbatim into a path literal, so `/api/vault/write` did exactly what it was
    asked and created an `Import/` directory holding one file — inside a folder
    of fifty flat siblings. The route is not at fault; nothing upstream ever
    said the segment was a title rather than a directory.

    Note this cannot use `require_path_segment` from emptyos.sdk.utils: that
    regex forbids spaces, and every note in these folders has spaces in its
    filename. It is a traversal guard for slug-shaped ids, not a title
    sanitiser.
    """
    if not path.endswith(".md"):
        raise ValueError(
            f"Derived mutation path for {provider_id} must end in .md: {path!r}"
        )
    if path.startswith("/") or ".." in Path(path).parts:
        raise ValueError(f"Derived mutation path escapes the Vault: {path!r}")
    # Deliberately NOT checking that the parent folder already exists, though
    # that is the check which would have caught the `Import/` phantom: it needs
    # the vault filesystem, and a script joining a vault-relative path to a
    # local root is precisely the coupling that created the bug. Measured
    # against the 192 real derived paths on disk, all 192 parents exist and 5
    # top-level folders would have been wrongly refused by an allowlist. The
    # durable fix is the authoring rule in SKILL.md, not a gate here.


def render_derived_content(
    template: str,
    *,
    provider_id: str,
    source_path: str,
    digest_path: str,
    ingestion_date: str,
) -> str:
    replacements = {
        "{provider_id}": provider_id,
        "{source_path}": source_path,
        "{source_link}": f"[[{source_path.removesuffix('.md')}]]",
        "{digest_path}": digest_path,
        "{digest_link}": f"[[{digest_path.removesuffix('.md')}]]",
        "{ingestion_date}": ingestion_date,
    }
    result = template
    for token, value in replacements.items():
        result = result.replace(token, value)
    return result.rstrip() + "\n"


def plan_derived_mutations(
    *,
    base_url: str,
    headers: dict[str, str],
    spec: dict[str, Any],
    provider_id: str,
    source_path: str,
    digest_path: str,
) -> list[dict[str, Any]]:
    plans: list[dict[str, Any]] = []
    seen: set[str] = set()
    for row in spec.get("derived_mutations") or []:
        path = str(row["path"])
        if path in seen:
            raise ValueError(f"Duplicate derived mutation path for {provider_id}: {path}")
        seen.add(path)
        check_derived_path(path, provider_id=provider_id)
        mode = str(row.get("mode") or "append")
        rendered = render_derived_content(
            str(row["content"]),
            provider_id=provider_id,
            source_path=source_path,
            digest_path=digest_path,
            ingestion_date=str(spec["ingestion_date"]),
        )
        before = api_read(base_url, headers, path)
        marker = str(row.get("marker") or provider_id)
        if mode == "create":
            if before is None:
                after = rendered
            elif before == rendered:
                after = before
            elif (
                before.startswith(rendered.rstrip() + "\n\n")
                and row.get("allow_appended_markers")
                and all(
                    str(appended_marker) in before
                    for appended_marker in row["allow_appended_markers"]
                )
            ):
                after = before
            else:
                raise RuntimeError(f"Unexpected existing content at {path}")
        elif mode == "append":
            if before is None:
                raise RuntimeError(f"Cannot append to missing derived note: {path}")
            if marker in before:
                after = before
            else:
                after = before.rstrip() + "\n\n" + rendered
        elif mode == "replace-exact":
            if before is None:
                raise RuntimeError(
                    f"Cannot replace content in missing derived note: {path}"
                )
            match_template = row.get("match")
            if not isinstance(match_template, str) or not match_template:
                raise ValueError(
                    f"replace-exact mutation requires non-empty match: {path}"
                )
            match = render_derived_content(
                match_template,
                provider_id=provider_id,
                source_path=source_path,
                digest_path=digest_path,
                ingestion_date=str(spec["ingestion_date"]),
            ).rstrip("\n")
            replacement = rendered.rstrip("\n")
            occurrences = before.count(match)
            if occurrences == 1:
                after = before.replace(match, replacement, 1)
            elif occurrences == 0 and marker in before and replacement in before:
                after = before
            elif occurrences == 0:
                raise RuntimeError(
                    f"replace-exact match not found at {path}"
                )
            else:
                raise RuntimeError(
                    f"replace-exact match is not unique at {path}: {occurrences}"
                )
        else:
            raise ValueError(f"Unsupported derived mutation mode: {mode}")
        plans.append(
            {
                "path": path,
                "before": before,
                "after": after,
                "backup_path": row.get("backup_path"),
            }
        )
    return plans


def final_ledger_row(
    item: dict[str, Any],
    spec: dict[str, Any],
    provider_id: str,
    source_path: str,
    digest_path: str,
) -> str:
    status = "partial" if spec.get("capture_fidelity") == "partial" else "complete"
    summary = str(spec.get("ledger_summary") or "browser capture fact-checked")
    return (
        f"- {spec['ingestion_date']} · gemini-older · {provider_id} · "
        f"{spec['title']} · archived source + digest · {status} · "
        f"{len(item.get('messages') or [])} messages · "
        f"[[{source_path.removesuffix('.md')}|source]] · "
        f"[[{digest_path.removesuffix('.md')}|digest]] · {summary}"
    )


def ledger_after(current: str, provider_id: str, final_row: str) -> tuple[str, str]:
    matching = [line for line in current.splitlines() if provider_id in line]
    if not matching:
        return current.rstrip() + "\n\n" + final_row + "\n", "appended"
    if matching == [final_row]:
        return current, "reused"
    raise RuntimeError(f"Conflicting ledger receipt for {provider_id}: {matching}")


def prospective_reader(
    base_reader: Callable[[str], str | None],
    overlays: dict[str, str],
) -> Callable[[str], str]:
    def read(path: str) -> str:
        if path in overlays:
            return overlays[path]
        value = base_reader(path)
        if value is None:
            raise urllib.error.HTTPError(path, 404, "", None, None)
        return value

    return read


def apply_item(
    *,
    base_url: str,
    headers: dict[str, str],
    item: dict[str, Any],
    spec: dict[str, Any],
) -> dict[str, Any]:
    provider_id = str(item["url"]).rstrip("/").rsplit("/", 1)[-1]
    if provider_id != str(spec["provider_id"]):
        raise ValueError(f"Provider ID mismatch: {provider_id}")
    if str(spec["title"]) not in str(item.get("label") or ""):
        raise ValueError(f"Title/list-label mismatch for {provider_id}")

    source_path, digest_path, source = source_markdown(item, spec, provider_id)
    derived_plans = plan_derived_mutations(
        base_url=base_url,
        headers=headers,
        spec=spec,
        provider_id=provider_id,
        source_path=source_path,
        digest_path=digest_path,
    )
    digest = digest_markdown(
        spec, provider_id, source_path, digest_path, len(item.get("messages") or [])
    )
    checks = AUDIT.source_checks(source, provider_id)
    if not all(checks.values()):
        raise RuntimeError(f"Source contract failed for {provider_id}: {checks}")

    current_ledger = api_read(base_url, headers, LEDGER_PATH)
    if current_ledger is None:
        raise RuntimeError("Ingestion ledger missing")
    row = final_ledger_row(
        item, spec, provider_id, source_path, digest_path
    )
    next_ledger, ledger_status = ledger_after(current_ledger, provider_id, row)
    index = AUDIT.ledger_note_candidates(next_ledger, QUEUE)
    overlays = {
        source_path: source,
        digest_path: digest,
        LEDGER_PATH: next_ledger,
        **{row["path"]: row["after"] for row in derived_plans},
    }
    reader = prospective_reader(
        lambda path: api_read(base_url, headers, path),
        overlays,
    )
    evidence = AUDIT.audit_item(
        {
            "provider_id": provider_id,
            "title": spec["title"],
            "created_at": f"{spec['ingestion_date']}T00:00:00+10:00",
            "message_count": len(item.get("messages") or []),
        },
        reader,
        QUEUE,
        ledger_paths=index.get(provider_id),
        ledger_entry_present=provider_id in index,
    )
    if not evidence["new_schema_complete"]:
        raise ApplyRefused("prospective evidence graph is not clean", evidence)

    backup_receipts = []
    for plan in derived_plans:
        backup_path = plan.get("backup_path")
        if not backup_path:
            continue
        if plan["before"] != plan["after"]:
            if plan["before"] is None:
                raise RuntimeError(
                    f"Backup requested for newly created note: {plan['path']}"
                )
            status = write_exact(
                base_url, headers, str(backup_path), str(plan["before"])
            )
        else:
            if api_read(base_url, headers, str(backup_path)) is None:
                raise RuntimeError(f"Expected backup is missing: {backup_path}")
            status = "reused"
        backup_receipts.append({"path": str(backup_path), "status": status})

    source_status = write_exact(base_url, headers, source_path, source)
    digest_status = write_exact(base_url, headers, digest_path, digest)
    derived_receipts = []
    for plan in derived_plans:
        status = write_update_exact(
            base_url,
            headers,
            str(plan["path"]),
            plan["before"],
            str(plan["after"]),
        )
        derived_receipts.append({"path": str(plan["path"]), "status": status})
    if next_ledger != current_ledger:
        api_write(base_url, headers, LEDGER_PATH, next_ledger)
    if api_read(base_url, headers, LEDGER_PATH) != next_ledger:
        raise RuntimeError(f"Ledger readback failed for {provider_id}")
    return {
        "provider_id": provider_id,
        "source": source_status,
        "digest": digest_status,
        "derived": derived_receipts or "none-digest-contained",
        "ledger": ledger_status,
        "new_schema_complete": True,
        "source_path": source_path,
        "digest_path": digest_path,
        "backups": backup_receipts,
    }


def load_inputs(capture_path: Path, spec_path: Path) -> tuple[list[Any], dict[str, Any]]:
    capture = json.loads(capture_path.read_text(encoding="utf-8-sig"))
    specs = json.loads(spec_path.read_text(encoding="utf-8-sig"))
    items = capture.get("items")
    rows = specs.get("items")
    if not isinstance(items, list) or not isinstance(rows, list):
        raise ValueError("Both input files need an items array")
    by_id = {str(row["provider_id"]): row for row in rows}
    return items, by_id


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--capture", type=Path, required=True)
    parser.add_argument("--spec", type=Path, required=True)
    parser.add_argument("--config", type=Path, default=CONFIG)
    parser.add_argument(
        "--provider-id",
        action="append",
        dest="provider_ids",
        help="Process only this provider ID; repeat for more than one.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()

    def build() -> list:
        return _collect_receipts(args)

    return run_cli(build)


def _collect_receipts(args: argparse.Namespace) -> list:
    capture_items, specs = load_inputs(args.capture, args.spec)
    if args.provider_ids:
        selected = set(args.provider_ids)
        capture_items = [
            item
            for item in capture_items
            if str(item["url"]).rstrip("/").rsplit("/", 1)[-1] in selected
        ]
        found = {
            str(item["url"]).rstrip("/").rsplit("/", 1)[-1]
            for item in capture_items
        }
        missing = selected - found
        if missing:
            raise ValueError(f"Provider IDs not found in capture: {sorted(missing)}")
    base_url, headers = connection(args.config)
    receipts = []
    for item in capture_items:
        provider_id = str(item["url"]).rstrip("/").rsplit("/", 1)[-1]
        spec = specs.get(provider_id)
        if spec is None:
            raise ValueError(f"No digest spec for {provider_id}")
        receipts.append(
            apply_item(
                base_url=base_url,
                headers=headers,
                item=item,
                spec=spec,
            )
        )
    return receipts


if __name__ == "__main__":
    raise SystemExit(main())
