"""EmptyOS App SDK."""

from emptyos.runtime.atomic_io import atomic_write_bytes, atomic_write_text
from emptyos.sdk import dimensions, formulas

# Practice app shared modules
from emptyos.sdk.agent_runner import (
    AgentRunResult,
    AgentRunSpec,
    AgentRunner,
    ClaudeCliRunner,
    EosAgentRunner,
    effective_runner_config,
    resolve_agent_runner,
    resolve_app_runner,
)
from emptyos.sdk.audio import assess_fillers, assess_pacing, compute_speech_metrics
from emptyos.sdk.base_app import BaseApp
from emptyos.sdk.base_engine import BaseEngine
from emptyos.sdk.base_plugin import BasePlugin
from emptyos.sdk.record_store import JsonRecordStore
from emptyos.sdk.capture_routes import (
    CAPTURE_DESTINATIONS,
    CaptureDestination,
    apply_capture_direct,
    capture_destination,
    propose_capture,
    shape_capture_args,
)
from emptyos.sdk.chat_session import ChatSessionStore
from emptyos.sdk.column_types import ColumnType, ColumnTypeRegistry
from emptyos.sdk.decorators import cli_command, on_event, scheduled, web_route, ws_route
from emptyos.sdk.embeddings import (
    Embedder,
    EmbeddingIndex,
    build_index,
    build_retrieval_query,
    cosine,
)
from emptyos.sdk.external_service import ExternalServiceBase
from emptyos.sdk.intents import (
    DEFAULT_INTENT_PROMPT_HEADER,
    INTENT_RE,
    MAX_INTENTS_IN_PROMPT,
    build_plan_dict,
    find_intents,
    intent_embedding_text,
    render_intent_block,
    scope_intents,
    scope_intents_by_relevance,
    validate_args,
)
from emptyos.sdk.markdown_render import (
    convert_callouts,
    extract_images,
    render_markdown,
    resolve_wikilinks,
)
from emptyos.sdk.conformance import ConformanceCase, ConformanceRegistry
from emptyos.sdk.method_registry import MethodRegistry, MethodSpec
from emptyos.sdk.multi_lens import multi_lens_analyze
from emptyos.sdk.operation import (
    AuditSpec,
    OperationError,
    OperationResult,
    OperationRunner,
    OperationSpec,
    RetryPolicy,
    UndoSpec,
    operation_error_from_exception,
    operation_tool_display,
)
from emptyos.sdk.parallel_text import parse_parallel_md
from emptyos.sdk.schema import (
    field_help,
    field_range,
    field_unit,
    inputs_hash,
    schema_field,
    to_jsonschema,
    validate,
)
from emptyos.sdk.scoring import alignment_to_events, lcs_score, word_accuracy
from emptyos.sdk.session import HistoryStore, SessionStore
from emptyos.sdk.srs import (
    due_items as srs_due_items,
)
from emptyos.sdk.srs import (
    review_stats as srs_review_stats,
)
from emptyos.sdk.srs import (
    fsrs_schedule,
    quality_to_rating,
    repair_legacy_schedule,
    score_to_rating,
    sm2_schedule,
)
from emptyos.sdk.stats import daily_counts, practice_stats, progress_percent, rolling_average
from emptyos.sdk.claude_run_stream import (
    stream_claude_run_events,
    transform_stream_json_line,
)
from emptyos.sdk.streaming import NDJSON_MEDIA, ndjson_response
from emptyos.sdk.tabular import (
    QueryUnavailable,
    duckdb_available,
    flatten_note_records,
    query_files,
    query_mixed,
    query_rows,
)
from emptyos.sdk.time_series import TimeSeriesCounter, days_ago_utc, today_utc
from emptyos.sdk.toolchain import probe_binary_version, resolve_binary
from emptyos.sdk.utils import (
    CAPTURE_LINE_RE,
    DONE_PATTERN,
    DUE_INLINE_PATTERN,
    DUE_PATTERN,
    ROOM_PATTERN,
    TASK_RE,
    WIKILINK_RE,
    compute_task_decay,
    config_flag,
    ensure_column,
    extract_due,
    csv_download_response,
    csv_to_rows,
    sniff_columns,
    read_upload_text,
    extract_wikilinks,
    fm_list,
    fm_scalar,
    fm_str,
    fmt_num,
    format_markdown_table,
    load_json,
    new_id,
    normalize_clock_time,
    normalize_relative_date,
    normalize_relative_offset,
    now_iso,
    parse_captures,
    parse_frontmatter,
    parse_json_fence,
    parse_llm_json,
    parse_llm_svg,
    parse_markdown_table,
    rows_to_csv,
    save_json,
    set_frontmatter_field,
    slug_from_path,
    slugify,
    slugify_unicode,
    first_prose_line,
    strip_frontmatter,
    strip_markdown,
    task_tier,
    today_iso,
    unique_slug,
    is_archived,
)
from emptyos.sdk.music_library import (
    AUDIO_EXTS,
    SIDECAR_MD,
    AlbumLibrary,
    LibraryMixin,
    SongLibrary,
)
from emptyos.sdk.pdf import PDF_THEMES, PdfStyle, render_markdown_pdf, resolve_pdf_style
from emptyos.sdk.pending_store import PendingStore
from emptyos.sdk.run_center import RunCenterMixin
from emptyos.sdk.run_status import RUN_PHASE_COLORS, RUN_PHASES, normalize_run_status
from emptyos.sdk.vault_library import VaultLibrary
from emptyos.sdk.vault_model import (
    VaultModel,
    bool_validator,
    date_or_none_validator,
    float_or_none_validator,
    int_or_none_validator,
)
from emptyos.sdk.web_search import (
    UNTRUSTED_SOURCE_CLAUSE,
    SourceFencer,
    arxiv_search,
    clean_page_text,
    crossref_lookup,
    ddg_search,
    github_search,
    hn_search,
    is_http_url,
    is_public_web_url,
    openalex_search,
    read_web_source,
    triage_hits,
    semantic_scholar_search,
    site_label,
    source_fencer,
    untrusted_block,
    wikipedia_search,
)
from emptyos.sdk.deep_loop import (
    FOLLOWUP_SYSTEM,
    DeepLoopResult,
    dedupe_sources,
    deepen,
)
from emptyos.sdk.worktree import ensure_worktree, git_run, py_compile_files
from emptyos.sdk.google_auth import PermanentAuthLatch, is_permanent_auth_error
from emptyos.capabilities.spend_cap import SpendCapReached

__all__ = [
    "SpendCapReached",
    "DONE_PATTERN",
    "DUE_INLINE_PATTERN",
    "DUE_PATTERN",
    "ROOM_PATTERN",
    "TASK_RE",
    "compute_task_decay",
    "extract_due",
    "task_tier",
    "BaseApp",
    "BaseEngine",
    "BasePlugin",
    "AgentRunResult",
    "AgentRunSpec",
    "AgentRunner",
    "ClaudeCliRunner",
    "EosAgentRunner",
    "resolve_agent_runner",
    "resolve_app_runner",
    "effective_runner_config",
    "Embedder",
    "EmbeddingIndex",
    "build_index",
    "build_retrieval_query",
    "cosine",
    "ExternalServiceBase",
    "PdfStyle",
    "PDF_THEMES",
    "render_markdown_pdf",
    "resolve_pdf_style",
    "multi_lens_analyze",
    "parse_parallel_md",
    "DEFAULT_INTENT_PROMPT_HEADER",
    "INTENT_RE",
    "MAX_INTENTS_IN_PROMPT",
    "build_plan_dict",
    "find_intents",
    "intent_embedding_text",
    "render_intent_block",
    "scope_intents",
    "scope_intents_by_relevance",
    "validate_args",
    "cli_command",
    "on_event",
    "scheduled",
    "web_route",
    "ws_route",
    "CAPTURE_DESTINATIONS",
    "CaptureDestination",
    "apply_capture_direct",
    "capture_destination",
    "propose_capture",
    "shape_capture_args",
    "CAPTURE_LINE_RE",
    "config_flag",
    "ensure_column",
    "fm_str",
    "fm_list",
    "fm_scalar",
    "load_json",
    "new_id",
    "normalize_clock_time",
    "normalize_relative_date",
    "normalize_relative_offset",
    "save_json",
    "parse_captures",
    "parse_frontmatter",
    "parse_json_fence",
    "parse_llm_json",
    "parse_llm_svg",
    "set_frontmatter_field",
    "slug_from_path",
    "slugify",
    "slugify_unicode",
    "unique_slug",
    "is_archived",
    "strip_frontmatter",
    "WIKILINK_RE",
    "extract_wikilinks",
    "parse_markdown_table",
    "format_markdown_table",
    "fmt_num",
    "rows_to_csv",
    "csv_to_rows",
    "csv_download_response",
    "sniff_columns",
    "read_upload_text",
    "QueryUnavailable",
    "duckdb_available",
    "query_rows",
    "query_files",
    "query_mixed",
    "flatten_note_records",
    "first_prose_line",
    "strip_markdown",
    "today_iso",
    "now_iso",
    "SessionStore",
    "HistoryStore",
    "ChatSessionStore",
    "compute_speech_metrics",
    "assess_pacing",
    "assess_fillers",
    "atomic_write_bytes",
    "atomic_write_text",
    "JsonRecordStore",
    "lcs_score",
    "word_accuracy",
    "alignment_to_events",
    "practice_stats",
    "rolling_average",
    "progress_percent",
    "daily_counts",
    "PendingStore",
    "VaultLibrary",
    "VaultModel",
    "int_or_none_validator",
    "float_or_none_validator",
    "bool_validator",
    "date_or_none_validator",
    "SongLibrary",
    "AlbumLibrary",
    "LibraryMixin",
    "SIDECAR_MD",
    "AUDIO_EXTS",
    "ColumnType",
    "ColumnTypeRegistry",
    "formulas",
    "fsrs_schedule",
    "quality_to_rating",
    "repair_legacy_schedule",
    "score_to_rating",
    "sm2_schedule",
    "srs_due_items",
    "srs_review_stats",
    "TimeSeriesCounter",
    "today_utc",
    "days_ago_utc",
    "probe_binary_version",
    "resolve_binary",
    "NDJSON_MEDIA",
    "ndjson_response",
    "stream_claude_run_events",
    "transform_stream_json_line",
    "dimensions",
    "render_markdown",
    "resolve_wikilinks",
    "convert_callouts",
    "extract_images",
    "MethodRegistry",
    "MethodSpec",
    "AuditSpec",
    "OperationError",
    "OperationResult",
    "OperationRunner",
    "OperationSpec",
    "RetryPolicy",
    "UndoSpec",
    "operation_error_from_exception",
    "operation_tool_display",
    "ConformanceCase",
    "ConformanceRegistry",
    "schema_field",
    "validate",
    "to_jsonschema",
    "inputs_hash",
    "field_unit",
    "field_range",
    "field_help",
    "git_run",
    "ensure_worktree",
    "py_compile_files",
    "PermanentAuthLatch",
    "is_permanent_auth_error",
    "normalize_run_status",
    "RunCenterMixin",
    "RUN_PHASES",
    "RUN_PHASE_COLORS",
    "ddg_search",
    "github_search",
    "hn_search",
    "arxiv_search",
    "semantic_scholar_search",
    "openalex_search",
    "crossref_lookup",
    "wikipedia_search",
    "site_label",
    "is_http_url",
    "is_public_web_url",
    "clean_page_text",
    "read_web_source",
    "triage_hits",
    "UNTRUSTED_SOURCE_CLAUSE",
    "untrusted_block",
    "SourceFencer",
    "source_fencer",
    "deepen",
    "DeepLoopResult",
    "dedupe_sources",
    "FOLLOWUP_SYSTEM",
]
